Repository mozilla/activity-stream, pull requests merged in 2018-03, with the labels that each got.

#4002 chore(mc): Port Bug 1440284 - change this.EXPORTED_SYMBOLS back to var EXPORTED_SYMBOLS in JS modules, r=mccr8.
  .eslintrc.js
  system-addon/common/Actions.jsm
  system-addon/common/Dedupe.jsm
  system-addon/common/PerfService.jsm
  system-addon/common/PrerenderData.jsm
  system-addon/common/Reducers.jsm
  system-addon/lib/ActivityStream.jsm
  system-addon/lib/ActivityStreamMessageChannel.jsm
  system-addon/lib/ActivityStreamPrefs.jsm
  system-addon/lib/FaviconFeed.jsm
  system-addon/lib/FilterAdult.jsm
  system-addon/lib/HighlightsFeed.jsm
  system-addon/lib/LinksCache.jsm
  system-addon/lib/ManualMigration.jsm
  system-addon/lib/NewTabInit.jsm
  system-addon/lib/PersistentCache.jsm
  system-addon/lib/PlacesFeed.jsm
  system-addon/lib/PrefsFeed.jsm
  system-addon/lib/Screenshots.jsm
  system-addon/lib/SectionsManager.jsm
  system-addon/lib/ShortURL.jsm
  system-addon/lib/SnippetsFeed.jsm
  system-addon/lib/Store.jsm
  system-addon/lib/SystemTickFeed.jsm
  system-addon/lib/TelemetryFeed.jsm
  system-addon/lib/TippyTopProvider.jsm
  system-addon/lib/TopSitesFeed.jsm
  system-addon/lib/TopStoriesFeed.jsm
  system-addon/lib/UTEventReporting.jsm
  system-addon/lib/UserDomainAffinityProvider.jsm
  system-addon/ping-centre/PingCentre.jsm
  system-addon/vendor/Redux.jsm
Labels: PR / R+ with nits

#4009 Fix Bug 1441931 - Use open_url provided by Pocket for 'saved to pocket' items in highlights
  system-addon/common/Reducers.jsm
  system-addon/content-src/components/Card/Card.jsx
  system-addon/lib/PlacesFeed.jsm
  system-addon/test/unit/content-src/components/Card.test.jsx
  system-addon/test/unit/lib/PlacesFeed.test.js
Labels: PR / R+

#4011 Bug 1441984 - Only show OpenInPrivateBrowsing option if private browsing enabled
  system-addon/content-src/components/LinkMenu/LinkMenu.jsx
  system-addon/content-src/lib/link-menu-options.js
  system-addon/lib/PrefsFeed.jsm
  system-addon/test/unit/content-src/components/Card.test.jsx
  system-addon/test/unit/content-src/components/LinkMenu.test.jsx
  system-addon/test/unit/lib/PrefsFeed.test.js
Labels: PR / R+ with nits

#4005 chore(mc): Backport of Bug 1440276 - Activity Stream spikes after Bookmark activity, triggering lots of main thread work
  system-addon/lib/PlacesFeed.jsm
Labels: PR / Needs review

#4012 chore(mc): Port Bug 1433958 - Change code that sets nsIURI.ref to use nsIURIMutator r=mayhemer
  system-addon/lib/FaviconFeed.jsm
  system-addon/test/unit/lib/FaviconFeed.test.js
  system-addon/test/unit/unit-entry.js
Labels: PR / R+

#3989 Fix Bug 1425457 - Include some extra info to user event ping for top sites
  docs/v2-system-addon/data_dictionary.md
  docs/v2-system-addon/data_events.md
  system-addon/content-src/components/Card/Card.jsx
  system-addon/content-src/components/LinkMenu/LinkMenu.jsx
  system-addon/content-src/components/TopSites/TopSite.jsx
  system-addon/content-src/components/TopSites/TopSites.jsx
  system-addon/content-src/lib/link-menu-options.js
  system-addon/test/schemas/pings.js
  system-addon/test/unit/content-src/components/Card.test.jsx
  system-addon/test/unit/content-src/components/LinkMenu.test.jsx
  system-addon/test/unit/content-src/components/TopSites.test.jsx
Labels: PR / R+

#4016 chore(strings): Add strings for about:preferences and top site custom images
  CODEOWNERS
  locales/en-US/strings.properties
Labels: PR / R+

#4021 Fix Bug 1442992 - Remove second argument from Cu.reportError call
  system-addon/lib/SectionsManager.jsm
Labels: PR / R+

#4020 Fix Bug 1441278 - Missing line numbers in failing unit tests
  package.json
Labels: PR / R+

#4013 Add suggested Bugzilla workflow for data reviews
  docs/v2-system-addon/telemetry.md
Labels: PR / Needs review

#4019 Fix Bug 1443243 - Preloaded tab is sending impression ping after section was disabled
  system-addon/content-src/components/Sections/Sections.jsx
  system-addon/test/unit/content-src/components/Sections.test.jsx
Labels: PR / R+

#4025 Fix Bug 1442193 - show section context menu button on :focus
  system-addon/content-src/components/CollapsibleSection/_CollapsibleSection.scss
Labels: PR / Needs review

#4022 Fix Bug 1433212 - Implement section reordering
  system-addon/common/Actions.jsm
  system-addon/common/PrerenderData.jsm
  system-addon/common/Reducers.jsm
  system-addon/content-src/components/Base/Base.jsx
  system-addon/content-src/components/CollapsibleSection/CollapsibleSection.jsx
  system-addon/content-src/components/CollapsibleSection/_CollapsibleSection.scss
  system-addon/content-src/components/ContextMenu/ContextMenu.jsx
  system-addon/content-src/components/ContextMenu/_ContextMenu.scss
  system-addon/content-src/components/SectionMenu/SectionMenu.jsx
  system-addon/content-src/components/Sections/Sections.jsx
  system-addon/content-src/components/TopSites/TopSites.jsx
  system-addon/content-src/lib/section-menu-options.js
  system-addon/lib/ActivityStream.jsm
  system-addon/lib/HighlightsFeed.jsm
  system-addon/lib/SectionsManager.jsm
  system-addon/test/schemas/pings.js
  system-addon/test/unit/common/Reducers.test.js
  system-addon/test/unit/content-src/components/ContextMenu.test.jsx
  system-addon/test/unit/content-src/components/SectionMenu.test.jsx
  system-addon/test/unit/content-src/components/Sections.test.jsx
  system-addon/test/unit/lib/HighlightsFeed.test.js
  system-addon/test/unit/lib/SectionsManager.test.js
Labels: PR / R+

#4018 Fix Bug 1433209 - Remove unused strings to simplify translating
  locales/en-US/strings.properties
  system-addon/test/unit/content-src/components/PreferencesPane.test.jsx
Labels: PR / Needs review

#4023 Fix Bug 1443347 - Adjust styles for larger cards on wide layout
  system-addon/content-src/components/Card/_Card.scss
Labels: PR / Needs review

#4029 chore(l10n): Update L10n from changeset 892265c8cfb90dff0763a57ceec6415525900f24
  locales/an/strings.properties
  locales/az/strings.properties
  locales/bg/strings.properties
  locales/br/strings.properties
  locales/bs/strings.properties
  locales/cak/strings.properties
  locales/cs/strings.properties
  locales/cy/strings.properties
  locales/de/strings.properties
  locales/dsb/strings.properties
  locales/es-AR/strings.properties
  locales/es-CL/strings.properties
  locales/es-ES/strings.properties
  locales/et/strings.properties
  locales/fi/strings.properties
  locales/fr/strings.properties
  locales/fy-NL/strings.properties
  locales/gd/strings.properties
  locales/he/strings.properties
  locales/hsb/strings.properties
  locales/hu/strings.properties
  locales/it/strings.properties
  locales/ja/strings.properties
  locales/ka/strings.properties
  locales/kab/strings.properties
  locales/kk/strings.properties
  locales/lt/strings.properties
  locales/lv/strings.properties
  locales/mk/strings.properties
  locales/ms/strings.properties
  locales/nb-NO/strings.properties
  locales/nl/strings.properties
  locales/nn-NO/strings.properties
  locales/pl/strings.properties
  locales/pt-PT/strings.properties
  locales/sk/strings.properties
  locales/sl/strings.properties
  locales/sq/strings.properties
  locales/sr/strings.properties
  locales/sv-SE/strings.properties
  locales/th/strings.properties
  locales/tr/strings.properties
  locales/uk/strings.properties
  locales/zh-CN/strings.properties
  locales/zh-TW/strings.properties
Labels: PR / Needs review

#4026 Bug 1441570 - Add a test to verify that a topsite can be edited from the context menu.
  system-addon/test/functional/mochitest/browser.ini
  system-addon/test/functional/mochitest/browser_topsites_contextMenu_edit.js
Labels: PR / Needs work

#4014 Fix Bug 1438368 - about:home about:newtab snippet blocking
  system-addon/common/Actions.jsm
  system-addon/common/Reducers.jsm
  system-addon/content-src/lib/snippets.js
  system-addon/lib/ActivityStreamStorage.jsm
  system-addon/lib/SnippetsFeed.jsm
  system-addon/test/unit/common/Reducers.test.js
  system-addon/test/unit/content-src/lib/snippets.test.js
  system-addon/test/unit/lib/ActivityStreamStorage.test.js
  system-addon/test/unit/lib/SnippetsFeed.test.js
Labels: PR / R+

#4031 Revert 'Bug 1441570 - Add a test to verify that a topsite can be edited from the context menu.'
  system-addon/test/functional/mochitest/browser.ini
  system-addon/test/functional/mochitest/browser_topsites_contextMenu_edit.js
Labels: PR / R+

#4034 Fix Bug 1443908 - position: fixed; for Add Top Site modal
  system-addon/content-src/components/TopSites/_TopSites.scss
Labels: PR / Needs review

#4028 Fix Bug 1433209 - Remove unused strings
  locales/en-US/strings.properties
  system-addon/test/unit/content-src/components/CollapsibleSection.test.jsx
  system-addon/test/unit/content-src/components/PreferencesPane.test.jsx
Labels: PR / Needs review

#4035 Fix Bug 1442383 - Activity stream spends a lot time fetching highlights after bookmark sync
  system-addon/lib/HighlightsFeed.jsm
  system-addon/lib/PlacesFeed.jsm
  system-addon/test/unit/lib/HighlightsFeed.test.js
  system-addon/test/unit/lib/PlacesFeed.test.js
Labels: PR / R+

#4037 Fix Bug 1444518 - Ignore bookmarks added and removed during an import or restore
  system-addon/lib/HighlightsFeed.jsm
  system-addon/lib/PlacesFeed.jsm
  system-addon/test/unit/lib/HighlightsFeed.test.js
  system-addon/test/unit/lib/PlacesFeed.test.js
Labels: PR / R+

#4038 fix(nobug): Use regular size pocket icon
  system-addon/content-src/components/Card/types.js
  system-addon/content-src/styles/_icons.scss
Labels: PR / R+

#4015 Fix Bug 1404890 - Move new tab settings for sections to about:preferences
  system-addon/lib/AboutPreferences.jsm
  system-addon/lib/ActivityStream.jsm
  system-addon/lib/SectionsManager.jsm
  system-addon/test/unit/lib/AboutPreferences.test.js
  system-addon/test/unit/lib/ActivityStream.test.js
  system-addon/test/unit/unit-entry.js
Labels: PR / Needs review

#3970 Fix Bug 1410378 - Add automated test for "Top Sites - Add Top Site"
  system-addon/test/functional/mochitest/browser_topsites_section.js
Labels: PR / R+ with nits

#4041 Fix Bug 1432672 - Remove sidebar preferences and have gear open about:preferences
  system-addon/common/Reducers.jsm
  system-addon/content-src/components/Base/Base.jsx
  system-addon/content-src/components/Base/_Base.scss
  system-addon/content-src/components/PreferencesPane/PreferencesPane.jsx
  system-addon/content-src/components/PreferencesPane/_PreferencesPane.scss
  system-addon/content-src/lib/section-menu-options.js
  system-addon/content-src/styles/_activity-stream.scss
  system-addon/lib/AboutPreferences.jsm
  system-addon/test/unit/common/Reducers.test.js
  system-addon/test/unit/content-src/components/Base.test.jsx
  system-addon/test/unit/content-src/components/PreferencesPane.test.jsx
  system-addon/test/unit/lib/AboutPreferences.test.js
Labels: PR / Needs review

#4042 fix(preferences): Use plain DOM instead of XBL appendItem
  system-addon/lib/AboutPreferences.jsm
  system-addon/test/unit/lib/AboutPreferences.test.js
Labels: PR / R+

#4043 Backport new bookmark change sources
  system-addon/lib/PlacesFeed.jsm
  system-addon/test/unit/lib/PlacesFeed.test.js
Labels: PR / R+

#4045 Fix Bug 1446395 - Assign context menus in Highlights on a per card type basis
  system-addon/content-src/lib/link-menu-options.js
  system-addon/lib/SectionsManager.jsm
  system-addon/test/unit/content-src/components/LinkMenu.test.jsx
  system-addon/test/unit/lib/SectionsManager.test.js
Labels: PR / R+

#4050 Fix Bug 1384094 - High CPU. network traffic and memory usage when open Newtab page if you have opened / bookmarked a problematic/ huge game page in the past
  system-addon/lib/Screenshots.jsm
  system-addon/test/unit/lib/Screenshots.test.js
Labels: PR / R+

#4040 Fix Bug 1445157 - Move isCollapsed pref to IndexedDB
  system-addon/common/Actions.jsm
  system-addon/common/PrerenderData.jsm
  system-addon/common/Reducers.jsm
  system-addon/content-src/components/CollapsibleSection/CollapsibleSection.jsx
  system-addon/content-src/components/Sections/Sections.jsx
  system-addon/content-src/components/TopSites/TopSites.jsx
  system-addon/content-src/lib/section-menu-options.js
  system-addon/lib/ActivityStream.jsm
  system-addon/lib/ActivityStreamStorage.jsm
  system-addon/lib/PrefsFeed.jsm
  system-addon/lib/SectionsManager.jsm
  system-addon/lib/TopSitesFeed.jsm
  system-addon/test/unit/common/PrerenderData.test.js
  system-addon/test/unit/common/Reducers.test.js
  system-addon/test/unit/content-src/components/CollapsibleSection.test.jsx
  system-addon/test/unit/content-src/components/SectionMenu.test.jsx
  system-addon/test/unit/content-src/components/Sections.test.jsx
  system-addon/test/unit/lib/ActivityStream.test.js
  system-addon/test/unit/lib/ActivityStreamStorage.test.js
  system-addon/test/unit/lib/PrefsFeed.test.js
  system-addon/test/unit/lib/SectionsManager.test.js
  system-addon/test/unit/lib/TopSitesFeed.test.js
Labels: PR / R+ with nits

#3891 Fix Bug 1402654 - Allow custom image / thumbnail for an edited top site
  docs/v2-system-addon/data_dictionary.md
  docs/v2-system-addon/data_events.md
  system-addon/common/Actions.jsm
  system-addon/common/Reducers.jsm
  system-addon/content-src/components/TopSites/TopSite.jsx
  system-addon/content-src/components/TopSites/TopSiteForm.jsx
  system-addon/content-src/components/TopSites/TopSiteFormInput.jsx
  system-addon/content-src/components/TopSites/TopSites.jsx
  system-addon/content-src/components/TopSites/_TopSites.scss
  system-addon/content-src/styles/_variables.scss
  system-addon/lib/TopSitesFeed.jsm
  system-addon/test/schemas/pings.js
  system-addon/test/unit/common/Reducers.test.js
  system-addon/test/unit/content-src/components/TopSites.test.jsx
  system-addon/test/unit/lib/TelemetryFeed.test.js
  system-addon/test/unit/lib/TopSitesFeed.test.js
Labels: PR / R+ with nits

#4053 Fix Bug 1444616 - fix context menu button alignment
  system-addon/content-src/components/CollapsibleSection/CollapsibleSection.jsx
  system-addon/content-src/components/CollapsibleSection/_CollapsibleSection.scss
  system-addon/content-src/components/Sections/Sections.jsx
  system-addon/content-src/components/TopSites/TopSites.jsx
  system-addon/content-src/styles/_variables.scss
Labels: PR / Needs review

#4048 Fix Bug 1431469 - expose previous session end (UNINIT) to snippets
  system-addon/lib/SnippetsFeed.jsm
  system-addon/test/unit/lib/ActivityStreamStorage.test.js
  system-addon/test/unit/lib/SnippetsFeed.test.js
Labels: PR / R+

#4052 Fix Bug 1384094 - High CPU. network traffic and memory usage when open Newtab page if you have opened / bookmarked a problematic/ huge game page in the past
  system-addon/lib/Screenshots.jsm
  system-addon/test/unit/lib/Screenshots.test.js
Labels: PR / R+

#4054 Revert "Fix Bug 1445157 - Move isCollapsed pref to IndexedDB."
  system-addon/common/Actions.jsm
  system-addon/common/PrerenderData.jsm
  system-addon/common/Reducers.jsm
  system-addon/content-src/components/CollapsibleSection/CollapsibleSection.jsx
  system-addon/content-src/components/Sections/Sections.jsx
  system-addon/content-src/components/TopSites/TopSites.jsx
  system-addon/content-src/lib/section-menu-options.js
  system-addon/lib/ActivityStream.jsm
  system-addon/lib/ActivityStreamStorage.jsm
  system-addon/lib/PrefsFeed.jsm
  system-addon/lib/SectionsManager.jsm
  system-addon/lib/TopSitesFeed.jsm
  system-addon/test/unit/common/PrerenderData.test.js
  system-addon/test/unit/common/Reducers.test.js
  system-addon/test/unit/content-src/components/CollapsibleSection.test.jsx
  system-addon/test/unit/content-src/components/SectionMenu.test.jsx
  system-addon/test/unit/content-src/components/Sections.test.jsx
  system-addon/test/unit/lib/ActivityStream.test.js
  system-addon/test/unit/lib/ActivityStreamStorage.test.js
  system-addon/test/unit/lib/PrefsFeed.test.js
  system-addon/test/unit/lib/SectionsManager.test.js
  system-addon/test/unit/lib/TopSitesFeed.test.js
Labels: PR / Needs review

#4055 fix(screenshots): Ignore failures when trying to write empty file
  system-addon/lib/Screenshots.jsm
Labels: PR / Needs review

#4057 Fix Bug 1421428 - Link rich icon for redirected url
  system-addon/lib/FaviconFeed.jsm
  system-addon/lib/FilterAdult.jsm
  system-addon/lib/Utils.jsm
  system-addon/test/unit/lib/FaviconFeed.test.js
  system-addon/test/unit/lib/FilterAdult.test.js
  system-addon/test/unit/unit-entry.js
Labels: PR / Needs review

#4063 Fix Bug 1444616 - push section menu button half a pixel up
  system-addon/content-src/components/Base/_Base.scss
  system-addon/content-src/components/CollapsibleSection/_CollapsibleSection.scss
  system-addon/content-src/styles/_variables.scss
Labels: PR / R+

#4065 Fix Bug 1448394 - fix cut off g in Trending
  system-addon/content-src/components/Card/_Card.scss
Labels: PR / R+

#4064 chore (codequality) #nobug Remove unnecessary usage of injector
  system-addon/test/unit/lib/SystemTickFeed.test.js
Labels: PR / Needs review

#4066 chore(tests): Clean up unnecessary injector and wrong global setting
  system-addon/test/unit/lib/PlacesFeed.test.js
  system-addon/test/unit/lib/UserDomainAffinityProvider.test.js
  system-addon/test/unit/unit-entry.js
  system-addon/test/unit/utils.js
Labels: PR / Needs review

#4058 Fix Bug 1445157 - Move isCollapsed pref to IndexedDB
  system-addon/common/Actions.jsm
  system-addon/common/PrerenderData.jsm
  system-addon/common/Reducers.jsm
  system-addon/content-src/components/CollapsibleSection/CollapsibleSection.jsx
  system-addon/content-src/components/Sections/Sections.jsx
  system-addon/content-src/components/TopSites/TopSites.jsx
  system-addon/content-src/lib/section-menu-options.js
  system-addon/lib/ActivityStream.jsm
  system-addon/lib/ActivityStreamStorage.jsm
  system-addon/lib/PrefsFeed.jsm
  system-addon/lib/SectionsManager.jsm
  system-addon/lib/TopSitesFeed.jsm
  system-addon/test/unit/common/PrerenderData.test.js
  system-addon/test/unit/common/Reducers.test.js
  system-addon/test/unit/content-src/components/CollapsibleSection.test.jsx
  system-addon/test/unit/content-src/components/SectionMenu.test.jsx
  system-addon/test/unit/content-src/components/Sections.test.jsx
  system-addon/test/unit/lib/ActivityStream.test.js
  system-addon/test/unit/lib/ActivityStreamStorage.test.js
  system-addon/test/unit/lib/PrefsFeed.test.js
  system-addon/test/unit/lib/SectionsManager.test.js
  system-addon/test/unit/lib/TopSitesFeed.test.js
Labels: PR / R+ with nits

#4059 Fix Bug 1421682 - Activity Streams exhausts file descriptors capturing screenshots when large numbers of bookmarks are added at once
  system-addon/common/Actions.jsm
  system-addon/common/Reducers.jsm
  system-addon/lib/HighlightsFeed.jsm
  system-addon/lib/PlacesFeed.jsm
  system-addon/lib/TopSitesFeed.jsm
  system-addon/test/unit/common/Reducers.test.js
  system-addon/test/unit/lib/HighlightsFeed.test.js
  system-addon/test/unit/lib/PlacesFeed.test.js
  system-addon/test/unit/lib/TopSitesFeed.test.js
  system-addon/test/unit/unit-entry.js
Labels: PR / R+ with nits

#4056 Bug 1432675 - Add Message Center experiment
  system-addon/content-src/components/Base/Base.jsx
  system-addon/content-src/components/MessageCenterAdmin/MessageCenterAdmin.jsx
  system-addon/content-src/components/MessageCenterAdmin/MessageCenterAdmin.scss
  system-addon/content-src/lib/snippets.js
  system-addon/content-src/message-center/components/Button.jsx
  system-addon/content-src/message-center/components/SnippetBase.jsx
  system-addon/content-src/message-center/message-center-content.jsx
  system-addon/content-src/message-center/templates/SimpleSnippet.jsx
  system-addon/content-src/styles/_activity-stream.scss
  system-addon/content-src/styles/_variables.scss
  system-addon/lib/ActivityStream.jsm
  system-addon/lib/MessageCenterFeed.jsm
  system-addon/lib/MessageCenterRouter.jsm
  system-addon/test/unit/content-src/lib/snippets.test.js
  system-addon/test/unit/lib/ActivityStream.test.js
  system-addon/test/unit/message-center/MessageCenterRouter.test.js
  system-addon/test/unit/message-center/constants.js
  system-addon/test/unit/unit-entry.js
Labels: PR / R+

#4070 Fix Bug 1446195 - Update story preferences description and link
  locales/en-US/strings.properties
  system-addon/lib/AboutPreferences.jsm
  system-addon/lib/ActivityStream.jsm
  system-addon/lib/SectionsManager.jsm
  system-addon/test/unit/lib/AboutPreferences.test.js
Labels: PR / R+

#4062 Fix Bug 1449292 - TopSites don't update their custom screenshot
  system-addon/lib/TopSitesFeed.jsm
  system-addon/test/unit/lib/TopSitesFeed.test.js
Labels: PR / Needs review

#4068 fix(storage): Lazily open database on first access instead of requiri…
  system-addon/lib/ActivityStream.jsm
  system-addon/lib/ActivityStreamStorage.jsm
  system-addon/lib/PrefsFeed.jsm
  system-addon/lib/SectionsManager.jsm
  system-addon/lib/SnippetsFeed.jsm
  system-addon/lib/TopSitesFeed.jsm
  system-addon/test/unit/lib/ActivityStream.test.js
  system-addon/test/unit/lib/ActivityStreamStorage.test.js
  system-addon/test/unit/lib/SectionsManager.test.js
  system-addon/test/unit/lib/TopSitesFeed.test.js
Labels: PR / Needs review

#4072 chore(FaviconFeed): Remove the url hashing
  system-addon/lib/FaviconFeed.jsm
  system-addon/lib/FilterAdult.jsm
  system-addon/lib/Utils.jsm
  system-addon/test/unit/lib/FaviconFeed.test.js
  system-addon/test/unit/lib/FilterAdult.test.js
Labels: PR / R+ with nits

#4067 chore (perf): lazy load NavHistoryService in UserDomainAffinityProvider
  system-addon/lib/UserDomainAffinityProvider.jsm
  system-addon/test/unit/lib/UserDomainAffinityProvider.test.js
Labels: PR / Needs review

#4073 chore(cleanup): fix some missed r? comments from 997f422
  system-addon/content-src/components/Base/Base.jsx
  system-addon/content-src/components/CollapsibleSection/_CollapsibleSection.scss
Labels: PR / Needs review
