Repository mozilla/activity-stream, pull requests merged in 2018-10, with the labels that each got.

#4458 Fix Bug 1463775 - Buttons from the new onboarding have the wrong highlight on Dark theme
  content-src/asrouter/components/ModalOverlay/_ModalOverlay.scss
  content-src/asrouter/templates/OnboardingMessage/_OnboardingMessage.scss
Labels: PR / Needs review

#4459 Fix Bug 1488462 - Big slowdown happening every x minutes
  lib/HighlightsFeed.jsm
  test/unit/lib/HighlightsFeed.test.js
Labels: PR / R+ with nits

#4460 Fix Bug 1495546 - Localization fails in OnboardingMessageProvider if we've already localized strings before
  lib/OnboardingMessageProvider.jsm
Labels: PR / R+

#4454 Fix Bug 1485069 - Add client_id for Snippets reporting
  content-src/asrouter/templates/OnboardingMessage/OnboardingMessage.jsx
  docs/v2-system-addon/data_events.md
  lib/TelemetryFeed.jsm
  test/unit/lib/TelemetryFeed.test.js
Labels: PR / Awaiting data review

#4461 Backport Bug 1495517 - Migrate improvesearch.topSiteSearchShortcuts pref from ActivityStream.jsm to firefox.js r=k88hudson
  lib/ActivityStream.jsm
  lib/PrefsFeed.jsm
Labels: PR / R+

#4438 Fix Bug 1492086 - Add ASR Snippets Newsletter template
  content-src/asrouter/asrouter-content.jsx
  content-src/asrouter/components/Button/_Button.scss
  content-src/asrouter/components/SnippetBase/SnippetBase.jsx
  content-src/asrouter/components/SnippetBase/_SnippetBase.scss
  content-src/asrouter/templates/NewsletterSnippet/NewsletterSnippet.jsx
  content-src/asrouter/templates/NewsletterSnippet/NewsletterSnippet.schema.json
  content-src/asrouter/templates/NewsletterSnippet/_NewsletterSnippet.scss
  content-src/asrouter/templates/SimpleSnippet/SimpleSnippet.jsx
  content-src/asrouter/templates/SimpleSnippet/_SimpleSnippet.scss
  content-src/styles/_activity-stream.scss
  lib/ASRouter.jsm
  test/unit/asrouter/ASRouter.test.js
  test/unit/asrouter/constants.js
  test/unit/asrouter/templates/NewsletterSnippet.test.jsx
Labels: PR / R+

#4467 Fix Bug 1496167 - Add installation source to addons installed from activitystream
  lib/ASRouter.jsm
  test/unit/asrouter/MessageLoaderUtils.test.js
Labels: PR / R+

#4464 Bug 1496212 - Update documentation for ASRouter targeting
  content-src/asrouter/docs/targeting-attributes.md
  content-src/asrouter/docs/targeting-guide.md
  content-src/asrouter/schemas/message-format.md
  karma.mc.config.js
  package-lock.json
  package.json
  test/unit/asrouter/TargetingDocs.test.js
Labels: PR / R+ with nits

#4462 Fix Bug 1477633 - Add tooltip text to dismiss button
  content-src/asrouter/components/SnippetBase/SnippetBase.jsx
  content-src/asrouter/templates/SimpleSnippet/SimpleSnippet.schema.json
Labels: PR / R+

#4465 Fix Bug 1496428 - Turn on new simplified onboarding experience for everyone
  common/Actions.jsm
  common/Reducers.jsm
  content-src/components/Base/_Base.scss
  content-src/lib/asroutercontent.js
  content-src/lib/snippets.js
  content-src/styles/_activity-stream.scss
  docs/v2-system-addon/snippets.md
  karma.mc.config.js
  lib/ASRouter.jsm
  lib/ASRouterPreferences.jsm
  lib/ASRouterTargeting.jsm
  lib/ActivityStream.jsm
  lib/OnboardingMessageProvider.jsm
  lib/PrefsFeed.jsm
  lib/SnippetsFeed.jsm
  mochitest.sh
  test/browser/browser_asrouter_targeting.js
  test/unit/activity-stream.test.jsx
  test/unit/asrouter/ASRouter.test.js
  test/unit/asrouter/ASRouterFeed.test.js
  test/unit/asrouter/ASRouterPreferences.test.js
  test/unit/asrouter/ASRouterTargeting.test.js
  test/unit/asrouter/TargetingDocs.test.js
  test/unit/content-src/lib/snippets.test.js
  test/unit/lib/PrefsFeed.test.js
  test/unit/lib/SnippetsFeed.test.js
Labels: PR / R+

#4469 Fix Bug 1496352 - Add SHOW_FIREFOX_ACCOUTS Router action
  common/Actions.jsm
  lib/ASRouter.jsm
  test/unit/asrouter/ASRouter.test.js
Labels: PR / R+

#4470 bug 1496246 - Update Pocket CTA implementation with feedback from Leg…
  content-src/components/CollapsibleSection/CollapsibleSection.jsx
  content-src/components/CollapsibleSection/_CollapsibleSection.scss
  content-src/components/PocketLoggedInCta/PocketLoggedInCta.jsx
  content-src/components/PocketLoggedInCta/_PocketLoggedInCta.scss
  lib/SectionsManager.jsm
  locales/en-US/strings.properties
Labels: PR / R+

#4472 chore(l10n): Update from l10n-central Fri Oct 05 2018 13:28:30 GMT-0400 (EDT)
  locales/bg/strings.properties
  locales/cak/strings.properties
  locales/de/strings.properties
  locales/es-CL/strings.properties
  locales/fr/strings.properties
  locales/gn/strings.properties
  locales/kab/strings.properties
  locales/kk/strings.properties
  locales/lij/strings.properties
  locales/nb-NO/strings.properties
  locales/nn-NO/strings.properties
  locales/ro/strings.properties
  locales/ru/strings.properties
  locales/sq/strings.properties
Labels: PR / Needs review

#4471 [Uplift backport] Bug 1488462 - Big slowdown happening every x minutes
  lib/HighlightsFeed.jsm
  test/unit/lib/HighlightsFeed.test.js
Labels: PR / On hold for now

#4463 [Uplift backport] Bug 1485069 - Add client_id for Snippets reporting
  content-src/asrouter/templates/OnboardingMessage/OnboardingMessage.jsx
  docs/v2-system-addon/data_events.md
  lib/TelemetryFeed.jsm
  test/unit/lib/TelemetryFeed.test.js
Labels: PR / On hold for now

#4468 [Uplift backport] Bug 1493041 - Topstories feed uninit can remove idle-daily observer before init has a chance to add it
  lib/TopStoriesFeed.jsm
  test/unit/lib/TopStoriesFeed.test.js
Labels: PR / On hold for now

#4476 bug 1489619 - Loading spocs from cache doesn't properly reset cam…
  lib/TopStoriesFeed.jsm
  test/unit/lib/TopStoriesFeed.test.js
Labels: PR / On hold for now

#4475 Bug 1488846 - Ensure pocket cta doesn't flash between logged in and o…
  common/Reducers.jsm
  content-src/components/Base/_Base.scss
  content-src/components/Sections/Sections.jsx
  content-src/components/Sections/_Sections.scss
  test/unit/common/Reducers.test.js
  test/unit/content-src/components/Sections.test.jsx
Labels: PR / On hold for now

#4480 bug 1496246 - Update Pocket CTA implementation with feedback from Leg…
  content-src/components/CollapsibleSection/CollapsibleSection.jsx
  content-src/components/CollapsibleSection/_CollapsibleSection.scss
  content-src/components/PocketLoggedInCta/PocketLoggedInCta.jsx
  content-src/components/PocketLoggedInCta/_PocketLoggedInCta.scss
  lib/SectionsManager.jsm
  locales/en-US/strings.properties
Labels: PR / On hold for now

#4477 Fix Bug 1497261 - Revert parameter rename
  lib/ASRouter.jsm
  test/unit/asrouter/ASRouter.test.js
Labels: PR / R+

#4485 Fix Bug 1495768 - add Amazon to Search Shortcuts for Austria
  lib/ActivityStream.jsm
Labels: PR / R+

#4483 Backport - Replace nsINavBookmarksService::onItemAdded with 'page-bookmarked'
  lib/PlacesFeed.jsm
  test/unit/lib/PlacesFeed.test.js
  test/unit/unit-entry.js
Labels: PR / In progress don't review yet

#4484 Fix Bug 1494778 - CFR should respect the xpinstall.enabled pref
  content-src/asrouter/docs/targeting-attributes.md
  lib/ASRouterTargeting.jsm
  lib/CFRMessageProvider.jsm
  test/browser/browser_asrouter_targeting.js
  test/unit/asrouter/CFRMessageProvider.test.js
Labels: PR / R+

#4478 Fix Bug 1492085 - Use the Newsletter template for FxA signup
  content-src/asrouter/asrouter-content.jsx
  content-src/asrouter/templates/SubmitFormSnippet/SubmitFormSnippet.jsx
  content-src/asrouter/templates/SubmitFormSnippet/SubmitFormSnippet.schema.json
  content-src/asrouter/templates/SubmitFormSnippet/_SubmitFormSnippet.scss
  content-src/styles/_activity-stream.scss
  test/unit/asrouter/asrouter-content.test.jsx
  test/unit/asrouter/constants.js
  test/unit/asrouter/templates/SubmitFormSnippet.test.jsx
Labels: PR / R+

#4486 Fix Bug 1496721 - Flip the pref to turn simplified onboarding on
  lib/ActivityStream.jsm
Labels: PR / Needs review

#4491 Bug 1493032 - Intermittent browser/components/newtab/test/browser/browser_topsites_contextMenu_options.js | Uncaught exception - TypeError: contextMenu is null; can't access its "querySelector" property
  test/browser/browser_topsites_contextMenu_options.js
Labels: PR / R+

#4492 Bug 1492556 - Intermittent browser/components/newtab/test/browser/browser_topsites_section.js | Uncaught exception - No context menu found - timed out after 50 tries.
  test/browser/browser_topsites_section.js
Labels: PR / R+

#4490 Fix Bug 1485633 - Context menu is displayed wrong for the last Highlight from a row
  content-src/components/Sections/_Sections.scss
Labels: PR / Needs review

#4493 Fix Bug 1484249 - Remove horizontal scrollbar in modal
  content-src/components/TopSites/_TopSites.scss
Labels: PR / Needs review

#4447 Fix Bug 1497616 - feat(experiments): Pocket Personalization V2
  docs/v2-system-addon/data_events.md
  lib/ActivityStream.jsm
  lib/PersonalityProvider.jsm
  lib/RecipeExecutor.jsm
  lib/TopStoriesFeed.jsm
  test/unit/lib/PersonalityProvider.test.js
  test/unit/lib/RecipeExecutor.test.js
  test/unit/lib/TopStoriesFeed.test.js
  test/unit/unit-entry.js
Labels: PR / R+

#4482 Add CFR addon install test
  test/browser/browser_asrouter_cfr.js
Labels: PR / R+ with nits

#4479 Fix Bug 1494101 - Telemetry for custom url category
  docs/v2-system-addon/data_events.md
  lib/SiteClassifier.jsm
  lib/TelemetryFeed.jsm
  test/unit/lib/SiteClassifier.test.js
  test/unit/lib/TelemetryFeed.test.js
  test/unit/unit-entry.js
Labels: PR / Awaiting data review

#4496 Fix Bug 1499068 - Adjust modal button to have variable width
  content-src/asrouter/components/ModalOverlay/_ModalOverlay.scss
Labels: PR / R+

#4497 Fix Bug 1499078 - Add RTL margins to onboarding modal
  content-src/asrouter/templates/OnboardingMessage/_OnboardingMessage.scss
Labels: PR / R+

#4500 Port Bug 1497960: Make ProfileAge return the same instances for the same profile directory and preload times.json to avoid data races. r=janerik
  lib/ASRouterTargeting.jsm
  lib/ManualMigration.jsm
  lib/SnippetsFeed.jsm
  test/browser/browser_asrouter_targeting.js
  test/unit/lib/ManualMigration.test.js
  test/unit/lib/SnippetsFeed.test.js
Labels: PR / R+

#4499 Fix Bug 1483027 - Add title to three doted menu in home
  content-src/components/Card/Card.jsx
  content-src/components/CollapsibleSection/CollapsibleSection.jsx
  content-src/components/TopSites/TopSite.jsx
  locales/en-US/strings.properties
  test/unit/content-src/components/Card.test.jsx
  test/unit/content-src/components/TopSites.test.jsx
Labels: PR / Needs work

#4503 Fix Bug 1499358 - Add button_url field to schema as fallback for OPEN_URL
  content-src/asrouter/templates/SimpleSnippet/SimpleSnippet.jsx
  content-src/asrouter/templates/SimpleSnippet/SimpleSnippet.schema.json
  lib/SnippetsTestMessageProvider.jsm
  test/unit/asrouter/templates/SimpleSnippet.test.jsx
Labels: PR / R+

#4504 Fix Bug 1496785 - change snippet links to bold weight in Dark theme
  content-src/asrouter/components/SnippetBase/_SnippetBase.scss
Labels: PR / R+

#4502 Bug 1492088 - Add ASR Send to device template
  content-src/asrouter/asrouter-content.jsx
  content-src/asrouter/components/Button/_Button.scss
  content-src/asrouter/components/RichText/RichText.jsx
  content-src/asrouter/rich-text-strings.js
  content-src/asrouter/templates/SendToDeviceSnippet/SendToDeviceSnippet.jsx
  content-src/asrouter/templates/SendToDeviceSnippet/isEmailOrPhoneNumber.js
  content-src/asrouter/templates/SubmitFormSnippet/SubmitFormSnippet.jsx
  content-src/asrouter/templates/SubmitFormSnippet/SubmitFormSnippet.schema.json
  content-src/asrouter/templates/SubmitFormSnippet/_SubmitFormSnippet.scss
  lib/SnippetsTestMessageProvider.jsm
  test/unit/asrouter/SnippetsTestMessageProvider.test.js
  test/unit/asrouter/templates/SendToDeviceSnippet.test.jsx
  test/unit/asrouter/templates/SubmitFormSnippet.test.jsx
  test/unit/asrouter/templates/isEmailOrPhoneNumber.test.js
Labels: PR / R+ with nits

#4505 Bug 1499823 - Change object-curly-newline to consistent instead of minProperties in eslint
  .eslintrc.js
  lib/ASRouterPreferences.jsm
Labels: PR / R+ with nits

#4507 Fix Bug 1499071 - Make onboarding just a bit longer for l10n
  content-src/asrouter/components/ModalOverlay/_ModalOverlay.scss
  content-src/asrouter/templates/OnboardingMessage/_OnboardingMessage.scss
Labels: PR / R+

#4489 Fix Bug 1492853 - Add isUpdated targeting parameter
  content-src/asrouter/docs/targeting-attributes.md
  lib/ASRouterTargeting.jsm
  test/browser/browser_asrouter_targeting.js
  test/unit/unit-entry.js
Labels: PR / R+

#4508 Add enable/disable/reset devtools for ASRouter
  content-src/components/ASRouterAdmin/ASRouterAdmin.jsx
  content-src/components/Base/Base.jsx
  lib/ASRouter.jsm
  lib/ASRouterPreferences.jsm
  test/unit/asrouter/ASRouter.test.js
  test/unit/asrouter/ASRouterPreferences.test.js
  test/unit/unit-entry.js
Labels: PR / R+

#4510 Fix Bug 1500431 - Add missing required fields to PAGE_TAKEOVER_DATA ping
  lib/TelemetryFeed.jsm
  test/schemas/pings.js
  test/unit/lib/TelemetryFeed.test.js
Labels: PR / Needs review

#4511 Bug 1483055 - Add targeting for pinned sites
  content-src/asrouter/docs/targeting-attributes.md
  lib/ASRouterTargeting.jsm
  test/browser/browser_asrouter_targeting.js
Labels: PR / R+ with nits

#4512 Compat eoy
  content-src/asrouter/components/SnippetBase/SnippetBase.jsx
  content-src/asrouter/components/SnippetBase/_SnippetBase.scss
  content-src/asrouter/templates/EOYSnippet/EOYSnippet.jsx
  content-src/asrouter/templates/FXASignupSnippet/FXASignupSnippet.jsx
  content-src/asrouter/templates/template-manifest.jsx
  lib/SnippetsTestMessageProvider.jsm
  test/unit/asrouter/compatibility-reference/fx57-compat.test.js
  test/unit/asrouter/compatibility-reference/snippets-fx57.js
  test/unit/asrouter/templates/EOYSnippet.test.jsx
Labels: PR / R+ with nits

#4518 Fix Bug 1497967 - Add Opt-out flow for users to stop seeing CFR recommendations
  common/Actions.jsm
  lib/ASRouter.jsm
  lib/CFRMessageProvider.jsm
  lib/CFRPageActions.jsm
  test/browser/browser_asrouter_cfr.js
  test/unit/asrouter/ASRouter.test.js
  test/unit/asrouter/CFRPageActions.test.js
  test/unit/asrouter/constants.js
Labels: PR / R+

#4516 (nobug) Add more support for setting user preferences in ASR devtools
  content-src/components/ASRouterAdmin/ASRouterAdmin.jsx
  content-src/components/ASRouterAdmin/ASRouterAdmin.scss
  lib/ASRouter.jsm
  lib/ASRouterPreferences.jsm
  test/unit/asrouter/ASRouter.test.js
  test/unit/asrouter/ASRouterPreferences.test.js
Labels: PR / R+

#4521 about:library build changes
  .eslintignore
  .gitignore
  aboutlibrary/content/aboutlibrary.xhtml
  aboutlibrary/jar.mn
  aboutlibrary/moz.build
  content-src/aboutlibrary/aboutlibrary.jsx
  content-src/aboutlibrary/aboutlibrary.scss
  package.json
  webpack.aboutlibrary.config.js
  yamscripts.yml
Labels: Needs discussion

#4527 chore(nobug): Do not build about:library in buildmc
  .mcignore
Labels: PR / R+

#4525 Fix Bug 1501656 - Prevent onLocationChange from being called twice be…
  lib/ASRouterTriggerListeners.jsm
  test/unit/unit-entry.js
Labels: PR / R+

#4528 Port Bug 1493844 - Part 2 - Remove the "caption" and "groupbox" bindings. r=bgrins,dao,jaws,johannh,surkov
  lib/AboutPreferences.jsm
Labels: PR / R+

#4519 Targeting devtools
  content-src/components/ASRouterAdmin/ASRouterAdmin.jsx
  content-src/components/ASRouterAdmin/ASRouterAdmin.scss
  lib/ASRouter.jsm
  test/unit/asrouter/ASRouter.test.js
Labels: PR / R+

#4532 Fix Bug 1502266 - Verify that Update Checker is available before crea…
  lib/ASRouterTargeting.jsm
Labels: PR / R+

#4533 Fix Bug 1502430 - Add mochitest of onLocationChange trigger in the sa…
  test/browser/browser_asrouter_cfr.js
Labels: PR / R+

#4537 Fix Bug 1497683 - remove small breakpoint with 3 top sites across
  content-src/components/Base/_Base.scss
  content-src/components/Search/_Search.scss
  content-src/components/TopSites/_TopSites.scss
  content-src/styles/_variables.scss
Labels: PR / R+

#4538 Backport Bug 1503288 - Use 'args' in button_action params to fix busted simplified onboarding actions
  content-src/asrouter/templates/OnboardingMessage/OnboardingMessage.schema.json
  lib/OnboardingMessageProvider.jsm
  test/unit/asrouter/templates/OnboardingMessage.test.jsx
Labels: PR / Needs work
