Repository mozilla/activity-stream, pull requests merged in 2018-11, with the labels that each got.

#4544 Backport Bug 1472212 - Update URLs to include the noscripts version in xpcshell and browser tests for newtab. r=Mardak
  aboutNewTabService.js
  test/browser/browser_packaged_as_locales.js
  test/xpcshell/test_AboutNewTabService.js
Labels: PR / R+

#4542 (nobug): Report JEXL syntax errors in ASRouter Admin
  content-src/components/ASRouterAdmin/ASRouterAdmin.jsx
  lib/ASRouter.jsm
Labels: PR / R+ with nits

#4543 Bug 1503897 - Upgrade merge sub-dependency to 1.2.1
  package-lock.json
Labels: PR / R+

#4546 Fix Bug 1503688 - Remove the Amazon Assistant CFR metadata
  data/content/assets/cfr_amazon_assistant.png
  docs/v2-system-addon/data_events.md
  lib/CFRMessageProvider.jsm
  test/unit/asrouter/CFRMessageProvider.test.js
Labels: PR / R+

#4535 Fix Bug 1499901 - Add builduplift task that does not export strings
  package.json
  yamscripts.yml
Labels: PR / R+

#4547 Fixes bug 1504165 - Two Sponsored cards are wrongly displayed after i…
  common/Reducers.jsm
  test/unit/common/Reducers.test.js
Labels: PR / R+

#4541 Fix Bug 1503685 - Add "extension controlled" info to PAGE_TAKEOVER_DATA telemetry ping
  docs/v2-system-addon/data_events.md
  lib/TelemetryFeed.jsm
  test/schemas/pings.js
  test/unit/lib/TelemetryFeed.test.js
Labels: PR / Awaiting data review

#4545 Fix Bug 1501304 - Add telemetry for CFR opt-out controls
  docs/v2-system-addon/data_events.md
  lib/CFRPageActions.jsm
  test/unit/asrouter/CFRPageActions.test.js
Labels: PR / Awaiting data review, PR / R+

#4526 Fix Bug 1501817 - Create FxA onboarding card
  content-src/asrouter/docs/targeting-attributes.md
  content-src/asrouter/templates/OnboardingMessage/_OnboardingMessage.scss
  data/content/assets/illustration-sync@2x.png
  lib/ASRouterTargeting.jsm
  lib/OnboardingMessageProvider.jsm
  test/browser/browser_asrouter_targeting.js
  test/unit/asrouter/templates/OnboardingMessage.test.jsx
  test/xpcshell/test_ASRouterTargeting_attribution.js
  test/xpcshell/xpcshell.ini
Labels: PR / R+ with nits

#4539 Bug 1497507 - aligning cta w. value proposition
  content-src/components/MoreRecommendations/_MoreRecommendations.scss
  content-src/components/PocketLoggedInCta/_PocketLoggedInCta.scss
  content-src/components/Sections/_Sections.scss
Labels: PR / Needs work

#4551 Fix Bug 1504754 - Debug noscripts version of new tab page need to be packaged
  content-src/components/TopSites/TopSite.jsx
  jar.mn
  test/unit/content-src/components/TopSites.test.jsx
Labels: PR / R+

#4555 Bug 1505890 - Pinned sites targeting should handle null entries
  lib/ASRouterTargeting.jsm
  test/browser/browser_asrouter_targeting.js
Labels: PR / R+

#4556 chore(l10n): Update from l10n-central Thu Nov 08 2018 16:22:28 GMT-0500 (EST)
  locales-src/bn-IN/strings.properties
  locales-src/cak/strings.properties
  locales-src/es-CL/strings.properties
  locales-src/et/strings.properties
  locales-src/fa/strings.properties
  locales-src/hr/strings.properties
  locales-src/ia/strings.properties
  locales-src/kn/strings.properties
  locales-src/lv/strings.properties
  locales-src/pa-IN/strings.properties
  locales-src/pt-PT/strings.properties
Labels: PR / R+

#4559 Bug 1506225 - Support blocking by campaign
  content-src/components/ASRouterAdmin/ASRouterAdmin.jsx
  lib/ASRouter.jsm
  lib/SnippetsTestMessageProvider.jsm
  test/unit/asrouter/ASRouter.test.js
Labels: PR / Needs review

#4564 Fix Bug 1506592 - Broken image icon for empty sections
  content-src/components/Sections/Sections.jsx
Labels: PR / R+

#4563 Fix Bug 1506594 - Open snippet links in same window
  content-src/asrouter/components/RichText/RichText.jsx
  content-src/asrouter/templates/SubmitFormSnippet/SubmitFormSnippet.jsx
  lib/ASRouter.jsm
  lib/OnboardingMessageProvider.jsm
  test/unit/asrouter/ASRouter.test.js
  test/unit/asrouter/RichText.test.jsx
Labels: PR / R+

#4558 Fix Bug 1502501 - Conditionally show "Return to AMO" instead of StartupOverlay for FxA sign-in on about:welcome
  content-src/activity-stream.jsx
  content-src/asrouter/asrouter-content.jsx
  content-src/asrouter/templates/StartupOverlay/StartupOverlay.jsx
  content-src/asrouter/templates/StartupOverlay/_StartupOverlay.scss
  content-src/components/Base/Base.jsx
  content-src/lib/asroutercontent.js
  content-src/styles/_activity-stream.scss
  lib/OnboardingMessageProvider.jsm
  test/unit/activity-stream.test.jsx
  test/unit/asrouter/templates/OnboardingMessage.test.jsx
  test/unit/content-src/components/Base.test.jsx
  test/unit/content-src/components/StartupOverlay.test.jsx
Labels: PR / R+

#4523 Fixes bug 1507973 - v2 with attachments for personality provider in activity stream.
  lib/PersonalityProvider.jsm
  test/unit/lib/FilterAdult.test.js
  test/unit/lib/PersistentCache.test.js
  test/unit/lib/PersonalityProvider.test.js
  test/unit/lib/TopStoriesFeed.test.js
  test/unit/unit-entry.js
Labels: PR / Needs review

#4565 Fix Bug 1506838 - Update Send To Device snippet to better match old template
  content-src/asrouter/components/Button/_Button.scss
  content-src/asrouter/components/SnippetBase/_SnippetBase.scss
  content-src/asrouter/rich-text-strings.js
  content-src/asrouter/templates/EOYSnippet/_EOYSnippet.scss
  content-src/asrouter/templates/FXASignupSnippet/FXASignupSnippet.jsx
  content-src/asrouter/templates/SendToDeviceSnippet/SendToDeviceSnippet.jsx
  content-src/asrouter/templates/SubmitFormSnippet/SubmitFormSnippet.jsx
  content-src/asrouter/templates/SubmitFormSnippet/_SubmitFormSnippet.scss
  content-src/styles/_variables.scss
  test/unit/asrouter/templates/FXASignupSnippet.test.jsx
  test/unit/asrouter/templates/SendToDeviceSnippet.test.jsx
Labels: PR / R+

#4557 Release uplift: Bug 1504165 - Two Sponsored cards are wrongly displayed after i…
  common/Reducers.jsm
  test/unit/common/Reducers.test.js
Labels: PR / On hold for now

#4566 no bug - Fixing some 1px missing breakpoint rages.
  content-src/components/TopSites/_TopSites.scss
Labels: PR / R+

#4567 bug 1507599 - top stories more Recommendations link showing up for Ge…
  content-src/components/Sections/Sections.jsx
Labels: PR / R+

#4550 (nobug): Add unit tests for ASRouterAdmin
  test/unit/content-src/components/ASRouterAdmin.test.jsx
Labels: PR / R+

#4573 (nobug) package-lock update to https link
  package-lock.json
Labels: PR / Needs review

#4574 (nobug): Fix ASR Snippets preview by positioning on top of legacy snippets
  content-src/asrouter/components/SnippetBase/_SnippetBase.scss
Labels: PR / R+

#4570 Fix Bug 1500563 - Update ASR schemas to reflect defaults, have 1 schema per template
  content-src/asrouter/components/Button/Button.jsx
  content-src/asrouter/components/Button/_Button.scss
  content-src/asrouter/components/SnippetBase/SnippetBase.jsx
  content-src/asrouter/components/SnippetBase/_SnippetBase.scss
  content-src/asrouter/rich-text-strings.js
  content-src/asrouter/templates/EOYSnippet/EOYSnippet.jsx
  content-src/asrouter/templates/EOYSnippet/EOYSnippet.schema.json
  content-src/asrouter/templates/EOYSnippet/_EOYSnippet.scss
  content-src/asrouter/templates/FXASignupSnippet/FXASignupSnippet.jsx
  content-src/asrouter/templates/FXASignupSnippet/FXASignupSnippet.schema.json
  content-src/asrouter/templates/NewsletterSnippet/NewsletterSnippet.jsx
  content-src/asrouter/templates/NewsletterSnippet/NewsletterSnippet.schema.json
  content-src/asrouter/templates/SendToDeviceSnippet/SendToDeviceSnippet.jsx
  content-src/asrouter/templates/SendToDeviceSnippet/SendToDeviceSnippet.schema.json
  content-src/asrouter/templates/SimpleSnippet/SimpleSnippet.jsx
  content-src/asrouter/templates/SimpleSnippet/SimpleSnippet.schema.json
  content-src/asrouter/templates/SimpleSnippet/_SimpleSnippet.scss
  content-src/asrouter/templates/SubmitFormSnippet/SubmitFormSnippet.jsx
  content-src/asrouter/templates/SubmitFormSnippet/_SubmitFormSnippet.scss
  content-src/styles/_variables.scss
  lib/SnippetsTestMessageProvider.jsm
  test/unit/asrouter/templates/FXASignupSnippet.test.jsx
  test/unit/asrouter/templates/NewsletterSnippet.test.jsx
  test/unit/asrouter/templates/SendToDeviceSnippet.test.jsx
  test/unit/asrouter/templates/SimpleSnippet.test.jsx
  test/unit/asrouter/templates/SubmitFormSnippet.test.jsx
Labels: PR / R+

#4575 Bug 1502384 - Link to debugging guide for ASR Devtools
  content-src/asrouter/README.md
  content-src/asrouter/docs/debugging-docs.md
  content-src/asrouter/docs/debugging-guide.png
  content-src/asrouter/docs/telemetry-screenshot.png
  content-src/components/ASRouterAdmin/ASRouterAdmin.jsx
  content-src/components/ASRouterAdmin/ASRouterAdmin.scss
Labels: PR / Needs review

#4576 Bug 1509942 - Upgrade npm-run-all
  package-lock.json
  package.json
Labels: PR / Needs review

#4562 Fix Bug 1506229 - Run check for duplicate files in TC
  mochitest.sh
Labels: PR / Needs work

#4572 Fix Bug 1508667 - update eslint and plugins to latest versions
  .eslintrc.js
  content-src/components/ASRouterAdmin/ASRouterAdmin.jsx
  package-lock.json
  package.json
Labels: PR / Needs review

#4579 Fix Bug 1509810 - Add missing defaults for snippet templates
  content-src/asrouter/components/SnippetBase/_SnippetBase.scss
  content-src/asrouter/templates/EOYSnippet/EOYSnippet.jsx
  content-src/asrouter/templates/EOYSnippet/_EOYSnippet.scss
  content-src/asrouter/templates/FXASignupSnippet/FXASignupSnippet.jsx
  content-src/asrouter/templates/FXASignupSnippet/FXASignupSnippet.schema.json
  content-src/asrouter/templates/NewsletterSnippet/NewsletterSnippet.jsx
  content-src/asrouter/templates/SendToDeviceSnippet/SendToDeviceSnippet.schema.json
  lib/SnippetsTestMessageProvider.jsm
  test/unit/asrouter/templates/EOYSnippet.test.jsx
  test/unit/asrouter/templates/FXASignupSnippet.test.jsx
  test/unit/asrouter/templates/NewsletterSnippet.test.jsx
  test/unit/asrouter/templates/SendToDeviceSnippet.test.jsx
Labels: PR / R+ with nits

#4560 Fix Bug 1504754 - Debug noscripts version of new tab page fail to load
  aboutNewTabService.js
  bin/render-activity-stream-html.js
  test/xpcshell/test_AboutNewTabService.js
Labels: PR / R+

#4578 Fix Bug 1475354 - Create first-run template and content for Return To AMO experience
  content-src/activity-stream.jsx
  content-src/asrouter/asrouter-content.jsx
  content-src/asrouter/rich-text-strings.js
  content-src/asrouter/templates/OnboardingMessage/OnboardingMessage.jsx
  content-src/asrouter/templates/OnboardingMessage/OnboardingMessage.schema.json
  content-src/asrouter/templates/ReturnToAMO/ReturnToAMO.jsx
  content-src/asrouter/templates/ReturnToAMO/_ReturnToAMO.scss
  content-src/asrouter/templates/StartupOverlay/StartupOverlay.jsx
  content-src/asrouter/templates/StartupOverlay/_StartupOverlay.scss
  content-src/components/ASRouterAdmin/ASRouterAdmin.jsx
  content-src/components/Base/Base.jsx
  content-src/styles/_activity-stream.scss
  content-src/styles/_variables.scss
  data/content/assets/gift-extension.svg
  lib/ASRouter.jsm
  lib/OnboardingMessageProvider.jsm
  test/unit/asrouter/ASRouter.test.js
  test/unit/asrouter/asrouter-content.test.jsx
  test/unit/asrouter/templates/OnboardingMessage.test.jsx
  test/unit/unit-entry.js
Labels: PR / R+

#4582 Bug 1510678 - Change recommended addons for Firefox 64 CFR release
  lib/CFRMessageProvider.jsm
  test/unit/asrouter/CFRMessageProvider.test.js
Labels: PR / R+

#4577 Fix Bug 1508431 - Update new tab breakpoints for better content layouts
  content-src/components/CollapsibleSection/CollapsibleSection.jsx
  content-src/components/CollapsibleSection/_CollapsibleSection.scss
  content-src/components/PocketLoggedInCta/_PocketLoggedInCta.scss
  content-src/components/Sections/Sections.jsx
  content-src/components/Sections/_Sections.scss
  content-src/styles/_variables.scss
Labels: PR / R+
