Repository mozilla/activity-stream, pull requests merged in 2018-04, with the labels that each got.

#4074 Fix #1447752 - set search input background to $white
  system-addon/content-src/components/Search/_Search.scss
Labels: PR / Needs review

#4061 Fix Bug 1448911 - Fail early for file protocol customScreenshotUrl
  system-addon/content-src/components/TopSites/TopSiteForm.jsx
  system-addon/test/unit/content-src/components/TopSites.test.jsx
Labels: PR / Needs review

#4077 Fix Bug 1451001 - add black fill and hairline for cards in dark theme
  system-addon/content-src/components/Card/_Card.scss
  system-addon/content-src/styles/_theme.scss
Labels: PR / Needs review

#4081 Fix Bug 1451419 - set background of Top Site icons to $white
  system-addon/content-src/components/TopSites/_TopSites.scss
Labels: PR / R+

#4082 Fix Bug 1451089 - make context menu styles consistent with doorhangers
  system-addon/content-src/components/ContextMenu/_ContextMenu.scss
  system-addon/content-src/styles/_theme.scss
Labels: PR / R+

#4083 Fix Bug 1451474 - color updates for search drop down
  system-addon/content-src/components/Search/_Search.scss
  system-addon/content-src/styles/_theme.scss
Labels: PR / R+ with nits

#4085 Fix Bug 1451091 - Chronologically order highlights
  system-addon/lib/HighlightsFeed.jsm
  system-addon/test/unit/lib/HighlightsFeed.test.js
Labels: PR / R+

#4080 Fix #1451778 - Set <body/> bg color. Move --theme-vars up to body.
  system-addon/content-src/components/Base/Base.jsx
  system-addon/content-src/components/Base/_Base.scss
  system-addon/content-src/styles/_activity-stream.scss
  system-addon/content-src/styles/_theme.scss
  system-addon/test/unit/content-src/components/Base.test.jsx
Labels: PR / R+ with nits

#4084 Fix Bug 1445769 - Top Sites runs `refresh` at startup even when disabled
  system-addon/bootstrap.js
  system-addon/common/PrerenderData.jsm
  system-addon/content-src/components/Sections/Sections.jsx
  system-addon/content-src/components/TopSites/TopSites.jsx
  system-addon/lib/AboutPreferences.jsm
  system-addon/lib/ActivityStream.jsm
  system-addon/lib/HighlightsFeed.jsm
  system-addon/lib/SectionsManager.jsm
  system-addon/lib/TelemetryFeed.jsm
  system-addon/lib/TopSitesFeed.jsm
  system-addon/test/functional/mochitest/browser_as_render.js
  system-addon/test/unit/content-src/components/Sections.test.jsx
  system-addon/test/unit/lib/HighlightsFeed.test.js
  system-addon/test/unit/lib/SectionsManager.test.js
Labels: PR / R+

#4089 Use moz-osx-font-smoothing: grayscale for dark theme
  system-addon/content-src/styles/_theme.scss
Labels: PR / R+

#4088 Bug 1453761 - Make font size of option descriptions larger
  system-addon/lib/AboutPreferences.jsm
Labels: PR / R+

#4087 Fix Bug 1453479 - more dark theme updates
  system-addon/content-src/components/Base/_Base.scss
  system-addon/content-src/components/Card/_Card.scss
  system-addon/content-src/components/CollapsibleSection/_CollapsibleSection.scss
  system-addon/content-src/components/ContextMenu/_ContextMenu.scss
  system-addon/content-src/components/Search/_Search.scss
  system-addon/content-src/components/TopSites/_TopSites.scss
  system-addon/content-src/components/Topics/_Topics.scss
  system-addon/content-src/styles/_activity-stream.scss
  system-addon/content-src/styles/_theme.scss
  system-addon/content-src/styles/_variables.scss
  system-addon/content-src/styles/activity-stream-linux.scss
  system-addon/content-src/styles/activity-stream-mac.scss
  system-addon/content-src/styles/activity-stream-windows.scss
Labels: PR / R+ with nits

#4091 chore(styles): Refactor textbox shadow from color rule
  system-addon/content-src/styles/_theme.scss
Labels: PR / Needs review

#4092 fix(styles): Only use osx property for mac css
  system-addon/content-src/styles/_theme.scss
  system-addon/content-src/styles/activity-stream-mac.scss
Labels: PR / Needs review

#4036 Fix Bug 1410828 - Add a test to verify that the next top site in queue replaces a dismissed top site
  system-addon/test/functional/mochitest/browser_topsites_contextMenu_options.js
Labels: PR / R+

#4095 Fix Bug 1454501 - apply dark theme only to builtin Dark theme
  system-addon/lib/ThemeFeed.jsm
  system-addon/test/unit/lib/ThemeFeed.test.js
Labels: PR / Needs review

#4099 Fix Bug 1454501 - followup to ee47675 to handle default theme being undefined
  system-addon/lib/ThemeFeed.jsm
  system-addon/test/unit/lib/ThemeFeed.test.js
Labels: PR / R+ with nits

#4098 chore (styles): modal overlay color refactor
  system-addon/content-src/components/ConfirmDialog/_ConfirmDialog.scss
  system-addon/content-src/styles/_theme.scss
  system-addon/content-src/styles/_variables.scss
Labels: PR / R+

#4100 Fix Bug 1454743 - fix section fetching in spocs experiment
  system-addon/lib/TopStoriesFeed.jsm
  system-addon/test/unit/lib/TopStoriesFeed.test.js
Labels: PR / Needs review

#4101 Fix Bug 1454743 - fix section fetching in spocs experiment
  system-addon/lib/TopStoriesFeed.jsm
  system-addon/test/unit/lib/TopStoriesFeed.test.js
Labels: PR / R+

#4093 Fix Bug 1454263 - fix search drop down dividers and hover colors
  system-addon/content-src/components/Search/_Search.scss
  system-addon/content-src/styles/_theme.scss
  system-addon/content-src/styles/_variables.scss
Labels: PR / R+ with nits

#4094 Fix Bug 1454423 - update secondary text color to pass contrast test
  system-addon/content-src/components/Card/_Card.scss
  system-addon/content-src/styles/_theme.scss
Labels: PR / R+

#4102 feat(stories): Turn on sponsored content with new feed variant
  system-addon/lib/ActivityStream.jsm
Labels: PR / Needs review

#4086 Fix Bug 1450875 - Wait for Sections to be added before broadcasting content
  system-addon/lib/HighlightsFeed.jsm
  system-addon/test/unit/lib/HighlightsFeed.test.js
Labels: PR / R+ with nits

#4103 Fix Bug 1454730 - change Top Site icon background to grey-70 on dark theme
  system-addon/content-src/components/TopSites/_TopSites.scss
  system-addon/content-src/styles/_theme.scss
Labels: PR / R+

#4104 chore(highlights): Update fetchHighlights comment to explain more
  system-addon/lib/HighlightsFeed.jsm
Labels: PR / R+

#4105 Followup Bug 1454807 - Enable for US region only (for en-* locales)
  system-addon/lib/ActivityStream.jsm
Labels: PR / Needs review

#4107 Fix Bug 1454985 - use ::after for search provider dividers
  system-addon/content-src/components/Search/_Search.scss
Labels: PR / Needs review

#4106 Fix Bug 1455081 - update icon and text tertiary colors in dark theme
  system-addon/content-src/styles/_theme.scss
Labels: PR / Needs review

#4076 Fix Bug 1433230 - Add recent downloads to Highlights
  locales/en-US/strings.properties
  system-addon/common/Actions.jsm
  system-addon/content-src/components/Card/Card.jsx
  system-addon/content-src/components/Card/_Card.scss
  system-addon/content-src/components/Card/types.js
  system-addon/content-src/components/LinkMenu/LinkMenu.jsx
  system-addon/content-src/lib/link-menu-options.js
  system-addon/content-src/styles/_icons.scss
  system-addon/content-src/styles/_variables.scss
  system-addon/data/content/assets/glyph-download-icon.svg
  system-addon/data/content/assets/glyph-open-file-16.svg
  system-addon/lib/ActivityStream.jsm
  system-addon/lib/DownloadsManager.jsm
  system-addon/lib/HighlightsFeed.jsm
  system-addon/lib/PrefsFeed.jsm
  system-addon/lib/SectionsManager.jsm
  system-addon/test/unit/content-src/components/Card.test.jsx
  system-addon/test/unit/content-src/components/LinkMenu.test.jsx
  system-addon/test/unit/content-src/components/Sections.test.jsx
  system-addon/test/unit/lib/DownloadsManager.test.js
  system-addon/test/unit/lib/HighlightsFeed.test.js
  system-addon/test/unit/unit-entry.js
Labels: PR / R+ with nits

#4111 Fix Bug 1432595 - Add section in prefs to turn off parts of Highlights
  locales/en-US/strings.properties
  system-addon/lib/ActivityStream.jsm
  system-addon/lib/HighlightsFeed.jsm
  system-addon/lib/SectionsManager.jsm
  system-addon/test/unit/lib/HighlightsFeed.test.js
Labels: PR / R+

#4114 Followup Bug 1432595 - Add section in prefs to turn off parts of Highlights
  locales/en-US/strings.properties
Labels: PR / R+

#4110 Add telemetry pings (part 1 - UI instrumentation)
  system-addon/common/Actions.jsm
  system-addon/content-src/message-center/components/Button.jsx
  system-addon/content-src/message-center/components/SnippetBase.jsx
  system-addon/content-src/message-center/message-center-content.jsx
  system-addon/content-src/message-center/templates/SimpleSnippet.jsx
  system-addon/lib/MessageCenterRouter.jsm
  system-addon/lib/TelemetryFeed.jsm
  system-addon/test/unit/common/Actions.test.js
  system-addon/test/unit/lib/TelemetryFeed.test.js
  system-addon/test/unit/message-center/MessageCenterRouter.test.js
Labels: PR / R+

#4115 fix(styles): Switch to border-image instead of ::after for search engine separator
  system-addon/content-src/components/Search/_Search.scss
Labels: PR / Needs review

#4116 AS router Snippet template should respect theme variables
  system-addon/content-src/components/MessageCenterAdmin/MessageCenterAdmin.scss
  system-addon/content-src/message-center/components/Button.jsx
  system-addon/content-src/message-center/components/SnippetBase.jsx
Labels: PR / Needs review

#4117 Fix modal icon width
  system-addon/content-src/styles/_icons.scss
Labels: PR / R+ with nits

#4118 Rename ASRouter
  .sass-lint.yml
  system-addon/content-src/asrouter/asrouter-content.jsx
  system-addon/content-src/asrouter/components/Button/Button.jsx
  system-addon/content-src/asrouter/components/Button/_Button.scss
  system-addon/content-src/asrouter/components/SnippetBase/SnippetBase.jsx
  system-addon/content-src/asrouter/components/SnippetBase/_SnippetBase.scss
  system-addon/content-src/asrouter/message-format.md
  system-addon/content-src/asrouter/templates/SimpleSnippet/SimpleSnippet.jsx
  system-addon/content-src/asrouter/templates/SimpleSnippet/_SimpleSnippet.scss
  system-addon/content-src/components/ASRouterAdmin/ASRouterAdmin.jsx
  system-addon/content-src/components/ASRouterAdmin/ASRouterAdmin.scss
  system-addon/content-src/components/Base/Base.jsx
  system-addon/content-src/components/Search/_Search.scss
  system-addon/content-src/lib/snippets.js
  system-addon/content-src/message-center/components/Button.jsx
  system-addon/content-src/message-center/components/SnippetBase.jsx
  system-addon/content-src/styles/_activity-stream.scss
  system-addon/content-src/styles/_icons.scss
  system-addon/lib/ASRouter.jsm
  system-addon/lib/ASRouterFeed.jsm
  system-addon/lib/ActivityStream.jsm
  system-addon/test/unit/asrouter/ASRouter.test.js
  system-addon/test/unit/asrouter/constants.js
  system-addon/test/unit/content-src/lib/snippets.test.js
  system-addon/test/unit/lib/ActivityStream.test.js
  system-addon/test/unit/message-center/constants.js
Labels: PR / R+

#4075 Fix Bug 1433215 - Add blockList persistance to Message Center
  system-addon/content-src/components/ASRouterAdmin/ASRouterAdmin.jsx
  system-addon/lib/ASRouter.jsm
  system-addon/lib/ASRouterFeed.jsm
  system-addon/test/unit/asrouter/ASRouter.test.js
Labels: PR / R+

#4119 Fix Bug 1447891 - Top Sites keep changing dramatically
  system-addon/content-src/components/TopSites/TopSite.jsx
  system-addon/content-src/lib/link-menu-options.js
  system-addon/lib/PlacesFeed.jsm
  system-addon/lib/TopSitesFeed.jsm
  system-addon/test/unit/content-src/components/LinkMenu.test.jsx
  system-addon/test/unit/content-src/components/TopSites.test.jsx
  system-addon/test/unit/lib/PlacesFeed.test.js
  system-addon/test/unit/lib/TopSitesFeed.test.js
  system-addon/test/unit/unit-entry.js
Labels: PR / R+

#4121 Fix Bug 1456477 - remove border (inset shadow) from top sites icons
  system-addon/content-src/components/TopSites/_TopSites.scss
  system-addon/content-src/styles/_theme.scss
Labels: PR / R+ with nits

#4120 Fix Bug 1449653 - Implement a dark theme for snippets
  system-addon/content-src/asrouter/components/SnippetBase/_SnippetBase.scss
  system-addon/content-src/styles/_theme.scss
  system-addon/content-src/styles/_variables.scss
Labels: PR / R+ with nits

#4122 Fix Bug 1456445 - The 'Go to download page' context menu option does not do anything on Windows and Linux
  system-addon/common/Actions.jsm
  system-addon/content-src/lib/link-menu-options.js
  system-addon/lib/DownloadsManager.jsm
  system-addon/test/unit/content-src/components/LinkMenu.test.jsx
  system-addon/test/unit/lib/DownloadsManager.test.js
  system-addon/test/unit/unit-entry.js
Labels: PR / Needs review

#4126 Fix tests that would never fail
  system-addon/test/unit/content-src/components/Card.test.jsx
  system-addon/test/unit/content-src/components/ConfirmDialog.test.jsx
  system-addon/test/unit/content-src/components/LinkMenu.test.jsx
  system-addon/test/unit/content-src/components/SectionMenu.test.jsx
  system-addon/test/unit/content-src/components/TopSites.test.jsx
Labels: PR / R+

#4124 Fix Bug 1455931 - TopSites refresh should wait for tippytop provider to initialize
  system-addon/lib/TopSitesFeed.jsm
  system-addon/test/unit/lib/TopSitesFeed.test.js
Labels: PR / Needs review

#4123 Fix Bug 1456082 - Storage should not have telemetry be a required argument
  system-addon/lib/ActivityStreamStorage.jsm
  system-addon/test/unit/lib/ActivityStreamStorage.test.js
Labels: PR / R+

#4129 Bug 1457927 - The most recent download is wrongly displayed in the last position
  system-addon/lib/DownloadsManager.jsm
  system-addon/test/unit/lib/HighlightsFeed.test.js
Labels: PR / Needs review
