Repository mozilla/activity-stream, pull requests merged in 2018-09, with the labels that each got.

#4277 Fix Bug 1471636 - Visual indication that we are previewing a snippet
  common/Actions.jsm
  common/Reducers.jsm
  content-src/asrouter/asrouter-content.jsx
  content-src/asrouter/components/SnippetBase/_SnippetBase.scss
  content-src/styles/_variables.scss
  lib/ASRouter.jsm
  lib/ActivityStreamMessageChannel.jsm
  test/unit/asrouter/ASRouter.test.js
  test/unit/asrouter/asrouter-content.test.jsx
  test/unit/asrouter/constants.js
  test/unit/common/Reducers.test.js
  test/unit/lib/ActivityStreamMessageChannel.test.js
Labels: PR / On hold for now

#4402 (nobug) Check for presence of currentNotification before removal
  lib/CFRPageActions.jsm
Labels: PR / R+

#4294 feat(experiments): add text taggers
  lib/NaiveBayesTextTagger.jsm
  lib/NmfTextTagger.jsm
  lib/TfIdfVectorizer.jsm
  test/unit/lib/NaiveBayesTextTagger.test.js
  test/unit/lib/NmfTextTagger.test.js
  test/unit/lib/TfIdfVectorizer.test.js
Labels: PR / R+ with nits

#4400 Fix Bug 1486909 - Remove init/uninit assignments to _currentSearchHostname, delete lazy…
  lib/TopSitesFeed.jsm
  test/unit/lib/TopSitesFeed.test.js
Labels: PR / R+ with nits

#4316 Fix Bug 1481680 - Add mochitests for search shortcuts and fix existing mochitests
  test/browser/browser.ini
  test/browser/browser_topsites_contextMenu_options.js
  test/browser/browser_topsites_section.js
Labels: PR / R+ with nits

#4399 Fix Bug 1486950 - Increase date range to avoid intermittent
  test/browser/browser_asrouter_targeting.js
Labels: PR / R+

#4403 (mochitest): Add mochitest for CFR panel show/hide
  test/browser/browser.ini
  test/browser/browser_asrouter_cfr.js
Labels: PR / R+ with nits

#4406 Fix Bug 1484206 - Add previousSessionEnd to targeting context
  content-src/asrouter/schemas/message-format.md
  lib/ASRouter.jsm
  lib/ASRouterTargeting.jsm
  test/unit/asrouter/ASRouter.test.js
Labels: PR / R+

#4410 Fix Bug 1482534 - fix font smoothing in OSX
  content-src/styles/activity-stream-mac.scss
Labels: PR / R+

#4409 Fix Bug 1482859 - Block snippet messages after CTA was clicked
  content-src/asrouter/asrouter-content.jsx
  content-src/asrouter/templates/SimpleSnippet/SimpleSnippet.jsx
  content-src/asrouter/templates/SimpleSnippet/SimpleSnippet.schema.json
  test/unit/asrouter/asrouter-content.test.jsx
  test/unit/asrouter/templates/SimpleSnippet.test.jsx
Labels: PR / R+

#4412 chore(telemetry): Remove the redundant flag in CFR telemetry
  lib/CFRPageActions.jsm
  test/unit/asrouter/CFRPageActions.test.js
Labels: PR / R+

#4416 Revert "Fix Bug 1482534 - fix font smoothing in OSX (#4410)"
  content-src/styles/activity-stream-mac.scss
Labels: PR / Needs review

#4418 Fix Bug 1484206 - Fix merge of custom context and targetting getters
  lib/ASRouterTargeting.jsm
  test/unit/asrouter/ASRouterTargeting.test.js
Labels: PR / R+ with nits

#4417 Fixes bug 1490734 - Fresh profile can sometimes display no card in th…
  content-src/components/Base/Base.jsx
  content-src/components/Sections/Sections.jsx
  test/unit/content-src/components/Base.test.jsx
  test/unit/content-src/components/Sections.test.jsx
Labels: PR / R+

#4414 Fix Bug 1490508 - Collapse the recommendation when the urlbar is focused
  lib/CFRPageActions.jsm
Labels: PR / Needs review

#4413 Fix Bug 1433243 - Implement ASR persistent caching for remote endpoints
  content-src/components/ASRouterAdmin/ASRouterAdmin.jsx
  lib/ASRouter.jsm
  test/unit/asrouter/ASRouter.test.js
  test/unit/asrouter/MessageLoaderUtils.test.js
Labels: PR / R+

#4401 Fix Bug 1488846 - Pocket cta for logged out users flickers a bit before displaying the logged in version (topics) and shifting
  common/Reducers.jsm
  content-src/components/Base/_Base.scss
  content-src/components/Sections/Sections.jsx
  content-src/components/Sections/_Sections.scss
  test/unit/common/Reducers.test.js
  test/unit/content-src/components/Sections.test.jsx
Labels: PR / R+ with nits

#4421 Fix Bug 1484698 - Rename hasFxAccount to usesFirefoxSync
  content-src/asrouter/schemas/message-format.md
  lib/ASRouterTargeting.jsm
  test/browser/browser_asrouter_targeting.js
Labels: PR / R+

#4411 Fix Bug 1484207 - Add geo and firefox version targeting getters
  content-src/asrouter/schemas/message-format.md
  content-src/asrouter/schemas/provider-response.schema.json
  lib/ASRouter.jsm
  lib/ASRouterTargeting.jsm
  lib/ActivityStream.jsm
  test/browser/browser_asrouter_targeting.js
  test/unit/asrouter/ASRouter.test.js
  test/unit/asrouter/ASRouterTargeting.test.js
  test/unit/unit-entry.js
Labels: PR / R+

#4420 Fix Bug 1490241 - CFR fluent and string overrides should both have attributes
  content-src/asrouter/templates/CFR/templates/ExtensionDoorhanger.schema.json
  lib/CFRPageActions.jsm
  test/browser/browser_asrouter_cfr.js
  test/unit/asrouter/CFRPageActions.test.js
  test/unit/asrouter/templates/ExtensionDoorhanger.test.jsx
Labels: PR / Needs review

#4423 Port Bug 1487246: Enable the eslint no-sequences rule. r=Standard8
  .eslintrc.js
Labels: PR / R+

#4427 Fix Bug 1491841 - Incorrect payload for undesired event FXA_METRICS_ERROR
  content-src/components/StartupOverlay/StartupOverlay.jsx
Labels: PR / Needs review

#4433 (mochitests): Fix CFR mochitest intermittent
  test/browser/browser_asrouter_cfr.js
Labels: PR / Needs review

#4426 Fix Bug 1491944 - Run all_files_referenced on taskcluster
  mochitest.sh
Labels: PR / R+

#4428 Fix Bug 1485626 - Tab_Index reaches elements inside collapsed menus in activity stream
  content-src/components/CollapsibleSection/CollapsibleSection.jsx
Labels: PR / R+

#4431 Fix Bug 1482113 - Don't collect metrics when previewing Snippets
  content-src/asrouter/asrouter-content.jsx
  content-src/asrouter/components/SnippetBase/SnippetBase.jsx
  content-src/asrouter/templates/SimpleSnippet/SimpleSnippet.jsx
  test/unit/asrouter/asrouter-content.test.jsx
  test/unit/asrouter/templates/SimpleSnippet.test.jsx
Labels: PR / R+ with nits

#4435 Port Bug 1486739 - Enable ESLint rule comma-dangle
  .eslintrc.js
  ping-centre/PingCentre.jsm
Labels: PR / Needs review

#4434 Bug 1492174 - Update CFR Message to reflect planned cohorts
  lib/ActivityStream.jsm
  lib/CFRMessageProvider.jsm
Labels: PR / R+

#4437 (nobug): Skip failing CFR mochitest
  test/browser/browser.ini
Labels: PR / R+

#4419 Fix Bug 1489530: include blocked sites in ASRouter top sites targeting
  lib/ASRouterTargeting.jsm
Labels: PR / R+

#4422 Fix Bug 1484996: add weights for ASRouter messages
  lib/ASRouter.jsm
  lib/ASRouterTargeting.jsm
Labels: PR / R+

#4441 Fix Bug 1492454: Normalise ASRouter frequency caps
  lib/ASRouter.jsm
  test/unit/asrouter/ASRouter.test.js
Labels: PR / R+

#4444 Bug 1492174 - Part 2. Add variants for lifetime caps
  lib/CFRMessageProvider.jsm
  test/unit/asrouter/CFRMessageProvider.test.js
Labels: PR / R+

#4442 Backport Bug 1491609 - Updates to radio and checkbox common.css styling
  content-src/components/TopSites/_TopSites.scss
  content-src/styles/_icons.scss
Labels: PR / On hold for now, PR / R+

#4443 Fix Bug 1492777 - Failing CFR mochitest browser_asrouter_cfr.js
  test/browser/browser.ini
  test/browser/browser_asrouter_cfr.js
Labels: PR / R+

#4439 Fixes bug 1493041 - Topstories feed uninit can remove idle-daily obse…
  lib/TopStoriesFeed.jsm
  test/unit/lib/TopStoriesFeed.test.js
Labels: PR / R+

#4446 Backport Bug 1491394 - Update callsites to use new mozILocaleService API. r=jfkthame
  aboutNewTabService.js
  lib/ASRouter.jsm
  lib/ActivityStream.jsm
  lib/TelemetryFeed.jsm
  ping-centre/PingCentre.jsm
  test/browser/browser_packaged_as_locales.js
  test/unit/lib/ActivityStream.test.js
  test/unit/ping-centre/PingCentre.test.js
  test/unit/unit-entry.js
Labels: PR / Needs review

#4432 Bug 1492942 - Snippets should respect onboarding, user pref
  content-src/asrouter/asrouter-content.jsx
  content-src/components/ASRouterAdmin/ASRouterAdmin.jsx
  lib/ASRouter.jsm
  lib/ASRouterPreferences.jsm
  lib/TelemetryFeed.jsm
  test/unit/asrouter/ASRouter.test.js
  test/unit/asrouter/ASRouterPreferences.test.js
  test/unit/lib/TelemetryFeed.test.js
Labels: PR / On hold for now, PR / R+

#4449 Bug 1490697 - Support filtering by locale in ASR/CFR
  content-src/asrouter/schemas/message-format.md
  lib/ASRouterTargeting.jsm
  lib/CFRMessageProvider.jsm
  test/browser/browser_asrouter_targeting.js
Labels: PR / R+

#4451 Fix Bug 1494275 - CFR can wrongly recommend outdated versions of the addons
  content-src/asrouter/templates/CFR/templates/ExtensionDoorhanger.schema.json
  lib/CFRMessageProvider.jsm
  lib/CFRPageActions.jsm
  test/unit/asrouter/CFRPageActions.test.js
  test/unit/asrouter/templates/ExtensionDoorhanger.test.jsx
Labels: PR / R+

#4455 Bug 1494973 - Add clear cache method for ASRouter
  content-src/components/ASRouterAdmin/ASRouterAdmin.jsx
  lib/ASRouter.jsm
  lib/ASRouterTargeting.jsm
  test/browser/browser_asrouter_targeting.js
  test/browser/head.js
  test/unit/asrouter/ASRouter.test.js
  test/unit/asrouter/ASRouterTargeting.test.js
Labels: PR / R+
