Repository mozilla/activity-stream, pull requests merged in 2018-05, with the labels that each got.

#4128 fix(prerender): Check top before loading more scripts
  bin/render-activity-stream-html.js
Labels: PR / R+

#4131 Port Bug 1456035: Part 4 - Convert callers of XPCOMUtils.generateQI to ChromeUtils.generateQI. r=mccr8
  system-addon/lib/PlacesFeed.jsm
  system-addon/test/unit/unit-entry.js
Labels: PR / R+

#4134 Fix Bug 1456554 - remove wide layout experiment
  system-addon/common/PrerenderData.jsm
  system-addon/content-src/components/Base/Base.jsx
  system-addon/content-src/components/Base/_Base.scss
  system-addon/content-src/components/Card/_Card.scss
  system-addon/content-src/components/Sections/_Sections.scss
  system-addon/content-src/components/TopSites/_TopSites.scss
  system-addon/lib/ActivityStream.jsm
Labels: PR / R+

#4132 Fix Bug 1456127 - Handle telemetry pings for AS Router in TelemetryFeed
  system-addon/lib/TelemetryFeed.jsm
  system-addon/test/unit/lib/TelemetryFeed.test.js
Labels: PR / R+

#4138 fix(prerender): Make localized files different to avoid duplicate checks
  bin/render-activity-stream-html.js
Labels: PR / R+

#4137 Fix Bug 1458701 - Enable pocket stories for en-CA
  system-addon/lib/ActivityStream.jsm
Labels: PR / R+

#4136 Fix Bug 1458640 - Prevent any fatal indexedDB errors from crashing section
  system-addon/lib/ASRouter.jsm
  system-addon/lib/ActivityStreamStorage.jsm
  system-addon/test/unit/lib/ActivityStreamStorage.test.js
Labels: PR / R+ with nits

#4135 Fix Bug 1436228 - Green up our JS dependencies for Firefox 61
  package-lock.json
  package.json
Labels: PR / R+

#4140 Fix Bug 1445090-chore(l10n): remove unused strings to ease l10n work
  locales/en-US/strings.properties
Labels: PR / Needs review

#4141 AS Router Impression Stats
  system-addon/content-src/asrouter/asrouter-content.jsx
  system-addon/content-src/asrouter/components/ImpressionsWrapper/ImpressionsWrapper.jsx
  system-addon/content-src/asrouter/components/SnippetBase/SnippetBase.jsx
  system-addon/content-src/asrouter/templates/SimpleSnippet/SimpleSnippet.jsx
  system-addon/lib/ASRouter.jsm
  system-addon/test/unit/asrouter/asrouter-content.test.jsx
Labels: Blocking export, PR / R+

#4145 Fix Bug 1460119 - gSnippetsMap.getTotalBookmarksCount() never resolves
  system-addon/lib/SnippetsFeed.jsm
  system-addon/test/unit/lib/SnippetsFeed.test.js
Labels: PR / R+ with nits

#4144 Bug 1401194 - Add data-section-id to sections for web extension tests
  system-addon/content-src/components/CollapsibleSection/CollapsibleSection.jsx
Labels: PR / Needs review

#4090 Bug 1448918 - Migrate Firefox Desktop's first run experience from a w…
  locales/en-US/strings.properties
  system-addon/common/Actions.jsm
  system-addon/content-src/activity-stream.jsx
  system-addon/content-src/components/Base/Base.jsx
  system-addon/content-src/components/StartupOverlay/StartupOverlay.jsx
  system-addon/content-src/components/StartupOverlay/_StartupOverlay.scss
  system-addon/content-src/lib/snippets.js
  system-addon/content-src/styles/_activity-stream.scss
  system-addon/data/content/assets/fox-tail.png
  system-addon/data/content/assets/sync-devices.svg
  system-addon/test/schemas/pings.js
  system-addon/test/unit/content-src/components/Base.test.jsx
  system-addon/test/unit/content-src/components/StartupOverlay.test.jsx
Labels: PR / R+

#4142 Fix Bug 1459318 - Enable telemetry for AS Router
  docs/v2-system-addon/data_dictionary.md
  docs/v2-system-addon/data_events.md
  system-addon/lib/TelemetryFeed.jsm
  system-addon/test/schemas/pings.js
  system-addon/test/unit/lib/TelemetryFeed.test.js
Labels: PR / Needs review, PR / R+

#4146 Bug 1460377 - Hide Manage Section option for Web Extension sections and show Manage Extension
  locales/en-US/strings.properties
  system-addon/common/Actions.jsm
  system-addon/content-src/components/CollapsibleSection/CollapsibleSection.jsx
  system-addon/content-src/components/SectionMenu/SectionMenu.jsx
  system-addon/content-src/components/Sections/Sections.jsx
  system-addon/content-src/lib/section-menu-options.js
  system-addon/lib/AboutPreferences.jsm
  system-addon/test/unit/content-src/components/SectionMenu.test.jsx
  system-addon/test/unit/lib/AboutPreferences.test.js
Labels: PR / R+ with nits

#4151 Bug 1461787 - Add endpoint pref, button_type to ASRouter experiment
  system-addon/content-src/asrouter/components/Button/Button.jsx
  system-addon/content-src/asrouter/templates/SimpleSnippet/SimpleSnippet.jsx
  system-addon/content-src/asrouter/templates/SimpleSnippet/_SimpleSnippet.scss
  system-addon/lib/ASRouter.jsm
  system-addon/lib/ActivityStream.jsm
Labels: PR / R+ with nits

#4153 Bug 1456158 - Add schema for AS Router Simple Snippet template
  package-lock.json
  package.json
  system-addon/content-src/asrouter/schemas/message-format.md
  system-addon/content-src/asrouter/schemas/provider-response.schema.json
  system-addon/content-src/asrouter/templates/SimpleSnippet/SimpleSnippet.schema.json
  system-addon/test/unit/asrouter/templates/SimpleSnippet.test.jsx
  system-addon/test/unit/unit-entry.js
Labels: PR / R+

#4143 Fix Bug 1432676 - Create AS Router UI surface / template for Onboarding overlay
  system-addon/common/Actions.jsm
  system-addon/content-src/asrouter/asrouter-content.jsx
  system-addon/content-src/asrouter/components/ModalOverlay/ModalOverlay.jsx
  system-addon/content-src/asrouter/components/ModalOverlay/_ModalOverlay.scss
  system-addon/content-src/asrouter/templates/OnboardingMessage/OnboardingMessage.jsx
  system-addon/content-src/asrouter/templates/OnboardingMessage/_OnboardingMessage.scss
  system-addon/content-src/components/ASRouterAdmin/ASRouterAdmin.jsx
  system-addon/content-src/styles/_activity-stream.scss
  system-addon/data/content/assets/illustration-addons@2x.png
  system-addon/data/content/assets/illustration-privatebrowsing@2x.png
  system-addon/data/content/assets/illustration-screenshots@2x.png
  system-addon/lib/ASRouter.jsm
  system-addon/test/unit/asrouter/ASRouter.test.js
  system-addon/test/unit/asrouter/asrouter-content.test.jsx
  system-addon/test/unit/asrouter/constants.js
Labels: PR / R+

#4155 Fix unreferenced onboarding illustrations
  system-addon/content-src/asrouter/templates/OnboardingMessage/OnboardingMessage.jsx
  system-addon/content-src/asrouter/templates/OnboardingMessage/_OnboardingMessage.scss
Labels: PR / R+

#4157 Fix Bug 1462624 - 0.25 - 0.29% installer size (osx-cross, windows2012-32, windows2012-64) regression on push 79ab9d3259944b808a88f0c6783504e269bcff2c (Fri May 18 2018)
  system-addon/data/content/assets/fox-tail.png
  system-addon/data/content/assets/illustration-addons@2x.png
  system-addon/data/content/assets/illustration-privatebrowsing@2x.png
  system-addon/data/content/assets/illustration-screenshots@2x.png
Labels: PR / R+

#4161 Bug 1457227 - convert currentId to lastMessageId
  system-addon/content-src/asrouter/asrouter-content.jsx
  system-addon/content-src/components/ASRouterAdmin/ASRouterAdmin.jsx
  system-addon/lib/ASRouter.jsm
  system-addon/test/unit/asrouter/ASRouter.test.js
Labels: PR / R+ with nits

#4152 Fix Bug 1460782 - Exception in TelemetryFeed uninit
  system-addon/bootstrap.js
  system-addon/lib/TelemetryFeed.jsm
Labels: PR / Needs review

#4159 Fix Bug 1459289 - compact cards for highlights
  system-addon/content-src/components/Card/Card.jsx
  system-addon/content-src/components/Card/_Card.scss
  system-addon/content-src/components/Card/types.js
  system-addon/content-src/components/Sections/Sections.jsx
  system-addon/content-src/components/Sections/_Sections.scss
  system-addon/content-src/styles/_icons.scss
  system-addon/content-src/styles/_variables.scss
  system-addon/data/content/assets/glyph-download-icon.svg
  system-addon/data/content/assets/glyph-historyItem-16.svg
  system-addon/lib/DownloadsManager.jsm
  system-addon/lib/SectionsManager.jsm
  system-addon/test/unit/content-src/components/Sections.test.jsx
Labels: PR / R+ with nits

#4165 chore(lint): Fix sentance/sentence codespell warning
  locales/en-US/strings.properties
Labels: PR / R+

#4167 chore(highlights): Update mochitest to check for 2 rows of placeholders
  system-addon/test/functional/mochitest/browser_highlights_section.js
Labels: PR / Needs review

#4166 Bug 1428274 - AS Router should handle 204, 302, 500 codes approrpiately
  system-addon/lib/ASRouter.jsm
  system-addon/test/unit/asrouter/MessageLoaderUtils.test.js
Labels: PR / R+

#4168 Fix Bug 1457239 - Setting for number of rows is truncated making the label not readable unless you click on it
  system-addon/lib/AboutPreferences.jsm
Labels: PR / R+

#4170 Fix Bug 1464467 - fix type icon in RTL
  system-addon/content-src/components/Card/_Card.scss
Labels: PR / Needs review

#4171 Fix Bug 1464536 - Compact icon type circle can overlap host name
  system-addon/content-src/components/Card/_Card.scss
Labels: PR / Needs review

#4149 Fix Bug 1457582 - Replace strings-export and include .properties as part of buildmc
  bin/strings-export.js
  package.json
  yamscripts.yml
Labels: PR / R+ with nits

#4148 Fix Bug 1457580 - Update strings-import to get strings from l10n-central
  bin/strings-import.js
  package-lock.json
  package.json
  yamscripts.yml
Labels: PR / R+ with nits

#4172 Bug 1464019 - Turn off asrouter snippets when snippets.feed is false
  system-addon/content-src/asrouter/asrouter-content.jsx
  system-addon/content-src/lib/snippets.js
  system-addon/test/unit/content-src/lib/snippets.test.js
Labels: PR / Needs review

#4175 Fix Bug 1463426 - Open 'about:privatebrowsing' on onboarding 'Try Now' action
  system-addon/lib/ASRouter.jsm
  system-addon/test/unit/asrouter/ASRouter.test.js
  system-addon/test/unit/asrouter/constants.js
Labels: PR / Needs review

#4177 Fix Bug 1433217 - Create Onboarding message provider
  system-addon/content-src/asrouter/templates/OnboardingMessage/_OnboardingMessage.scss
  system-addon/data/content/assets/Illustration-gift@2x.png
  system-addon/lib/ASRouter.jsm
  system-addon/lib/OnboardingMessageProvider.jsm
Labels: PR / R+ with nits

#4181 chore(telemetry): Change telemetry for onboarding from 'TRY_NOW' to regular button click
  system-addon/content-src/asrouter/templates/OnboardingMessage/OnboardingMessage.jsx
Labels: PR / Needs review

#4183 chore(fix): Fix casing on illustration
  system-addon/data/content/assets/illustration-gift@2x.png
Labels: PR / Needs review

#4182 Bug 1464019 - Turn off asrouter snippets when snippets.feed is is false
  system-addon/content-src/asrouter/asrouter-content.jsx
  system-addon/content-src/lib/snippets.js
  system-addon/test/unit/content-src/lib/snippets.test.js
Labels: PR / Needs review

#4179 Fix Bug 1400536 - add pref for number of rows in sections
  system-addon/content-src/components/Sections/Sections.jsx
  system-addon/lib/ActivityStream.jsm
  system-addon/lib/HighlightsFeed.jsm
  system-addon/lib/SectionsManager.jsm
  system-addon/test/unit/content-src/components/Sections.test.jsx
  system-addon/test/unit/lib/HighlightsFeed.test.js
Labels: PR / Needs review

#4184 Fix Bug 1465398 - change max rows for top sites to 4
  system-addon/lib/AboutPreferences.jsm
  system-addon/lib/TopSitesFeed.jsm
  system-addon/test/unit/lib/TopSitesFeed.test.js
Labels: PR / Needs review

#4185 Fix Bug 1465178 - Telemetry source in AS Router is null
  system-addon/content-src/asrouter/asrouter-content.jsx
  system-addon/content-src/asrouter/components/ImpressionsWrapper/ImpressionsWrapper.jsx
  system-addon/content-src/asrouter/components/SnippetBase/SnippetBase.jsx
  system-addon/content-src/asrouter/templates/OnboardingMessage/OnboardingMessage.jsx
  system-addon/content-src/asrouter/templates/SimpleSnippet/SimpleSnippet.jsx
  system-addon/test/unit/asrouter/asrouter-content.test.jsx
Labels: PR / R+ with nits

#4187 Fix Bug 1463381 - change color of context text and icon on Pocket cards
  system-addon/content-src/components/Card/_Card.scss
Labels: PR / Needs review

#4189 Fix Bug 1465902 - Do not send a bundle of messages if we do not have enough messages to fill the bundle
  system-addon/lib/ASRouter.jsm
  system-addon/test/unit/asrouter/ASRouter.test.js
Labels: PR / R+

#4150 Bug 1436615 - Lots of memory used for activity stream PNGs encoded as data URIs
  system-addon/content-src/components/Card/Card.jsx
  system-addon/lib/Screenshots.jsm
  system-addon/test/functional/mochitest/browser_getScreenshots.js
  system-addon/test/unit/content-src/components/Card.test.jsx
  system-addon/test/unit/lib/Screenshots.test.js
Labels: PR / R+

#4178 Bug 1433216 - Add AS Router targeting
  karma.mc.config.js
  system-addon/content-src/asrouter/schemas/provider-response.schema.json
  system-addon/lib/ASRouter.jsm
  system-addon/lib/ASRouterTargeting.jsm
  system-addon/test/functional/mochitest/browser.ini
  system-addon/test/functional/mochitest/browser_asrouter_targeting.js
  system-addon/test/unit/unit-entry.js
Labels: PR / R+ with nits

#4186 Fix Bug 1465623 - fix position of type icon border on highlight cards
  system-addon/content-src/components/Card/_Card.scss
Labels: PR / Needs review
