Repository mozilla/activity-stream, pull requests merged in 2018-08, with the labels that each got.

#4272 Fix Bug 1479413 - Remove preview provider and message after it has been displayed
  content-src/asrouter/README.md
  lib/ASRouter.jsm
  test/unit/asrouter/ASRouter.test.js
Labels: PR / R+ with nits

#4273 Fix Bug 1476450 - disallow text-transform in sass-lint
  .sass-lint.yml
  content-src/components/Card/_Card.scss
  content-src/components/TopSites/_TopSites.scss
Labels: PR / R+

#4278 Bug 1479478 - Exclude default search URLs from topsites
  lib/ActivityStream.jsm
  lib/TopSitesFeed.jsm
  test/unit/lib/TopSitesFeed.test.js
Labels: PR / Needs review

#4269 Bug 1476055 - Add telemetry for JEXL and other targeting errors
  docs/v2-system-addon/data_events.md
  lib/ASRouter.jsm
  lib/ASRouterFeed.jsm
  lib/ASRouterTargeting.jsm
  test/browser/browser_asrouter_targeting.js
  test/unit/asrouter/ASRouter.test.js
  test/unit/asrouter/ASRouterFeed.test.js
Labels: PR / R+

#4280 Port Bug 1478404 - remove _xpcom_categories annotations as they're dead code, r=florian
  aboutNewTabService.js
Labels: PR / Needs review

#4259 Fix Bug 1472000: consolidate ASRouter message provider prefs
  karma.mc.config.js
  lib/ASRouter.jsm
  lib/ActivityStream.jsm
  test/unit/asrouter/ASRouter.test.js
  test/unit/asrouter/constants.js
Labels: PR / Needs review

#4285 Fix Bug 1480814 - Add a pref to enable/disable top site search shortcuts on the newtab page
  lib/ActivityStream.jsm
Labels: PR / R+

#4291 Fix Bug 1481503 - Use pocket outline for save action and solid pocket for saved
  content-src/lib/link-menu-options.js
  content-src/styles/_icons.scss
  data/content/assets/glyph-pocket-save-16.svg
Labels: PR / R+

#4293 Fix Bug 1481571 - ship a google icon
  data/content/tippytop/images/google-com@2x.png
  data/content/tippytop/top_sites.json
Labels: PR / R+

#4286 Fix Bug 1480535 - Make in-content search box more prominent
  content-src/components/Search/_Search.scss
Labels: PR / R+

#4288 Fix Bug 1480518 - Replace default and frecent sites with @search when they match given URL pattern
  common/Actions.jsm
  content-src/components/TopSites/TopSite.jsx
  content-src/lib/link-menu-options.js
  lib/PlacesFeed.jsm
  lib/TopSitesFeed.jsm
  test/unit/lib/PlacesFeed.test.js
  test/unit/lib/TopSitesFeed.test.js
Labels: PR / R+ with nits

#4295 Fix Bug 1480506 - Top Search Shortcuts should allow user to unpin
  content-src/components/LinkMenu/LinkMenu.jsx
  content-src/components/TopSites/TopSite.jsx
  content-src/components/TopSites/TopSitesConstants.js
Labels: PR / R+

#4284 Bug 1479021: support url params in provider endpoints
  lib/ASRouter.jsm
  test/unit/asrouter/ASRouter.test.js
Labels: PR / R+

#4289 Fix Bug 1480508: Add search shortcuts for new and existing users
  lib/ActivityStream.jsm
  lib/TopSitesFeed.jsm
  test/browser/head.js
  test/unit/lib/TopSitesFeed.test.js
Labels: PR / R+

#4297 Bug 1481895 - Refactor SEARCH_SHORTCUTS, getSearchProvider to separate file
  lib/SearchShortcuts.jsm
  lib/TopSitesFeed.jsm
Labels: PR / R+

#4299 Bug 1480888 - Implement blocking system for special search shortcut top sites - Part 1
  lib/TopSitesFeed.jsm
  test/unit/lib/TopSitesFeed.test.js
Labels: PR / R+

#4298 Fix Bug 1481677 - persistent/stable search (aka fixed position search bar)
  content-src/components/Base/Base.jsx
  content-src/components/ContextMenu/_ContextMenu.scss
  content-src/components/Search/Search.jsx
  content-src/components/Search/_Search.scss
  content-src/styles/_theme.scss
  content-src/styles/_variables.scss
Labels: PR / R+

#4296 Fix Bug 1481597 - Use the correct awesomebar API
  lib/PlacesFeed.jsm
  test/unit/lib/PlacesFeed.test.js
Labels: Blocked, PR / R+

#4283 Fixes Bug 1476045 - SPOCs stop showing after seeing 100 impressions o…
  lib/TopStoriesFeed.jsm
  test/unit/lib/TopStoriesFeed.test.js
Labels: PR / R+

#4304 Fix Bug 1482184 - only apply fixed-search if search section is visible
  content-src/components/Base/Base.jsx
Labels: PR / R+

#4276 Fix Bug 1479458 - Spocs updating when pref changes from a shield study
  content-src/components/Base/Base.jsx
  lib/SectionsManager.jsm
  lib/TopStoriesFeed.jsm
  test/unit/content-src/components/Base.test.jsx
  test/unit/lib/SectionsManager.test.js
  test/unit/lib/TopStoriesFeed.test.js
Labels: PR / R+ with nits

#4301 Add utm params to initial fetch call.
  content-src/components/StartupOverlay/StartupOverlay.jsx
Labels: PR / R+ with nits

#4305 Fix Bug 1482190: don't convert manually pinned sites to search shortcuts
  lib/TopSitesFeed.jsm
Labels: PR / R+

#4303 Fix Bug 1481901: include additional search shortcut providers
  lib/ActivityStream.jsm
  lib/SearchShortcuts.jsm
  lib/TopSitesFeed.jsm
  test/unit/lib/ActivityStream.test.js
  test/unit/lib/TopSitesFeed.test.js
Labels: PR / R+ with nits

#4308 Fix Bug 1482247: rtl search icon position
  content-src/components/Search/_Search.scss
Labels: PR / Needs review

#4309 Fix Bug 1482209 - Handle disabling of the search shortcuts experiment
  lib/TopSitesFeed.jsm
  test/unit/lib/TopSitesFeed.test.js
Labels: PR / Needs review

#4290 Bug 1480513: Add telemetry for search shortcut
  content-src/components/TopSites/TopSite.jsx
  docs/v2-system-addon/data_dictionary.md
  docs/v2-system-addon/data_events.md
  test/schemas/pings.js
  test/unit/content-src/components/TopSites.test.jsx
Labels: PR / Needs review

#4310 Fix Bug 1482255: fix search shortcut pinning race condition
  lib/TopSitesFeed.jsm
Labels: PR / R+

#4315 Fix Bug 1481903: restrict search shortcuts to the correct regions
  lib/ActivityStream.jsm
  test/unit/lib/ActivityStream.test.js
Labels: PR / R+

#4313 Fix Bug 1482412 - Don't change the status of existing pinned sites
  lib/TopSitesFeed.jsm
  test/unit/lib/TopSitesFeed.test.js
Labels: PR / R+

#4318 Fix Bug 1482473 - Top search should be more like a button not a link
  content-src/components/TopSites/TopSite.jsx
  content-src/components/TopSites/_TopSites.scss
  test/unit/content-src/components/TopSites.test.jsx
Labels: PR / R+ with nits

#4319 Fix Bug 1482464: check for e.identifier before trying to match
  lib/TopSitesFeed.jsm
Labels: PR / Needs review

#4317 Fix Bug 1480507 - Add/Edit new Top Search Shortcut
  common/Actions.jsm
  common/Reducers.jsm
  content-src/components/TopSites/SearchShortcutsForm.jsx
  content-src/components/TopSites/TopSites.jsx
  content-src/components/TopSites/_TopSites.scss
  content-src/lib/section-menu-options.js
  lib/TopSitesFeed.jsm
  locales/en-US/strings.properties
  test/unit/common/Reducers.test.js
  test/unit/content-src/components/SectionMenu.test.jsx
  test/unit/content-src/components/TopSites.test.jsx
  test/unit/lib/TopSitesFeed.test.js
Labels: PR / R+

#4320 Fix Bug 1482479 - Update SEARCH_SHORTCUTS and top_sites.json to support the 9 desired search urls
  content-src/components/TopSites/SearchShortcutsForm.jsx
  content-src/components/TopSites/_TopSites.scss
  data/content/tippytop/images/baidu-com@2x.png
  data/content/tippytop/images/bing-com@2x.png
  data/content/tippytop/images/duckduckgo-com@2x.png
  data/content/tippytop/images/yandex-com@2x.png
  data/content/tippytop/top_sites.json
  lib/SearchShortcuts.jsm
  lib/TopSitesFeed.jsm
  test/unit/lib/TopSitesFeed.test.js
Labels: PR / Needs review

#4321 Bug 1482519 - Separate custom search shortcut options from organic ones
  content-src/components/TopSites/SearchShortcutsForm.jsx
  lib/SearchShortcuts.jsm
  lib/TopSitesFeed.jsm
  test/unit/lib/TopSitesFeed.test.js
Labels: PR / Needs review

#4323 Fix Bug 1482532 - make search shorcuts draggable again
  content-src/components/TopSites/TopSite.jsx
Labels: PR / Needs review

#4322 fix(tests): Skip taskcluster eslint as we have coverage with travis
  mochitest.sh
Labels: PR / Needs review

#4324 Bug 1479458 - Fixing broadcast of updated data from cache.
  lib/TopStoriesFeed.jsm
  test/unit/lib/TopStoriesFeed.test.js
Labels: PR / R+

#4328 Fix Bug 1482853 - white background for all searchys
  content-src/components/TopSites/SearchShortcutsForm.jsx
  content-src/components/TopSites/TopSite.jsx
  content-src/components/TopSites/_TopSites.scss
Labels: PR / R+

#4327 Fix Bug 1482865 - fix searchy overlap when resizing window
  content-src/components/TopSites/_TopSites.scss
Labels: PR / R+

#4329 chore(mc): Port Bug 1482565 - Support and show @Яндекс and @百度 searches for yandex and baidu r=mkaply
  lib/SearchShortcuts.jsm
Labels: PR / R+

#4332 Fix Bug 1482854 - Middle clicking an @search Top Site wrongly triggers autoscroll
  content-src/components/TopSites/TopSite.jsx
Labels: PR / Needs review

#4326 Fix Bug 1482629 - Compare search topsites against search engine _internalAliases
  lib/SearchShortcuts.jsm
  lib/TopSitesFeed.jsm
  test/unit/lib/TopSitesFeed.test.js
Labels: PR / R+

#4325 Fix Bug 1482871 - remove blue flash when clicking on div.search-wrapper
  content-src/components/Search/_Search.scss
Labels: PR / Needs review

#4337 Fix Bug 1483135 - Search shortcuts are not tabbable
  content-src/components/TopSites/TopSite.jsx
Labels: PR / Needs review

#4341 Fix Bug 1483257 - update search shortcuts when enabling experiment
  lib/TopSitesFeed.jsm
  test/unit/lib/TopSitesFeed.test.js
Labels: PR / Needs review

#4345 Bug 1483615 - Turn search shortcuts off and default filtering by default for release
  lib/ActivityStream.jsm
Labels: PR / Needs review

#4349 Bug 1483653 - Sites filtered out by improvesearch.noDefaultSearchTiles are replaced by default sites
  lib/TopSitesFeed.jsm
Labels: PR / Needs review

#4347 Fix Bug 1483255 - move search shortcut pinning/unpinning to feed
  common/Actions.jsm
  content-src/components/TopSites/SearchShortcutsForm.jsx
  lib/TopSitesFeed.jsm
  test/unit/lib/TopSitesFeed.test.js
Labels: PR / R+

#4343 Bug 1483562 - Use object for button_action in ASR
  content-src/asrouter/asrouter-content.jsx
  content-src/asrouter/templates/OnboardingMessage/OnboardingMessage.jsx
  lib/ASRouter.jsm
  lib/OnboardingMessageProvider.jsm
  test/unit/asrouter/ASRouter.test.js
Labels: PR / Needs review

#4351 (multiple): Add ASR telem
  content-src/asrouter/schemas/message-format.md
  lib/ASRouterTargeting.jsm
  test/browser/browser_asrouter_targeting.js
Labels: PR / R+

#4270 Fix Bug 1478569 - New Action: Show AppMenu
  common/Actions.jsm
  content-src/asrouter/asrouter-content.jsx
  content-src/asrouter/components/Button/Button.jsx
  content-src/asrouter/templates/SimpleSnippet/SimpleSnippet.jsx
  content-src/asrouter/templates/SimpleSnippet/SimpleSnippet.schema.json
  content-src/asrouter/templates/SimpleSnippet/_SimpleSnippet.scss
  lib/ASRouter.jsm
  test/unit/asrouter/ASRouter.test.js
  test/unit/asrouter/asrouter-content.test.jsx
  test/unit/asrouter/templates/SimpleSnippet.test.jsx
Labels: PR / R+

#4352 Fix Bug 1484227 - set improvesearch.noDefaultSearchTile to true
  lib/ActivityStream.jsm
Labels: PR / Needs review

#4354 fix(fxa): remove extra spacing in the FxA funnel cake flow url
  content-src/components/StartupOverlay/StartupOverlay.jsx
Labels: PR / R+

#4338 Fix Bug 1476684 - Onboarding shouldn't be affected by snippets experiment prefs
  content-src/activity-stream.jsx
  content-src/components/Base/Base.jsx
  content-src/lib/asroutercontent.js
  content-src/lib/snippets.js
  lib/ASRouter.jsm
  lib/ASRouterFeed.jsm
  lib/ASRouterTargeting.jsm
  lib/ActivityStream.jsm
  test/browser/browser_asrouter_targeting.js
  test/unit/activity-stream.test.jsx
  test/unit/asrouter/ASRouter.test.js
  test/unit/asrouter/ASRouterTargeting.test.js
  test/unit/asrouter/constants.js
  test/unit/content-src/lib/snippets.test.js
Labels: PR / R+

#4266 Fix Bug 1476688: Add ASRouter provider blocking and frequency capping
  content-src/asrouter/asrouter-content.jsx
  lib/ASRouter.jsm
  lib/ASRouterTargeting.jsm
  test/unit/asrouter/ASRouter.test.js
  test/unit/asrouter/ASRouterTargeting.test.js
Labels: PR / R+ with nits

#4358 Fix Bug 1482134 - Add client_id to onboarding telemetry in Activity Stream router
  content-src/asrouter/templates/OnboardingMessage/OnboardingMessage.jsx
  docs/v2-system-addon/data_events.md
  lib/TelemetryFeed.jsm
  test/unit/lib/TelemetryFeed.test.js
Labels: PR / R+

#4364 Fix Bug 1482579 - Wait on Search services to intialize before using it
  lib/TopSitesFeed.jsm
  test/unit/unit-entry.js
Labels: PR / R+

#4360 Fix Bug 1484031 - Add template schema for doorhanger
  content-src/asrouter/templates/CFR/templates/ExtensionDoorhanger.schema.json
  test/unit/asrouter/templates/ExtensionDoorhanger.test.jsx
Labels: PR / R+

#4367 Backport 1484496 - Support JS iterator protocol for nsISimpleEnumerator
  lib/ASRouterTriggerListeners.jsm
  lib/Screenshots.jsm
  test/unit/asrouter/ASRouterTriggerListeners.test.js
  test/unit/lib/Screenshots.test.js
  test/unit/unit-entry.js
Labels: PR / R+

#4368 Fix Bug 1484292 - remove hover state in Add Search Engine modal
  content-src/components/TopSites/_TopSites.scss
Labels: PR / Needs review

#4369 Fix Bug 1484290 - remove hairline/border from searchy icon
  content-src/components/TopSites/_TopSites.scss
Labels: PR / Needs review

#4370 Backport Bug 1364392 - Provide correct triggeringPrincipal to openLinkIn
  lib/ASRouter.jsm
  test/unit/asrouter/ASRouter.test.js
Labels: PR / R+

#4353 Fix Bug 1471391: Create CFR doorhanger
  content-src/asrouter/templates/CFR/templates/ExtensionDoorhanger.schema.json
  data/content/assets/glyph-webextension-16.svg
  lib/CFRPageActions.jsm
Labels: PR / R+

#4356 bug 1478755 - Ensure spocs load without a flash of rec
  common/Actions.jsm
  common/Reducers.jsm
  content-src/components/Sections/Sections.jsx
  lib/TopStoriesFeed.jsm
  test/unit/common/Reducers.test.js
  test/unit/content-src/components/Sections.test.jsx
  test/unit/lib/TopStoriesFeed.test.js
Labels: PR / R+ with nits

#4373 Bug 1486529 - Add doorhanger testing via asrouter admin panel
  karma.mc.config.js
  lib/ASRouter.jsm
  lib/CFRMessageProvider.jsm
  lib/CFRPageActions.jsm
  test/unit/asrouter/ASRouter.test.js
Labels: PR / R+

#4357 Bug 1485345 - Add timestamp targeting
  content-src/asrouter/README.md
  content-src/asrouter/schemas/message-format.md
  lib/ASRouterTargeting.jsm
  lib/ActivityStream.jsm
  test/browser/browser_asrouter_targeting.js
Labels: PR / R+ with nits

#4375 (nobug): Switch to lazy loading the modules
  lib/ASRouter.jsm
  test/unit/unit-entry.js
Labels: PR / R+

#4378 Fix Bug 1484289 - Update hover state style for Search Shortcuts
  content-src/components/TopSites/_TopSites.scss
  content-src/styles/_variables.scss
Labels: PR / Needs review

#4380 Fix Admin page CFR
  lib/ASRouter.jsm
  lib/CFRPageActions.jsm
  test/unit/asrouter/ASRouter.test.js
Labels: PR / Needs review

#4382 (nobug) Turn onboarding off by default
  lib/ActivityStream.jsm
Labels: PR / Needs review

#4381 (nobug): Run onboarding mochitests
  mochitest.sh
Labels: PR / R+

#4385 Fix Bug 1486867 - Install and No thanks actions should block and hide CFR message
  lib/CFRPageActions.jsm
Labels: PR / Needs review

#4387 Bug 1487208 - Targeting on cohort should work for all providers
  content-src/asrouter/schemas/message-format.md
  lib/ASRouterTargeting.jsm
  test/browser/browser_asrouter_targeting.js
Labels: PR / R+

#4388 Fix Bug 1486472 - Disable CFR notifications in private browsing mode
  lib/CFRPageActions.jsm
Labels: PR / R+

#4389 Fix Bug 1487156 - Track impressions for frequency capping in CFR
  content-src/components/ASRouterAdmin/ASRouterAdmin.jsx
  lib/CFRPageActions.jsm
Labels: PR / Needs review

#4390 Fix Bug 1487118: hide all recommendations when the ASRouter gets disa…
  lib/ASRouter.jsm
  lib/CFRPageActions.jsm
Labels: PR / R+

#4384 Fix Bug 1486648 - Implement telemetry policy for CFR
  lib/TelemetryFeed.jsm
  test/unit/lib/TelemetryFeed.test.js
Labels: PR / R+

#4392 Fix Bug 1487241 - Make sure top frecent query targeting meets requirements for CFR
  lib/ASRouterTargeting.jsm
  lib/CFRMessageProvider.jsm
Labels: PR / R+

#4393 Bug 1485422 - Add rating stars to CFR
  content-src/asrouter/templates/CFR/templates/ExtensionDoorhanger.schema.json
  data/content/assets/glyph-star-17.svg
  lib/CFRMessageProvider.jsm
  lib/CFRPageActions.jsm
Labels: PR / Needs review

#4394 Fix Bug 1487771 - add a delay for showing the context menu button when hovering links/sites
  content-src/styles/_variables.scss
Labels: PR / R+

#4372 Bug 1485528 - Ensure proper cache load when browser shutsdown and res…
  lib/PersistentCache.jsm
  lib/TopStoriesFeed.jsm
  test/unit/lib/PersistentCache.test.js
  test/unit/lib/TopStoriesFeed.test.js
Labels: PR / R+

#4395 Port Bug 1485418 - Land CFR UI Strings r=flod,k88hudson
  lib/CFRMessageProvider.jsm
  lib/CFRPageActions.jsm
Labels: PR / Needs review

#4391 Fix Bug 1487406 - Update ExtensionDoorhanger schema and tests
  content-src/asrouter/templates/CFR/templates/ExtensionDoorhanger.schema.json
  test/unit/asrouter/templates/ExtensionDoorhanger.test.jsx
Labels: PR / R+

#4371 Fix Bug 1484035, 1480099 - Implement CFR telemetry
  content-src/asrouter/templates/CFR/templates/ExtensionDoorhanger.schema.json
  docs/v2-system-addon/data_events.md
  lib/ASRouter.jsm
  lib/CFRMessageProvider.jsm
  lib/CFRPageActions.jsm
  test/unit/asrouter/ASRouter.test.js
  test/unit/asrouter/templates/ExtensionDoorhanger.test.jsx
Labels: PR / R+

#4355 bug 1483655 - Add a new explainer to the Recommended by Pocket section
  common/Actions.jsm
  common/Reducers.jsm
  content-src/components/CollapsibleSection/CollapsibleSection.jsx
  content-src/components/CollapsibleSection/_CollapsibleSection.scss
  content-src/components/MoreRecommendations/MoreRecommendations.jsx
  content-src/components/MoreRecommendations/_MoreRecommendations.scss
  content-src/components/PocketLoggedInCta/PocketLoggedInCta.jsx
  content-src/components/PocketLoggedInCta/_PocketLoggedInCta.scss
  content-src/components/Sections/Sections.jsx
  content-src/components/Sections/_Sections.scss
  content-src/components/Topics/Topics.jsx
  content-src/components/Topics/_Topics.scss
  content-src/styles/_activity-stream.scss
  content-src/styles/_variables.scss
  docs/v2-system-addon/data_events.md
  lib/AboutPreferences.jsm
  lib/ActivityStream.jsm
  lib/SectionsManager.jsm
  lib/TopStoriesFeed.jsm
  locales/en-US/strings.properties
  test/unit/common/Reducers.test.js
  test/unit/content-src/components/CollapsibleSection.test.jsx
  test/unit/content-src/components/MoreRecommendations.test.jsx
  test/unit/content-src/components/PocketLoggedInCta.test.jsx
  test/unit/content-src/components/Sections.test.jsx
  test/unit/content-src/components/Topics.test.jsx
  test/unit/lib/AboutPreferences.test.js
  test/unit/lib/HighlightsFeed.test.js
  test/unit/lib/TopStoriesFeed.test.js
Labels: PR / Needs work

#4397 (nobug) Remove the popupnotification to stop undesired chiclet collapse
  lib/CFRPageActions.jsm
Labels: PR / R+
