Repository mozilla/activity-stream, pull requests merged in 2018-02, with the labels that each got.

#3976 chore (polish): change drag and drop target to a grey box
  system-addon/content-src/components/TopSites/TopSite.jsx
  system-addon/content-src/components/TopSites/_TopSites.scss
  system-addon/test/unit/content-src/components/TopSites.test.jsx
Labels: PR / Needs review

#3974 chore(mc): Port Bug 1432992 - Remove definitions of Ci, Cr, Cc, and Cu
  bin/render-activity-stream-html.js
  package-lock.json
  package.json
  system-addon/bootstrap.js
  system-addon/lib/ActivityStream.jsm
  system-addon/lib/ActivityStreamMessageChannel.jsm
  system-addon/lib/ActivityStreamPrefs.jsm
  system-addon/lib/FaviconFeed.jsm
  system-addon/lib/FilterAdult.jsm
  system-addon/lib/HighlightsFeed.jsm
  system-addon/lib/ManualMigration.jsm
  system-addon/lib/NewTabInit.jsm
  system-addon/lib/PersistentCache.jsm
  system-addon/lib/PlacesFeed.jsm
  system-addon/lib/PrefsFeed.jsm
  system-addon/lib/Screenshots.jsm
  system-addon/lib/SectionsManager.jsm
  system-addon/lib/ShortURL.jsm
  system-addon/lib/SnippetsFeed.jsm
  system-addon/lib/Store.jsm
  system-addon/lib/SystemTickFeed.jsm
  system-addon/lib/TelemetryFeed.jsm
  system-addon/lib/TippyTopProvider.jsm
  system-addon/lib/TopSitesFeed.jsm
  system-addon/lib/TopStoriesFeed.jsm
  system-addon/lib/UTEventReporting.jsm
  system-addon/lib/UserDomainAffinityProvider.jsm
  system-addon/ping-centre/PingCentre.jsm
  system-addon/test/functional/mochitest/browser_getScreenshots.js
  system-addon/test/unit/lib/ActivityStreamMessageChannel.test.js
  system-addon/test/unit/lib/FilterAdult.test.js
  system-addon/test/unit/lib/PlacesFeed.test.js
  system-addon/test/unit/lib/SectionsManager.test.js
  system-addon/test/unit/lib/TelemetryFeed.test.js
  system-addon/test/unit/lib/TopStoriesFeed.test.js
  system-addon/test/unit/lib/UserDomainAffinityProvider.test.js
  system-addon/test/unit/ping-centre/PingCentre.test.js
  system-addon/test/unit/unit-entry.js
Labels: PR / R+

#3957 fix(snippets): Use the correct FxAccounts#promiseSignUpURI method
  system-addon/lib/SnippetsFeed.jsm
  system-addon/test/unit/lib/SnippetsFeed.test.js
Labels: PR / Needs review

#3980 fix (prerender) - set topSitesRows to 1 for initial prerendered pref
  system-addon/common/PrerenderData.jsm
Labels: PR / Needs review

#3983 fix (styles): fix pocket disclaimer text for wide layout
  system-addon/content-src/components/CollapsibleSection/_CollapsibleSection.scss
Labels: PR / Needs review

#3984 Bug 1438200 - Use domain name as provided in Pocket feed response
  system-addon/lib/TopStoriesFeed.jsm
  system-addon/test/unit/lib/TopStoriesFeed.test.js
Labels: PR / R+

#3985 chore(mc): Port Bug 1426705 - Add responsive layout, React 16 and bug fixes to Activity Stream. r=ursula
  system-addon/vendor/react-dev.js
Labels: PR / Needs review

#3965 Fix Bug 1401464 - Appropriate label required on Edit Top Site dialog
  locales/en-US/strings.properties
  system-addon/content-src/components/TopSites/TopSiteForm.jsx
  system-addon/content-src/components/TopSites/TopSiteFormInput.jsx
  system-addon/content-src/components/TopSites/_TopSites.scss
  system-addon/content-src/styles/_icons.scss
  system-addon/content-src/styles/_variables.scss
  system-addon/data/content/assets/glyph-cancel-16.svg
  system-addon/test/unit/content-src/components/TopSites.test.jsx
Labels: PR / Needs work

#3986 Fix Bug 1438565 - Send source and action_position with DELETE ping
  system-addon/content-src/components/ConfirmDialog/ConfirmDialog.jsx
  system-addon/content-src/lib/link-menu-options.js
  system-addon/test/schemas/pings.js
  system-addon/test/unit/content-src/components/ConfirmDialog.test.jsx
  system-addon/test/unit/content-src/components/LinkMenu.test.jsx
Labels: PR / Needs review

#3988 Fix Bug 1438523 - add enableWideLayout to prerender prefs
  system-addon/common/PrerenderData.jsm
  system-addon/content-src/components/Sections/_Sections.scss
Labels: PR / Needs review

#3987 Fix Bug 1422079 - sections context menu
  docs/v2-system-addon/sections.md
  locales/en-US/strings.properties
  system-addon/content-src/components/Base/Base.jsx
  system-addon/content-src/components/Base/_Base.scss
  system-addon/content-src/components/CollapsibleSection/CollapsibleSection.jsx
  system-addon/content-src/components/CollapsibleSection/_CollapsibleSection.scss
  system-addon/content-src/components/SectionMenu/SectionMenu.jsx
  system-addon/content-src/components/Sections/Sections.jsx
  system-addon/content-src/components/TopSites/TopSites.jsx
  system-addon/content-src/components/TopSites/_TopSites.scss
  system-addon/content-src/lib/section-menu-options.js
  system-addon/content-src/styles/_icons.scss
  system-addon/content-src/styles/_variables.scss
  system-addon/data/content/assets/glyph-add-16.svg
  system-addon/data/content/assets/glyph-arrowhead-down-16.svg
  system-addon/data/content/assets/glyph-arrowhead-up-16.svg
  system-addon/data/content/assets/glyph-info-16.svg
  system-addon/data/content/assets/glyph-info-option-12.svg
  system-addon/data/content/assets/glyph-maximize-16.svg
  system-addon/data/content/assets/glyph-minimize-16.svg
  system-addon/lib/ActivityStream.jsm
  system-addon/lib/SectionsManager.jsm
  system-addon/test/schemas/pings.js
  system-addon/test/unit/content-src/components/CollapsibleSection.test.jsx
  system-addon/test/unit/content-src/components/SectionMenu.test.jsx
  system-addon/test/unit/content-src/components/Sections.test.jsx
  system-addon/test/unit/content-src/components/TopSites.test.jsx
Labels: PR / R+ with nits

#3991 chore(mc): Port Bug 1234008 - Recompress some png images with zopflipng r=Dolske,Grisha,jryans
  system-addon/data/content/tippytop/images/aliexpress-com@2x.png
  system-addon/data/content/tippytop/images/allegro-pl@2x.png
  system-addon/data/content/tippytop/images/amazon@2x.png
  system-addon/data/content/tippytop/images/avito-ru@2x.png
  system-addon/data/content/tippytop/images/bbc-uk@2x.png
  system-addon/data/content/tippytop/images/ebay@2x.png
  system-addon/data/content/tippytop/images/facebook-com@2x.png
  system-addon/data/content/tippytop/images/leboncoin-fr@2x.png
  system-addon/data/content/tippytop/images/ok-ru@2x.png
  system-addon/data/content/tippytop/images/olx-pl@2x.png
  system-addon/data/content/tippytop/images/reddit-com@2x.png
  system-addon/data/content/tippytop/images/twitter-com@2x.png
  system-addon/data/content/tippytop/images/vk-com@2x.png
  system-addon/data/content/tippytop/images/wikipedia-org@2x.png
  system-addon/data/content/tippytop/images/wykop-pl@2x.png
  system-addon/data/content/tippytop/images/youtube-com@2x.png
Labels: PR / Needs review

#3992 chore(mc): Port Bug 1410818 - Add a test to verify the menu options for a default top site. r=Mardak
  system-addon/test/functional/mochitest/browser.ini
  system-addon/test/functional/mochitest/browser_topsites_contextMenu_options.js
  system-addon/test/functional/mochitest/browser_topsites_section.js
  system-addon/test/functional/mochitest/head.js
Labels: PR / Needs review

#3994 Fix Bug 1440792 - Context menus for sites and cards are opened too far from the button
  system-addon/content-src/components/CollapsibleSection/_CollapsibleSection.scss
Labels: PR / Needs review

#3996 chore(styles): Use a down-16 arrow for down/up and a smaller down-12 for down/forward.
  system-addon/content-src/components/CollapsibleSection/CollapsibleSection.jsx
  system-addon/content-src/components/CollapsibleSection/_CollapsibleSection.scss
  system-addon/content-src/styles/_icons.scss
  system-addon/data/content/assets/glyph-arrowhead-up-16.svg
Labels: PR / Needs review

#3998 Fix Bug 1440970 - Fix top sites context menu position
  system-addon/content-src/components/CollapsibleSection/_CollapsibleSection.scss
Labels: PR / Needs review

#4000 Fix Bug 1441301 - Adjust section context menu related styling
  system-addon/content-src/components/CollapsibleSection/_CollapsibleSection.scss
  system-addon/content-src/styles/_variables.scss
Labels: PR / Needs review

#3999 Fix Bug 1440781 - Refreshing preloaded tabs interferes with spoc placement
  system-addon/common/Reducers.jsm
  system-addon/lib/TopStoriesFeed.jsm
  system-addon/test/unit/common/Reducers.test.js
  system-addon/test/unit/lib/TopStoriesFeed.test.js
Labels: PR / R+

#3995 Fix Bug 1440378: Events Telemetry should be off by default in release
  system-addon/lib/ActivityStream.jsm
  system-addon/lib/TelemetryFeed.jsm
  system-addon/test/unit/lib/TelemetryFeed.test.js
Labels: PR / Needs review

#4001 fix Bug 1441235 - Update jsm-to-esmodules to parse var EXPORTED_SYMBOLS
  package-lock.json
  package.json
Labels: PR / Needs review

#4004 fix Bug 1431464 - Expose devtools usage to snippets
  docs/v2-system-addon/snippets.md
  system-addon/lib/SnippetsFeed.jsm
  system-addon/test/unit/lib/SnippetsFeed.test.js
  system-addon/test/unit/unit-entry.js
Labels: PR / R+

#3997 Fix Bug 1440456 - lazy render context menus
  system-addon/content-src/components/Card/Card.jsx
  system-addon/content-src/components/CollapsibleSection/CollapsibleSection.jsx
  system-addon/content-src/components/ContextMenu/ContextMenu.jsx
  system-addon/content-src/components/LinkMenu/LinkMenu.jsx
  system-addon/content-src/components/SectionMenu/SectionMenu.jsx
  system-addon/content-src/components/TopSites/TopSite.jsx
  system-addon/test/functional/mochitest/browser_topsites_section.js
  system-addon/test/unit/content-src/components/Card.test.jsx
  system-addon/test/unit/content-src/components/ContextMenu.test.jsx
  system-addon/test/unit/content-src/components/LinkMenu.test.jsx
  system-addon/test/unit/content-src/components/SectionMenu.test.jsx
  system-addon/test/unit/content-src/components/Sections.test.jsx
  system-addon/test/unit/content-src/components/TopSites.test.jsx
Labels: PR / R+ with nits

#4007 fix Bug 1431525 - Add addonInfo to snippets data
  docs/v2-system-addon/snippets.md
  system-addon/lib/SnippetsFeed.jsm
  system-addon/test/unit/lib/SnippetsFeed.test.js
  system-addon/test/unit/unit-entry.js
Labels: PR / R+

#4003 fix(topstories): Pinned cards should be cleared when section is re-initialized
  system-addon/common/Reducers.jsm
  system-addon/test/unit/common/Reducers.test.js
Labels: PR / R+ with nits

#4010 Fix Bug 1431470 - Add .getTotalBookmarksCount() to gSnippetsMap
  docs/v2-system-addon/snippets.md
  system-addon/common/Actions.jsm
  system-addon/content-src/lib/snippets.js
  system-addon/lib/SnippetsFeed.jsm
  system-addon/test/unit/content-src/lib/snippets.test.js
  system-addon/test/unit/lib/SnippetsFeed.test.js
Labels: PR / R+ with nits
