Repository mozilla/activity-stream, pull requests merged in 2018-07, with the labels that each got.

#4226 Fix Bug 1472642: focus email field on invalid input in about:welcome
  content-src/components/StartupOverlay/StartupOverlay.jsx
Labels: PR / R+

#4225 Fix Bug 1472209 - Remove StartupOverlay if the tour is skipped
  content-src/components/Base/Base.jsx
  content-src/components/StartupOverlay/StartupOverlay.jsx
  test/unit/content-src/components/StartupOverlay.test.jsx
Labels: PR / Needs review

#4224 Bug 1471695 - add Addon targeting to ASRouter
  lib/ASRouterTargeting.jsm
  test/functional/mochitest/browser_asrouter_targeting.js
Labels: PR / Needs review

#4228 (styles) Fix Bug 1472819: adjust position of Pocket disclaimer button
  content-src/components/CollapsibleSection/_CollapsibleSection.scss
Labels: PR / R+

#4229 Fix Bug 1459449 - Upgrate webpack
  .nvmrc
  karma.mc.config.js
  package-lock.json
  package.json
  test/unit/content-src/components/ComponentPerfTimer.test.jsx
  test/unit/lib/TopStoriesFeed.test.js
  webpack.prerender.config.js
  webpack.system-addon.config.js
  yamscripts.yml
Labels: PR / Needs review

#4230 Backport Bug 1434751 - Set Restore Defaults btn visibility
  lib/AboutPreferences.jsm
  test/unit/lib/AboutPreferences.test.js
Labels: PR / Needs review

#4210 Port Bug 1347204 - Implement Google Chrome New Tab Page color properties
  bin/render-activity-stream-html.js
  common/Actions.jsm
  common/Reducers.jsm
  content-src/components/ASRouterAdmin/ASRouterAdmin.scss
  content-src/components/Base/Base.jsx
  content-src/components/Card/_Card.scss
  content-src/styles/_theme.scss
  content-src/styles/activity-stream-mac.scss
  lib/ActivityStream.jsm
  lib/PrefsFeed.jsm
  lib/ThemeFeed.jsm
  test/unit/common/Reducers.test.js
  test/unit/content-src/components/Base.test.jsx
  test/unit/lib/ActivityStream.test.js
  test/unit/lib/PrefsFeed.test.js
  test/unit/lib/ThemeFeed.test.js
  test/unit/unit-entry.js
Labels: PR / R+ with nits

#4231 Fix Bug 1465548 - Pocket about:preferences "Learn more" is in the wrong place
  lib/AboutPreferences.jsm
  test/unit/lib/AboutPreferences.test.js
Labels: PR / R+

#4232 Fix Bug 1473848 - Stop exporting locales not explicitly in CENTRAL_LOCALES, e.g., "mix"
  bin/render-activity-stream-html.js
Labels: PR / R+

#4218 Fix Bug 1471514 - Add top-of-funnel metrics for fxa
  content-src/components/StartupOverlay/StartupOverlay.jsx
  lib/PrefsFeed.jsm
Labels: PR / R+

#4235 Fix Bug 1472038: Use app build ID for telemetry addon_version
  bootstrap.js
  common/Reducers.jsm
  docs/v2-system-addon/data_dictionary.md
  docs/v2-system-addon/data_events.md
  lib/ActivityStream.jsm
  lib/TelemetryFeed.jsm
  test/unit/common/Reducers.test.js
  test/unit/lib/ActivityStream.test.js
  test/unit/lib/TelemetryFeed.test.js
  test/unit/unit-entry.js
Labels: PR / R+

#4233 Fix Bug 1471243: stop AS showing before first run overlay
  content-src/components/Base/Base.jsx
  content-src/components/Base/_Base.scss
  content-src/components/StartupOverlay/StartupOverlay.jsx
  content-src/components/StartupOverlay/_StartupOverlay.scss
  content-src/styles/_activity-stream.scss
Labels: PR / R+

#4238 Backport changes from Bug 1472472
  lib/PlacesFeed.jsm
  test/unit/lib/PlacesFeed.test.js
Labels: PR / Needs review

#4239 Followup Bug 1471243 to fix browser_ext_themes_ntp_colors.js mochitest failure.
  content-src/components/StartupOverlay/_StartupOverlay.scss
Labels: PR / Needs review

#4240 Fix Bug 1471514 - Add top-of-funnel metrics for fxa.
  content-src/components/StartupOverlay/StartupOverlay.jsx
  lib/PrefsFeed.jsm
Labels: PR / R+ with nits

#4244 Fix bug in bbce85b that hides AS incorrectly
  content-src/styles/_activity-stream.scss
Labels: PR / R+ with nits

#4234 Fix Bug 1462114 - Set provider endpoint based on pref value
  lib/ASRouter.jsm
  lib/ActivityStream.jsm
  test/unit/asrouter/ASRouter.test.js
  test/unit/asrouter/ASRouterFeed.test.js
  test/unit/asrouter/constants.js
Labels: PR / R+

#4247 Fix Bug 1476086 - Stop importing locales not explicitly in CENTRAL_LOCALES, e.g., "pbb"
  bin/locales.js
  bin/render-activity-stream-html.js
  bin/strings-import.js
Labels: PR / Needs review

#4246 Fix Bug 1475212 - Onboarding overlay's buttons are not visibly focused using keyboard navigation
  content-src/asrouter/components/ModalOverlay/ModalOverlay.jsx
  content-src/asrouter/components/ModalOverlay/_ModalOverlay.scss
  content-src/asrouter/templates/OnboardingMessage/OnboardingMessage.jsx
  content-src/asrouter/templates/OnboardingMessage/_OnboardingMessage.scss
Labels: PR / Needs review

#4245 Fixing spocs so they have the chance to load on first tab.
  lib/TopStoriesFeed.jsm
  test/unit/lib/TopStoriesFeed.test.js
Labels: PR / R+ with nits

#4251 gSnippetsMap parity in ASRouter
  content-src/asrouter/schemas/message-format.md
  lib/ASRouterTargeting.jsm
  test/functional/mochitest/browser_asrouter_targeting.js
Labels: PR / R+

#4252 Fix Bug 1474411 - Port remaining desired functionality from bootstrap.js to ActivityStream.jsm
  bootstrap.js
  lib/ActivityStream.jsm
  test/unit/lib/ActivityStream.test.js
  test/unit/unit-entry.js
Labels: PR / Needs review

#4248 Bug 1432674 - Add support for frequency caps for AS Router
  content-src/asrouter/asrouter-content.jsx
  content-src/asrouter/schemas/message-format.md
  content-src/asrouter/schemas/provider-response.schema.json
  content-src/components/ASRouterAdmin/ASRouterAdmin.jsx
  lib/ASRouter.jsm
  lib/ASRouterTargeting.jsm
  test/functional/mochitest/browser_asrouter_targeting.js
  test/unit/asrouter/ASRouter.test.js
  test/unit/asrouter/ASRouterTargeting.test.js
Labels: PR / R+ with nits

#4250 Bug 1476381 - Fix outstanding sass lint warnings
  .sass-lint.yml
  content-src/components/Base/_Base.scss
  content-src/components/StartupOverlay/_StartupOverlay.scss
  content-src/styles/_activity-stream.scss
  content-src/styles/_theme.scss
  content-src/styles/_variables.scss
Labels: PR / R+ with nits

#4253 (tests) Fix ASRouterTargeting mochitest failures
  test/functional/mochitest/browser_asrouter_targeting.js
Labels: PR / Needs review

#4243 Fix Bug 1471350: add topFrecentSites to ASRouterTargeting
  lib/ASRouterTargeting.jsm
  test/functional/mochitest/browser_asrouter_targeting.js
  test/unit/unit-entry.js
Labels: PR / R+

#4254 Fix Bug 1474372: Run mochitests on taskcluster
  .taskcluster.yml
  README.md
  mochitest.sh
  package.json
  yamscripts.yml
Labels: PR / R+

#4258 Fix Bug 1476959 - Cut off tail letters in New Tab page (Highlights section)
  content-src/components/Card/_Card.scss
Labels: PR / Needs review

#4262 Fix Bug 1478218: add Places cleanup to browser_asrouter_targeting.js
  lib/ASRouterTargeting.jsm
  test/functional/mochitest/browser_asrouter_targeting.js
Labels: PR / R+

#4260 Fix Bug 1477766 - Display Simplified Onboarding Tour Cards in specific order
  content-src/asrouter/schemas/message-format.md
  content-src/asrouter/schemas/provider-response.schema.json
  lib/ASRouter.jsm
  lib/OnboardingMessageProvider.jsm
  test/unit/asrouter/ASRouter.test.js
  test/unit/asrouter/constants.js
Labels: PR / R+ with nits

#4257 Fix Bug 1477631: Allow setting whitelist hosts via prefs
  lib/ASRouter.jsm
  test/unit/asrouter/ASRouter.test.js
Labels: PR / R+ with nits

#4268 Port Bug 1369466 - Change consumers to the new location of RemotePageManager. r=mossop
  lib/ActivityStreamMessageChannel.jsm
Labels: PR / Needs review

#4265 Backport Bug 1474414 - Move most of browser/extensions/activity-stream to browser/components/newtab
  NewTabComponents.manifest
  aboutNewTabService.js
  bin/prepare-mochitests-dev
  bin/process-system-addon-for-package.js
  bin/update-version.js
  bootstrap.js
  docs/v2-system-addon/1.GETTING_STARTED.md
  install.rdf.in
  jar.mn
  mochitest.sh
  moz.build
  nsIAboutNewTabService.idl
  package.json
  test/browser/.eslintrc.js
  test/browser/blue_page.html
  test/browser/browser.ini
  test/browser/browser_activity_stream_strings.js
  test/browser/browser_as_load_location.js
  test/browser/browser_as_render.js
  test/browser/browser_asrouter_targeting.js
  test/browser/browser_enabled_newtabpage.js
  test/browser/browser_getScreenshots.js
  test/browser/browser_highlights_section.js
  test/browser/browser_newtab_overrides.js
  test/browser/browser_packaged_as_locales.js
  test/browser/browser_topsites_contextMenu_options.js
  test/browser/browser_topsites_section.js
  test/browser/head.js
  test/xpcshell/.eslintrc.js
  test/xpcshell/test_AboutNewTabService.js
  test/xpcshell/xpcshell.ini
  yamscripts.yml
Labels: PR / R+ with nits

#4271 Bug 1478930 - ja-JP-mac builds incorrectly use ja strings
  aboutNewTabService.js
  bin/render-activity-stream-html.js
  test/browser/browser_packaged_as_locales.js
Labels: PR / R+

#4263 Fix Bug 1475921 - remove text-transform usage on localized strings (section headers)
  content-src/components/CollapsibleSection/_CollapsibleSection.scss
  content-src/components/TopSites/_TopSites.scss
Labels: PR / R+

#4275 Fix Bug 1470211 - Dismissing a Bookmarked highlight also dismissed a Saved To Pocket highlight of the same content - Part 2
  content-src/lib/link-menu-options.js
Labels: PR / Needs review

#4255 Fix Bug 1471351: Add openURL trigger to ASRouter
  content-src/asrouter/asrouter-content.jsx
  content-src/asrouter/schemas/provider-response.schema.json
  karma.mc.config.js
  lib/ASRouter.jsm
  lib/ASRouterTargeting.jsm
  lib/ASRouterTriggerListeners.jsm
  lib/OnboardingMessageProvider.jsm
  test/browser/browser.ini
  test/browser/browser_asrouter_trigger_listeners.js
  test/unit/asrouter/ASRouter.test.js
  test/unit/asrouter/ASRouterTriggerListeners.test.js
  test/unit/unit-entry.js
Labels: PR / R+
