Repository mozilla/activity-stream, pull requests merged in 2018-12, with the labels that each got.

#4588 Fix Bug 1510553 - [RTL] Dot character is wrongly hyperlinked with the…
  lib/SnippetsTestMessageProvider.jsm
Labels: PR / Needs review

#4587 Fix Bug 1511156 - Windows attribution data is double encoded
  lib/OnboardingMessageProvider.jsm
  test/unit/asrouter/templates/OnboardingMessage.test.jsx
Labels: PR / Needs review

#4590 Fix Bug 1503632, reduce CPU usage when moving mouse on newtab
  content-src/components/CollapsibleSection/CollapsibleSection.jsx
Labels: PR / R+

#4585 Fix Bug 1511804 - CFRPageActions tries to wait for a layout flush but doesn't
  lib/CFRPageActions.jsm
  test/unit/asrouter/CFRPageActions.test.js
Labels: PR / R+

#4586 Backport Bug 1511112 - Remove remaining style flushes for getting the…
  lib/CFRPageActions.jsm
Labels: PR / Needs work

#4594 Fix Bug 1510551-Align checkbox with EOY and Newsletter snippet strings
  content-src/asrouter/templates/EOYSnippet/_EOYSnippet.scss
  content-src/asrouter/templates/SubmitFormSnippet/_SubmitFormSnippet.scss
Labels: PR / R+

#4593 Fix Bug 1514337 - Activity Stream layout pref and layout data for rapid experimentation
  common/Actions.jsm
  common/Reducers.jsm
  content-src/components/Sections/Sections.jsx
  lib/TopStoriesFeed.jsm
  test/unit/common/Reducers.test.js
  test/unit/lib/TopStoriesFeed.test.js
Labels: PR / R+ with nits

#4596 Fix Bug 1514913 - Hello world Pocket + New Tab test experiment
  content-src/components/Sections/Sections.jsx
  content-src/components/Sections/_Sections.scss
Labels: PR / Needs work

#4600 Backport Bug 1492937 - Make the JS subscript loader load scripts excl…
  aboutNewTabService.js
Labels: PR / Needs review

#4628 Devtools page pocket
  content-src/components/ASRouterAdmin/ASRouterAdmin.jsx
  content-src/components/ASRouterAdmin/ASRouterAdmin.scss
  content-src/components/ASRouterAdmin/SimpleHashRouter.jsx
  content-src/components/Base/Base.jsx
  test/unit/content-src/components/ASRouterAdmin.test.jsx
Labels: PR / R+ with nits

#4629 Bug 1516008 - Add pocket layout code behind its own separate pref
  common/Actions.jsm
  common/Reducers.jsm
  content-src/components/Base/Base.jsx
  content-src/components/DiscoveryStreamBase/DiscoveryStreamBase.jsx
  content-src/components/DiscoveryStreamBase/_DiscoveryStreamBase.scss
  content-src/components/Sections/Sections.jsx
  content-src/components/Sections/_Sections.scss
  content-src/styles/_activity-stream.scss
  lib/ActivityStream.jsm
  lib/DiscoveryStreamFeed.jsm
  lib/TopStoriesFeed.jsm
  test/unit/common/Reducers.test.js
  test/unit/content-src/components/Base.test.jsx
  test/unit/lib/DiscoveryStreamFeed.test.js
  test/unit/lib/TopStoriesFeed.test.js
Labels: PR / R+ with nits

#4599 Fix Bug 1508388 - Search hand-off
  common/Actions.jsm
  common/Reducers.jsm
  content-src/components/Base/Base.jsx
  content-src/components/Search/Search.jsx
  content-src/components/Search/_Search.scss
  lib/ActivityStream.jsm
  lib/PlacesFeed.jsm
  test/browser/browser_as_render.js
  test/unit/common/Reducers.test.js
  test/unit/content-src/components/Search.test.jsx
  test/unit/lib/PlacesFeed.test.js
Labels: PR / R+ with nits

#4623 Fix Bug 1510551-Align checkbox with EOY and Newsletter snippet strings
  content-src/asrouter/templates/EOYSnippet/_EOYSnippet.scss
  content-src/asrouter/templates/SubmitFormSnippet/_SubmitFormSnippet.scss
Labels: Uplift Needed

#4626 Fix Bug 1510553 - [RTL] Dot character is wrongly hyperlinked with the…
  lib/SnippetsTestMessageProvider.jsm
Labels: Uplift Needed
