Repository mozilla/activity-stream, pull requests merged in 2018-06, with the labels that each got.

#4180 Fix Bug 1465818 - Add semver-based version and information about allowed tags
  system-addon/content-src/asrouter/schemas/message-format.md
  system-addon/content-src/asrouter/templates/SimpleSnippet/SimpleSnippet.schema.json
Labels: PR / R+

#4193 (nobug) remove unused var(--newtab-text-tertiary-color)
  system-addon/content-src/styles/_theme.scss
Labels: PR / Needs review

#4191 Fix Bug 1466608 - increase highlight title font size to 12px
  system-addon/content-src/components/Card/_Card.scss
Labels: PR / Needs review

#4192 Bug 1464126 - Implement the rest of simple template vars in AS Router
  system-addon/content-src/asrouter/components/Button/Button.jsx
  system-addon/content-src/asrouter/components/Button/_Button.scss
  system-addon/content-src/asrouter/templates/SimpleSnippet/SimpleSnippet.jsx
  system-addon/content-src/asrouter/templates/SimpleSnippet/SimpleSnippet.schema.json
  system-addon/content-src/asrouter/templates/SimpleSnippet/_SimpleSnippet.scss
Labels: PR / R+

#4195 chore(changelog): Remove file that was mostly used for test pilot add-on
  CHANGELOG.md
Labels: PR / Needs review

#4197 Fix Bug 1467449 - ASRouter sets bundle to null
  lib/ASRouter.jsm
  test/unit/asrouter/ASRouter.test.js
Labels: PR / R+

#4162 Fix Bug 1457233 - Allow AS router message content to include subset of HTML
  content-src/asrouter/asrouter-content.jsx
  content-src/asrouter/templates/SimpleSnippet/SimpleSnippet.jsx
  content-src/asrouter/templates/SimpleSnippet/SimpleSnippet.schema.json
  karma.mc.config.js
  package-lock.json
  package.json
  webpack.prerender.config.js
  webpack.system-addon.config.js
Labels: PR / R+

#4198 Bug 1467485 - Missing screenshots for TopSiteLink components
  content-src/components/Card/Card.jsx
  content-src/components/TopSites/TopSite.jsx
  content-src/lib/screenshot-utils.js
  test/unit/content-src/components/Card.test.jsx
  test/unit/content-src/components/TopSites.test.jsx
  test/unit/content-src/lib/init-store.test.js
  test/unit/content-src/lib/screenshot-utils.test.js
Labels: PR / R+ with nits

#4199 Followup to Bug 1463381 - fix history icon fill color (compact cards)
  content-src/components/Card/_Card.scss
  content-src/styles/_variables.scss
Labels: PR / Needs review

#4200 Various Visual Edits
  content-src/components/StartupOverlay/StartupOverlay.jsx
  content-src/components/StartupOverlay/_StartupOverlay.scss
  locales/en-US/strings.properties
Labels: PR / R+

#4196 Fix Bug 1457233 - Use custom metric attributes for links
  content-src/asrouter/asrouter-content.jsx
  content-src/asrouter/templates/SimpleSnippet/SimpleSnippet.schema.json
  test/unit/asrouter/asrouter-content.test.jsx
Labels: PR / R+ with nits

#4205 Followup Bug 1464548 - Restore eslint no-undef by upgrading to eslint-plugin-mozilla 0.14.0
  .eslintrc.js
  package-lock.json
  package.json
Labels: PR / Needs review

#4206 chore(fix): Fix media query to use px
  content-src/components/StartupOverlay/_StartupOverlay.scss
Labels: PR / Needs review

#4207 chore(styles): More followup max-width media query fix with px
  content-src/components/StartupOverlay/_StartupOverlay.scss
Labels: PR / Needs review

#4208 chore(tests): Follow up to bug 1465553 fix failing mochitests
  test/functional/mochitest/browser_asrouter_targeting.js
Labels: PR / R+

#4204 Bug 1458658 - Unblock sites that are added
  lib/TopSitesFeed.jsm
  test/unit/lib/TopSitesFeed.test.js
Labels: PR / Needs review

#4201 Fix Bug 1469823 - Listen for PLACES_LINK_DELETED actions and update Topsites
  lib/TopSitesFeed.jsm
  test/unit/lib/TopSitesFeed.test.js
Labels: PR / Needs review

#4211 Bug 1448359 - Enable CSP for Activity Stream
  bin/render-activity-stream-html.js
Labels: PR / Needs work

#4173 Fix Bug 1463836 - AS Router Remote Provider Message Previewing
  content-src/asrouter/asrouter-content.jsx
  content-src/components/ASRouterAdmin/ASRouterAdmin.jsx
  lib/ASRouter.jsm
  test/unit/asrouter/ASRouter.test.js
Labels: PR / R+ with nits

#4212 Fix Bug 1470170 - Implement priority system for AS Router messages
  content-src/asrouter/asrouter-content.jsx
  content-src/asrouter/schemas/provider-response.schema.json
  lib/ASRouter.jsm
  lib/ASRouterTargeting.jsm
  lib/OnboardingMessageProvider.jsm
  test/unit/asrouter/ASRouter.test.js
  test/unit/asrouter/asrouter-content.test.jsx
Labels: PR / R+ with nits

#4214 Bug 1470284 - Use a darker no-image colour for cards in dark theme
  content-src/components/Card/_Card.scss
Labels: PR / R+

#4213 Bug 1416066 - Render Activity Stream HTML files without scripts
  bin/render-activity-stream-html.js
Labels: PR / R+

#4216 chore(css): Fix various css warnings and adjust margins for about:welcome
  content-src/asrouter/components/Button/_Button.scss
  content-src/asrouter/components/ModalOverlay/_ModalOverlay.scss
  content-src/asrouter/templates/OnboardingMessage/_OnboardingMessage.scss
  content-src/asrouter/templates/SimpleSnippet/_SimpleSnippet.scss
  content-src/components/StartupOverlay/_StartupOverlay.scss
  content-src/styles/_variables.scss
Labels: PR / Needs review

#4202 Fix Bug 1468978 - Update schema to use format: uri for links
  content-src/asrouter/templates/SimpleSnippet/SimpleSnippet.schema.json
Labels: PR / R+

#4217 Backport changes from bug 1464782
  content-src/asrouter/components/SnippetBase/_SnippetBase.scss
  content-src/components/Base/_Base.scss
  content-src/components/Card/_Card.scss
  content-src/components/CollapsibleSection/_CollapsibleSection.scss
  content-src/components/ContextMenu/_ContextMenu.scss
  content-src/components/Search/_Search.scss
  content-src/components/StartupOverlay/_StartupOverlay.scss
  content-src/components/TopSites/_TopSites.scss
  content-src/styles/_variables.scss
Labels: PR / R+

#4220 (nobug): Add trigger to message spec
  content-src/asrouter/schemas/message-format.md
Labels: PR / R+

#4222 Fix Bug 1471375 - Catch IndexedDB permafail
  lib/Store.jsm
  test/unit/lib/Store.test.js
Labels: PR / Needs review

#4221 Backport Bug 1340498 - Remove onVisits from PlacesFeed
  lib/PlacesFeed.jsm
  test/unit/lib/PlacesFeed.test.js
Labels: PR / Needs review

#4223 Fix Bug 1472297 - Hide the existing onboarding button for users in the new simplified onboarding experience cohort
  content-src/components/Base/Base.jsx
  content-src/styles/_activity-stream.scss
Labels: PR / R+
