Repository mozilla/activity-stream, pull requests merged in 2019-07, with the labels that each got.

#5139 Bug 1556895 - Convert first run strings in about:welcome and startup overlay to use fluent
  .eslintrc.js
  bin/bug_1556895_newtab.py
  content-src/asrouter/templates/StartupOverlay/StartupOverlay.jsx
  content-src/asrouter/templates/Trailhead/Trailhead.jsx
  lib/OnboardingMessageProvider.jsm
  locales-src/en-US/strings.properties
  locales-src/onboarding.ftl
  test/unit/asrouter/templates/Trailhead.test.jsx
Labels: PR / Needs review

#5144 Bug 1561208 - Clean up react-intl usage (shallowWithIntl, mountWithIntl, injectIntl, addLocaleData, IntlProvider)
  content-src/asrouter/asrouter-content.jsx
  content-src/components/Base/Base.jsx
  content-src/components/Card/Card.jsx
  content-src/components/DiscoveryStreamComponents/DSCard/DSCard.jsx
  content-src/components/DiscoveryStreamComponents/DSLinkMenu/DSLinkMenu.jsx
  content-src/components/DiscoveryStreamComponents/Hero/Hero.jsx
  content-src/components/DiscoveryStreamComponents/List/List.jsx
  content-src/components/TopSites/TopSite.jsx
  content-src/components/TopSites/TopSites.jsx
  docs/v2-system-addon/unit_testing_guide.md
  test/unit/asrouter/asrouter-content.test.jsx
  test/unit/content-src/components/Card.test.jsx
  test/unit/content-src/components/ComponentPerfTimer.test.jsx
  test/unit/content-src/components/DiscoveryStreamBase.test.jsx
  test/unit/content-src/components/DiscoveryStreamComponents/CardGrid.test.jsx
  test/unit/content-src/components/DiscoveryStreamComponents/DSCard.test.jsx
  test/unit/content-src/components/DiscoveryStreamComponents/DSEmptyState.test.jsx
  test/unit/content-src/components/DiscoveryStreamComponents/DSLinkMenu.test.jsx
  test/unit/content-src/components/DiscoveryStreamComponents/DSMessage.test.jsx
  test/unit/content-src/components/DiscoveryStreamComponents/Highlights.test.jsx
  test/unit/content-src/components/DiscoveryStreamComponents/HorizontalRule.test.jsx
  test/unit/content-src/components/DiscoveryStreamComponents/Navigation.test.jsx
  test/unit/content-src/components/DiscoveryStreamComponents/SectionTitle.test.jsx
  test/unit/content-src/components/DiscoveryStreamComponents/TopSites.test.jsx
  test/unit/content-src/components/MoreRecommendations.test.jsx
  test/unit/content-src/components/ReturnToAMO.test.jsx
  test/unit/content-src/components/Search.test.jsx
  test/unit/content-src/components/Sections.test.jsx
  test/unit/content-src/components/StartupOverlay.test.jsx
  test/unit/content-src/components/TopSites.test.jsx
  test/unit/content-src/components/Topics.test.jsx
  test/unit/utils.js
Labels: PR / R+ with nits

#5147 (no bug) - Fixing browser.ini to fix mochitests logging fluent ReferenceErrors
  test/browser/browser.ini
Labels: PR / Needs review

#5149 Bug 1563127 - Fixing invalid JSON from manual string injection
  content-src/components/Card/Card.jsx
  content-src/components/DiscoveryStreamComponents/DSLinkMenu/DSLinkMenu.jsx
  content-src/components/TopSites/TopSite.jsx
  test/unit/content-src/components/Card.test.jsx
  test/unit/content-src/components/DiscoveryStreamComponents/DSLinkMenu.test.jsx
  test/unit/content-src/components/TopSites.test.jsx
Labels: PR / Needs review

#5111 Bug 1558312 - Optimistic loading for ds images
  content-src/components/DiscoveryStreamComponents/DSImage/DSImage.jsx
Labels: PR / Needs review

#5140 (nobug) - Add mochitest for ReturnToAMO component
  lib/ASRouter.jsm
  lib/OnboardingMessageProvider.jsm
  test/browser/browser.ini
  test/browser/browser_onboarding_rtamo.js
Labels: PR / R+

#4931 (nobug) - Add basic discovery stream rendering mochitest
  lib/ActivityStream.jsm
  test/browser/browser.ini
  test/browser/browser_discovery_render.js
Labels: PR / In progress don't review yet, PR / On hold for now, PR / R+

#5145 Bug 1562954 - fixing link colour
  content-src/components/DiscoveryStreamComponents/Navigation/_Navigation.scss
Labels: PR / Needs review

#5152 Bug 1559548 - Dismissing a download highlight makes it go away and reappear
  lib/DownloadsManager.jsm
  test/unit/lib/DownloadsManager.test.js
Labels: PR / Needs review

#5157 Bug 1562894 - Patched out focus behaviour on ContextMenu
  content-src/components/ContextMenu/ContextMenu.jsx
Labels: PR / Needs review

#5155 Bug 1561660 - Tweaked CSS for welcome modal on smaller resolutions
  content-src/asrouter/components/ModalOverlay/_ModalOverlay.scss
  content-src/asrouter/templates/Trailhead/_Trailhead.scss
Labels: PR / R+

#5159 Bug 1561349 - Implement message templates for What's New panel
  content-src/asrouter/templates/OnboardingMessage/WhatsNewMessage.schema.json
  lib/ASRouter.jsm
  lib/ASRouterTargeting.jsm
  lib/OnboardingMessageProvider.jsm
  lib/ToolbarPanelHub.jsm
  test/unit/asrouter/ASRouter.test.js
  test/unit/asrouter/templates/OnboardingMessage.test.jsx
  test/unit/lib/ToolbarPanelHub.test.js
Labels: PR / Needs review

#5163 Bug 1561349 - UI polish for What's New messages
  content-src/asrouter/templates/OnboardingMessage/WhatsNewMessage.schema.json
  data/content/assets/whatsnew-send-icon.png
  lib/OnboardingMessageProvider.jsm
  lib/ToolbarPanelHub.jsm
  test/unit/lib/ToolbarPanelHub.test.js
Labels: PR / R+

#5158 Bug 1557304 - “About:welcome” cards overlapping issue with the browser resized to minimum width
  content-src/asrouter/templates/Trailhead/_Trailhead.scss
Labels: PR / R+

#5166 (nobug) Fix _createDateElement() helper
  lib/ToolbarPanelHub.jsm
Labels: PR / Needs review

#5169 (nobug) - Ignore whatsnew when rendering snippets
  content-src/asrouter/asrouter-content.jsx
Labels: PR / Needs review

#5160 Bug 1564146 - add fix:eslint commit hooks for prettier + install script
  bin/bootstrap
  docs/v2-system-addon/1.GETTING_STARTED.md
  hooks/post-commit
  hooks/pre-commit
  hooks/pre-push
Labels: PR / R+ with nits

#5165 Bug 1564898 - Use UpdateManager to get the earliest Firefox version used
  content-src/asrouter/docs/targeting-attributes.md
  lib/ASRouter.jsm
  lib/ASRouterTargeting.jsm
  lib/OnboardingMessageProvider.jsm
  test/unit/asrouter/ASRouter.test.js
Labels: PR / R+

#5170 Bug 1564811 - Badge actions can define a timeout delay after which the action is executed
  content-src/asrouter/templates/OnboardingMessage/ToolbarBadgeMessage.schema.json
  lib/ASRouter.jsm
  lib/OnboardingMessageProvider.jsm
  lib/ToolbarBadgeHub.jsm
  test/unit/asrouter/ASRouter.test.js
  test/unit/lib/ToolbarBadgeHub.test.js
Labels: PR / Needs review

#5168 Bug 1564124 - Fix eslint issues for no-async-promise-executor and no-misleading-character-class
  lib/ASRouterTargeting.jsm
  lib/AboutPreferences.jsm
  lib/LinksCache.jsm
  lib/PersistentCache.jsm
  lib/Tokenize.jsm
  test/unit/asrouter/ASRouterTargeting.test.js
  test/unit/lib/AboutPreferences.test.js
  test/unit/lib/LinksCache.test.js
  test/unit/lib/PersistentCache.test.js
Labels: PR / R+

#5171 (nobug) Move the What's New and Badge test messages to PanelTestProvider.jsm
  lib/OnboardingMessageProvider.jsm
  lib/PanelTestProvider.jsm
  test/unit/asrouter/PanelTestProvider.test.js
  test/unit/lib/ToolbarBadgeHub.test.js
  test/unit/lib/ToolbarPanelHub.test.js
Labels: PR / Needs review

#5180 (nobug) - Restore the default icon style after removing the badge
  lib/ToolbarBadgeHub.jsm
  test/unit/lib/ToolbarBadgeHub.test.js
Labels: PR / R+

#5183 Bug 1564568 - Hide What's New toolbar button after the user dismisses the panel
  lib/ToolbarPanelHub.jsm
  test/unit/lib/ToolbarPanelHub.test.js
Labels: PR / R+

#5182 Update depedencies
  package-lock.json
  package.json
Labels: PR / Needs review

#5179 Bug 1556862 - Localizing empty discovery stream messages
  .eslintrc.js
  content-src/components/DiscoveryStreamComponents/DSEmptyState/DSEmptyState.jsx
  locales-src/newtab.ftl
  test/unit/content-src/components/DiscoveryStreamComponents/DSEmptyState.test.jsx
Labels: PR / Needs review

#5174 Bug 1565088 - Add AUTO-GENERATED message to top of bundle.js to satisfy license lint
  webpack.system-addon.config.js
Labels: PR / R+

#5177 Bug 1562928 - Image source changes properly refresh card.
  content-src/components/DiscoveryStreamComponents/CardGrid/CardGrid.jsx
  content-src/components/DiscoveryStreamComponents/Hero/Hero.jsx
  content-src/components/DiscoveryStreamComponents/List/List.jsx
Labels: PR / R+

#5161 Bug 1559383 - Added keyboardAccess prop to all components with contex…
  content-src/components/Card/Card.jsx
  content-src/components/CollapsibleSection/CollapsibleSection.jsx
  content-src/components/ContextMenu/ContextMenu.jsx
  content-src/components/ContextMenu/ContextMenuButton.jsx
  content-src/components/DiscoveryStreamComponents/DSLinkMenu/DSLinkMenu.jsx
  content-src/components/LinkMenu/LinkMenu.jsx
  content-src/components/SectionMenu/SectionMenu.jsx
  content-src/components/TopSites/TopSite.jsx
  test/unit/content-src/components/Card.test.jsx
  test/unit/content-src/components/ContextMenu.test.jsx
  test/unit/content-src/components/DiscoveryStreamComponents/DSLinkMenu.test.jsx
  test/unit/content-src/components/TopSites.test.jsx
Labels: PR / R+

#5162 Bug 1563741 - Keeping body scroll static, but welcome modal centered …
  content-src/asrouter/components/ModalOverlay/ModalOverlay.jsx
  content-src/asrouter/components/ModalOverlay/_ModalOverlay.scss
  content-src/asrouter/templates/Trailhead/_Trailhead.scss
  test/unit/asrouter/ModalOverlay.test.jsx
Labels: PR / R+

#5176 Bug 1561554 - Add telemetry events for notification badges
  docs/v2-system-addon/data_events.md
  lib/ASRouter.jsm
  lib/ToolbarBadgeHub.jsm
  test/unit/asrouter/ASRouter.test.js
  test/unit/lib/ToolbarBadgeHub.test.js
Labels: PR / Awaiting data review, PR / R+

#5191 Bug 1566372 - Listen for pref changes as a way to trigger notifications
  lib/ToolbarBadgeHub.jsm
  lib/ToolbarPanelHub.jsm
  test/unit/lib/ToolbarBadgeHub.test.js
  test/unit/lib/ToolbarPanelHub.test.js
Labels: PR / Needs review

#5190 Bug 1566460 - Don't show the panel if there are no messages
  lib/ASRouter.jsm
  lib/ToolbarPanelHub.jsm
  test/unit/asrouter/ASRouter.test.js
  test/unit/lib/ToolbarPanelHub.test.js
Labels: PR / R+

#5186 Bug 1554961 - Adding a Top Site/Search Engine in a collapsed section is buggy.
  content-src/components/SectionMenu/SectionMenu.jsx
  test/unit/content-src/components/SectionMenu.test.jsx
Labels: PR / R+

#5187 Bug 1561625 - Add telemetry events for What's New panel
  docs/v2-system-addon/data_events.md
  lib/ASRouter.jsm
  lib/ToolbarPanelHub.jsm
  test/unit/asrouter/ASRouter.test.js
  test/unit/lib/ToolbarPanelHub.test.js
Labels: PR / R+

#5198 (nobug) - Fix What's New badge targeting expression
  lib/PanelTestProvider.jsm
Labels: PR / R+

#5193 Bug 1547337 - Accessibility Audit
  content-src/components/CollapsibleSection/CollapsibleSection.jsx
  content-src/components/ContextMenu/ContextMenu.jsx
  content-src/components/ContextMenu/ContextMenuButton.jsx
  locales-src/newtab.ftl
  test/unit/content-src/components/CollapsibleSection.test.jsx
  test/unit/content-src/components/ContextMenu.test.jsx
Labels: Accessibility, PR / Needs review

#5209 (nobug) - Add mochitest for toolbar badging behavior
  test/browser/browser.ini
  test/browser/browser_asrouter_bookmarkpanel.js
  test/browser/browser_asrouter_toolbarbadge.js
Labels: PR / R+

#5215 (nobug) - Adding documentation for setting update channel, geo, and locale
  docs/v2-system-addon/1.GETTING_STARTED.md
  docs/v2-system-addon/geo_locale.md
Labels: PR / R+ with nits
