Repository mozilla/activity-stream, pull requests merged in 2019-10, with the labels that each got.

#5327 (nobug) - Remove earliestFirefoxVersion attribute for causing perform…
  content-src/asrouter/docs/targeting-attributes.md
  lib/ASRouterTargeting.jsm
Labels: PR / R+

#5323 Bug 1582242 - Modal should not close when clicked outside the dialog
  content-src/asrouter/components/ModalOverlay/ModalOverlay.jsx
  content-src/asrouter/components/ModalOverlay/_ModalOverlay.scss
  test/unit/asrouter/ModalOverlay.test.jsx
Labels: PR / R+

#5331 Bug 1584642 - Control engagement label visibility with a pref
  content-src/components/DiscoveryStreamBase/DiscoveryStreamBase.jsx
  content-src/components/DiscoveryStreamComponents/CardGrid/CardGrid.jsx
  content-src/components/DiscoveryStreamComponents/DSCard/DSCard.jsx
  content-src/components/DiscoveryStreamComponents/DSContextFooter/DSContextFooter.jsx
  lib/ActivityStream.jsm
  test/unit/content-src/components/DiscoveryStreamComponents/DSContextFooter.test.jsx
Labels: PR / R+ with nits

#5336 Bug 1585686 - UnicodeEncodeError: 'ascii' codec can't encode character '\u2716' in position 9: ordinal not in range(128)
  mochitest.sh
Labels: PR / Needs review

#5304 Bug 1578528 - Support new join messaging in about:welcome
  content-src/asrouter/templates/Trailhead/_Trailhead.scss
  data/content/assets/trailhead/benefit-sync.png
  lib/OnboardingMessageProvider.jsm
  locales-src/onboarding.ftl
  test/browser/browser_aboutwelcome.js
  test/unit/asrouter/ASRouterTargeting.test.js
Labels: PR / R+ with nits

#5325 Bug 1578575 - Ad Privacy Info
  .eslintrc.js
  bin/render-activity-stream-html.js
  common/Actions.jsm
  common/Reducers.jsm
  content-src/asrouter/components/ModalOverlay/_ModalOverlay.scss
  content-src/components/DiscoveryStreamBase/DiscoveryStreamBase.jsx
  content-src/components/DiscoveryStreamComponents/DSLinkMenu/DSLinkMenu.jsx
  content-src/components/DiscoveryStreamComponents/DSPrivacyModal/DSPrivacyModal.jsx
  content-src/components/DiscoveryStreamComponents/DSPrivacyModal/_DSPrivacyModal.scss
  content-src/lib/link-menu-options.js
  content-src/styles/_activity-stream.scss
  locales-src/newtab.ftl
  test/unit/common/Reducers.test.js
  test/unit/content-src/components/DiscoveryStreamComponents/DSLinkMenu.test.jsx
  test/unit/content-src/components/DiscoveryStreamComponents/DSPrivacyModal.test.jsx
  test/unit/content-src/components/LinkMenu.test.jsx
Labels: PR / Needs review

#5337 Bug 1566505 - Update panel content when messages change
  lib/ToolbarPanelHub.jsm
  test/unit/lib/ToolbarPanelHub.test.js
Labels: PR / R+

#5339 (nobug) - Fixing a few items in telemetry debugging docs
  content-src/asrouter/docs/debugging-docs.md
Labels: PR / Needs review

#5338 Bug 1578579 - Add telemetry for ad privacy info
  content-src/components/DiscoveryStreamComponents/DSPrivacyModal/DSPrivacyModal.jsx
  content-src/lib/link-menu-options.js
  docs/v2-system-addon/data_events.md
  test/schemas/pings.js
  test/unit/content-src/components/DiscoveryStreamComponents/DSPrivacyModal.test.jsx
Labels: PR / Needs review

#5324 Bug 1550720 - Expose FxA services associated with profile to targetin…
  content-src/asrouter/docs/targeting-attributes.md
  lib/ASRouterTargeting.jsm
Labels: PR / Needs review

#5315 Bug 1579966 - Campaign id blocks
  content-src/components/DiscoveryStreamComponents/DSCard/DSCard.jsx
  content-src/components/DiscoveryStreamComponents/DSLinkMenu/DSLinkMenu.jsx
  content-src/components/DiscoveryStreamComponents/Hero/Hero.jsx
  content-src/components/DiscoveryStreamComponents/List/List.jsx
  content-src/lib/link-menu-options.js
  lib/ActivityStream.jsm
  lib/DiscoveryStreamFeed.jsm
  lib/PlacesFeed.jsm
  test/unit/content-src/components/DiscoveryStreamComponents/DSDismiss.test.jsx
  test/unit/lib/DiscoveryStreamFeed.test.js
Labels: PR / Needs review

#5321 Bug 1569696 - CFR: recommend send tab on popular recipe sites
  common/Actions.jsm
  lib/ASRouter.jsm
  lib/ASRouterTriggerListeners.jsm
  lib/PanelTestProvider.jsm
  test/browser/browser_asrouter_trigger_listeners.js
  test/unit/asrouter/ASRouter.test.js
  test/unit/asrouter/ASRouterTriggerListeners.test.js
  test/unit/asrouter/PanelTestProvider.test.js
  test/unit/unit-entry.js
Labels: PR / R+

#5340 Bug 1584625 - browser_aboutwelcome.js mochitest fails when run twice
  test/browser/browser_onboarding_rtamo.js
Labels: PR / Needs review

#5344 Bug 1376637 - Export platform name to targeting attributes
  content-src/asrouter/docs/targeting-attributes.md
  lib/ASRouterTargeting.jsm
  test/browser/browser_asrouter_targeting.js
Labels: PR / R+

#5345 Bug 1585387 - The font of the hyperlink and button label from the sponsored content cards is wrongly set to "Regular" instead of "Semibold"
  content-src/components/DiscoveryStreamComponents/DSCard/_DSCard.scss
Labels: PR / Needs review

#5307 Bug 1579251 - Full page about:welcome variant
  .eslintrc.js
  common/Actions.jsm
  content-src/asrouter/asrouter-content.jsx
  content-src/asrouter/components/FxASignupForm/FxASignupForm.jsx
  content-src/asrouter/components/FxASignupForm/_FxASignupForm.scss
  content-src/asrouter/templates/FirstRun/FirstRun.jsx
  content-src/asrouter/templates/FirstRun/Interrupt.jsx
  content-src/asrouter/templates/FullPageInterrupt/FullPageInterrupt.jsx
  content-src/asrouter/templates/FullPageInterrupt/_FullPageInterrupt.scss
  content-src/asrouter/templates/Trailhead/Trailhead.jsx
  content-src/asrouter/templates/Trailhead/_Trailhead.scss
  content-src/styles/_activity-stream.scss
  content-src/styles/_variables.scss
  data/content/assets/trailhead/firefox-systems.png
  docs/v2-system-addon/data_events.md
  lib/OnboardingMessageProvider.jsm
  locales-src/onboarding.ftl
  test/browser/browser_aboutwelcome.js
  test/schemas/pings.js
  test/unit/asrouter/templates/FullPageInterrupt.test.jsx
  test/unit/asrouter/templates/FxASignupForm.test.jsx
  test/unit/asrouter/templates/Interrupt.test.jsx
  test/unit/asrouter/templates/Trailhead.test.jsx
Labels: PR / R+ with nits

#5326 Bug 1576510 - Use aria-labelledby to add additional description information to badged toolbar buttons
  content-src/asrouter/templates/OnboardingMessage/ToolbarBadgeMessage.schema.json
  lib/OnboardingMessageProvider.jsm
  lib/ToolbarBadgeHub.jsm
  locales-src/asrouter.ftl
  test/unit/lib/ToolbarBadgeHub.test.js
Labels: PR / Needs review

#5348 Bug 1587926 - Idle callback with dsimage
  content-src/components/DiscoveryStreamComponents/DSImage/DSImage.jsx
  test/unit/content-src/components/DiscoveryStreamComponents/DSImage.test.jsx
Labels: PR / Needs review

#5351 Bug 1577655 - Removing unused margin override
  content-src/components/DiscoveryStreamComponents/DSTextPromo/_DSTextPromo.scss
Labels: PR / Needs review

#5314 Fix Bug 1582002 - make sync optional in the about:welcome signin flow
  content-src/asrouter/components/FxASignupForm/FxASignupForm.jsx
  content-src/asrouter/templates/FXASignupSnippet/FXASignupSnippet.jsx
  content-src/asrouter/templates/FXASignupSnippet/FXASignupSnippet.schema.json
  content-src/asrouter/templates/SendToDeviceSnippet/SendToDeviceSnippet.schema.json
Labels: PR / R+

#5262 Bug 1574549 - Small bug with pref change, not critical
  lib/DiscoveryStreamFeed.jsm
Labels: PR / R+ with nits

#5353 Bug 1589117 - Privacy info link menu changes
  content-src/components/DiscoveryStreamComponents/DSLinkMenu/DSLinkMenu.jsx
  test/unit/content-src/components/DiscoveryStreamComponents/DSLinkMenu.test.jsx
Labels: PR / Needs review

#5354 Bug 1583839 - Putting active state back on cards
  content-src/components/DiscoveryStreamComponents/DSCard/_DSCard.scss
Labels: PR / Needs review

#5330 Bug 1583262 - Messaging router custom code to support about:welcome variants in 71
  lib/ASRouter.jsm
Labels: PR / R+

#5355 Bug 1588524 - The 'What's New' toolbar button is redisplayed after br…
  lib/ToolbarBadgeHub.jsm
  test/unit/lib/ToolbarBadgeHub.test.js
Labels: PR / R+

#5347 Bug 1576510 - Redundant impression sent when clicking on 'show protec…
  lib/ToolbarPanelHub.jsm
  test/unit/lib/ToolbarPanelHub.test.js
Labels: PR / R+

#5360 (nobug) - Fixing mixin typo
  content-src/components/DiscoveryStreamComponents/CardGrid/_CardGrid.scss
  content-src/components/DiscoveryStreamComponents/DSCard/_DSCard.scss
  content-src/components/DiscoveryStreamComponents/Hero/_Hero.scss
  content-src/components/DiscoveryStreamComponents/List/_List.scss
  content-src/styles/_mixins.scss
Labels: PR / Needs review

#5362 Bug 1589025 - Displaying privacy modal in correct position
  content-src/asrouter/templates/Trailhead/_Trailhead.scss
Labels: PR / Needs review

#5346 Bug 1585147 - Migrate AS Router telemetry to Structured Ingestion (GCP)
  content-src/asrouter/asrouter-content.jsx
  docs/v2-system-addon/data_dictionary.md
  docs/v2-system-addon/data_events.md
  lib/ASRouter.jsm
  lib/ActivityStream.jsm
  lib/TelemetryFeed.jsm
  lib/ToolbarPanelHub.jsm
  ping-centre/PingCentre.jsm
  test/schemas/pings.js
  test/unit/asrouter/ASRouter.test.js
  test/unit/lib/TelemetryFeed.test.js
  test/unit/lib/ToolbarPanelHub.test.js
  test/unit/ping-centre/PingCentre.test.js
Labels: PR / Needs review

#5357 Bug 1583845 - Fixing CTA button colors
  content-src/components/DiscoveryStreamComponents/DSCard/_DSCard.scss
Labels: PR / Needs review

#5359 Bug 1589659 - Enabling hover state for privacy modal
  content-src/components/DiscoveryStreamComponents/DSPrivacyModal/DSPrivacyModal.jsx
  content-src/components/DiscoveryStreamComponents/DSPrivacyModal/_DSPrivacyModal.scss
Labels: PR / Needs review
