Repository mozilla/activity-stream, pull requests merged in 2019-01, with the labels that each got.

#4589 Fix Bug 1511165 - about:welcome addon card on windows says "addon name"
  lib/ASRouter.jsm
  lib/OnboardingMessageProvider.jsm
  test/unit/asrouter/ASRouter.test.js
  test/unit/asrouter/templates/OnboardingMessage.test.jsx
  test/unit/unit-entry.js
Labels: PR / R+ with nits

#4630 no bug - Stubbing out Discovery Stream components.
  content-src/components/DiscoveryStreamBase/DiscoveryStreamBase.jsx
  content-src/components/DiscoveryStreamBase/_DiscoveryStreamBase.scss
  content-src/components/DiscoveryStreamComponents/CardGrid/CardGrid.jsx
  content-src/components/DiscoveryStreamComponents/CardGrid/_CardGrid.scss
  content-src/components/DiscoveryStreamComponents/Hero/Hero.jsx
  content-src/components/DiscoveryStreamComponents/Hero/_Hero.scss
  content-src/components/DiscoveryStreamComponents/HorizontalRule/HorizontalRule.jsx
  content-src/components/DiscoveryStreamComponents/HorizontalRule/_HorizontalRule.scss
  content-src/components/DiscoveryStreamComponents/List/List.jsx
  content-src/components/DiscoveryStreamComponents/List/_List.scss
  content-src/components/DiscoveryStreamComponents/SectionTitle/SectionTitle.jsx
  content-src/components/DiscoveryStreamComponents/SectionTitle/_SectionTitle.scss
  content-src/components/DiscoveryStreamComponents/TopSites/TopSites.jsx
  content-src/components/DiscoveryStreamComponents/TopSites/_TopSites.scss
  content-src/styles/_activity-stream.scss
  lib/ActivityStream.jsm
Labels: PR / R+

#4633 Fix Bug 1517342 - Taskcluster fails because of missing env var
  mochitest.sh
Labels: PR / Needs review

#4634 Fix Bug 1515026 - Send telemetry ping for dismiss events
  content-src/asrouter/components/SnippetBase/SnippetBase.jsx
  test/unit/asrouter/templates/SubmitFormSnippet.test.jsx
Labels: PR / R+

#4636 Bug 1517596 - Add basic discoverystream devtools
  common/Actions.jsm
  common/Reducers.jsm
  content-src/components/ASRouterAdmin/ASRouterAdmin.jsx
  content-src/components/ASRouterAdmin/ASRouterAdmin.scss
  content-src/components/Base/Base.jsx
  lib/DiscoveryStreamFeed.jsm
  test/unit/common/Reducers.test.js
  test/unit/lib/DiscoveryStreamFeed.test.js
Labels: PR / R+

#4639 fix(styles): Remove title alignment that affect other sections for now
  content-src/components/DiscoveryStreamComponents/SectionTitle/_SectionTitle.scss
Labels: PR / R+

#4635 Fix Bug 1515663 - Block FxA snippet on form submit
  content-src/asrouter/templates/SubmitFormSnippet/SubmitFormSnippet.jsx
  test/unit/asrouter/templates/SubmitFormSnippet.test.jsx
Labels: PR / R+ with nits

#4638 Bug 1517713 - [RTL] Localized "Search the Web" string is LTR'd
  content-src/components/Search/_Search.scss
Labels: PR / Needs review

#4627 Fix Bug 1515411 - Disable Return to AMO for 65 Beta and Release
  lib/ASRouter.jsm
  lib/ASRouterTargeting.jsm
  lib/ActivityStream.jsm
  lib/OnboardingMessageProvider.jsm
  test/unit/asrouter/ASRouter.test.js
  test/unit/asrouter/ASRouterTargeting.test.js
  test/unit/content-src/components/ReturnToAMO.test.jsx
  test/unit/content-src/components/StartupOverlay.test.jsx
  test/unit/unit-entry.js
Labels: PR / R+

#4640 Fix Bug 1517745 - Remove arrow from search bar when hand-off enabled
  content-src/components/Search/Search.jsx
  content-src/components/Search/_Search.scss
Labels: PR / Needs review

#4631 Fix Bug 1517327 - Search telemetry failures not caught by taskcluster
  mochitest.sh
Labels: PR / R+

#4637 Fixes bug 1518171 - Adding feeds.
  common/Actions.jsm
  common/Reducers.jsm
  content-src/components/ASRouterAdmin/ASRouterAdmin.jsx
  content-src/components/ASRouterAdmin/ASRouterAdmin.scss
  content-src/components/DiscoveryStreamBase/DiscoveryStreamBase.jsx
  content-src/components/DiscoveryStreamComponents/CardGrid/CardGrid.jsx
  content-src/components/DiscoveryStreamComponents/Hero/Hero.jsx
  content-src/components/DiscoveryStreamComponents/List/List.jsx
  lib/DiscoveryStreamFeed.jsm
  test/unit/lib/DiscoveryStreamFeed.test.js
Labels: PR / R+ with nits

#4641 (nobug) - Prevent duplicate ids in the messageBlockList
  lib/ASRouter.jsm
  test/unit/asrouter/ASRouter.test.js
  test/unit/asrouter/MessageLoaderUtils.test.js
Labels: PR / R+

#4647 Bug 1517525 - Spelling issue for Reducers.test.js initial state
  test/unit/common/Reducers.test.js
Labels: PR / R+

#4645 Fixes bug 1514025 - Create a top sites section component for Activity…
  content-src/components/DiscoveryStreamBase/DiscoveryStreamBase.jsx
  content-src/components/DiscoveryStreamBase/_DiscoveryStreamBase.scss
  content-src/components/DiscoveryStreamComponents/SectionTitle/SectionTitle.jsx
  content-src/components/DiscoveryStreamComponents/SectionTitle/_SectionTitle.scss
  content-src/components/DiscoveryStreamComponents/TopSites/TopSites.jsx
  content-src/components/DiscoveryStreamComponents/TopSites/_TopSites.scss
  test/unit/content-src/components/DiscoveryStreamComponents/TopSites.test.jsx
Labels: PR / R+ with nits

#4644 Hero Component (WIP)
  content-src/components/DiscoveryStreamBase/DiscoveryStreamBase.jsx
  content-src/components/DiscoveryStreamBase/_DiscoveryStreamBase.scss
  content-src/components/DiscoveryStreamComponents/DSCard/DSCard.jsx
  content-src/components/DiscoveryStreamComponents/DSCard/_DSCard.scss
  content-src/components/DiscoveryStreamComponents/Hero/Hero.jsx
  content-src/components/DiscoveryStreamComponents/Hero/_Hero.scss
  content-src/styles/_activity-stream.scss
Labels: PR / Needs review

#4625 Bug 1513882 - [Return to AMO] Show add-on notification icon in ur…
  lib/ASRouter.jsm
  test/unit/asrouter/MessageLoaderUtils.test.js
Labels: PR / R+

#4649 Fixes bug 1518921 - Discovery Stream Spocs
  common/Actions.jsm
  common/Reducers.jsm
  lib/DiscoveryStreamFeed.jsm
  test/unit/common/Reducers.test.js
  test/unit/lib/DiscoveryStreamFeed.test.js
Labels: PR / Needs review

#4642 Bug 1515078 - Add opt out UX in about:preferences for Pocket Newtab
  lib/AboutPreferences.jsm
  locales-src/en-US/strings.properties
  test/unit/lib/AboutPreferences.test.js
Labels: PR / R+ with nits

#4580 Fix Bug 1509755 - Wait for browser initialization to finish before adding CFR trigger listeners
  lib/ASRouter.jsm
  lib/ASRouterTriggerListeners.jsm
  test/unit/asrouter/ASRouterTriggerListeners.test.js
Labels: PR / R+

#4653 Bug 1514018 - Hero component refinement (WIP)
  content-src/components/DiscoveryStreamBase/DiscoveryStreamBase.jsx
  content-src/components/DiscoveryStreamComponents/DSCard/DSCard.jsx
  content-src/components/DiscoveryStreamComponents/DSCard/_DSCard.scss
  content-src/components/DiscoveryStreamComponents/Hero/Hero.jsx
  content-src/components/DiscoveryStreamComponents/Hero/_Hero.scss
Labels: PR / Needs review

#4660 Bug 1520259 - Add space for devtools fixed sidebar
  content-src/components/ASRouterAdmin/ASRouterAdmin.scss
Labels: PR / R+

#4652 bug 1519484 - Working on css overrides on topsites.
  content-src/components/DiscoveryStreamBase/_DiscoveryStreamBase.scss
  content-src/components/DiscoveryStreamComponents/TopSites/_TopSites.scss
Labels: PR / R+ with nits

#4659 Bug 1513906 - Polish ReturnToAMO screen
  content-src/asrouter/templates/ReturnToAMO/_ReturnToAMO.scss
Labels: PR / R+

#4657 (nobug) - Improve ASRouterAdmin color contrast in dark theme
  content-src/components/ASRouterAdmin/ASRouterAdmin.scss
Labels: PR / R+

#4569 Fix Bug 1507306 - Unit tests running on Firefox 54
  .travis.yml
  bin/download-firefox-travis.sh
Labels: PR / R+

#4656 Bug 1519396 - 'Force Attribution' from ASRouter for Return to AMO doe…
  lib/ASRouter.jsm
Labels: PR / R+ with nits

#4655 Bug 1514006 - Add impression wrapper for Pocket sections
  content-src/components/DiscoveryStreamBase/DiscoveryStreamBase.jsx
  content-src/components/DiscoveryStreamImpressionStats/ImpressionStats.jsx
  test/unit/content-src/components/DiscoveryStreamComponents/ImpressionStats.test.jsx
Labels: PR / R+ with nits

#4661 Bug 1514022 – Card Grid component (WIP)
  content-src/components/DiscoveryStreamBase/DiscoveryStreamBase.jsx
  content-src/components/DiscoveryStreamComponents/CardGrid/CardGrid.jsx
  content-src/components/DiscoveryStreamComponents/CardGrid/_CardGrid.scss
  content-src/components/DiscoveryStreamComponents/DSCard/DSCard.jsx
  content-src/components/DiscoveryStreamComponents/DSCard/_DSCard.scss
  content-src/components/DiscoveryStreamComponents/Hero/_Hero.scss
  content-src/styles/_activity-stream.scss
  content-src/styles/_mixins.scss
Labels: PR / R+

#4662 Bug 1514732 - Create a telemetry ping for search hand-off
  content-src/components/Search/Search.jsx
  docs/v2-system-addon/data_events.md
  test/schemas/pings.js
  test/unit/content-src/components/Search.test.jsx
Labels: PR / Awaiting data review

#4654 Bug 1519766 - standup list component for DiscoveryStream
  content-src/components/DiscoveryStreamBase/DiscoveryStreamBase.jsx
  content-src/components/DiscoveryStreamBase/_DiscoveryStreamBase.scss
  content-src/components/DiscoveryStreamComponents/List/List.jsx
  content-src/components/DiscoveryStreamComponents/List/_List.scss
  content-src/styles/_variables.scss
  test/unit/content-src/components/DiscoveryStreamComponents/List.test.jsx
Labels: PR / R+

#4664 Bug 1520514 - Add memoized selector to add feed data and spocs to layout
  content-src/components/DiscoveryStreamBase/DiscoveryStreamBase.jsx
  content-src/components/DiscoveryStreamComponents/CardGrid/CardGrid.jsx
  content-src/components/DiscoveryStreamComponents/Hero/Hero.jsx
  content-src/lib/selectLayoutRender.js
  package-lock.json
  package.json
  test/unit/content-src/lib/selectLayoutRender.test.js
Labels: PR / R+

#4650 Bug 1520449 - Do the search hand-off on keydown instead of mouse click
  common/Actions.jsm
  common/Reducers.jsm
  content-src/components/Search/Search.jsx
  content-src/components/Search/_Search.scss
  lib/PlacesFeed.jsm
  test/unit/common/Reducers.test.js
  test/unit/content-src/components/Search.test.jsx
  test/unit/lib/PlacesFeed.test.js
Labels: PR / R+

#4668 Bug 1519141 - "Esc" should make the in-content search re-appear.
  content-src/components/Search/Search.jsx
  lib/PlacesFeed.jsm
  test/unit/content-src/components/Search.test.jsx
  test/unit/lib/PlacesFeed.test.js
Labels: PR / R+

#4666 Bug 1514006 - Part 2, add CLICK pings for the Hero section
  content-src/components/DiscoveryStreamBase/DiscoveryStreamBase.jsx
  content-src/components/DiscoveryStreamComponents/CardGrid/CardGrid.jsx
  content-src/components/DiscoveryStreamComponents/DSCard/DSCard.jsx
  content-src/components/DiscoveryStreamComponents/Hero/Hero.jsx
Labels: PR / R+

#4670 roll the dice for spocs.
  content-src/lib/selectLayoutRender.js
  test/unit/content-src/lib/selectLayoutRender.test.js
Labels: PR / R+ with nits

#4673 Bug 1520662: Ensure undeterministic load order is not causing crashes
  common/Reducers.jsm
  content-src/components/DiscoveryStreamBase/DiscoveryStreamBase.jsx
  content-src/components/DiscoveryStreamComponents/List/List.jsx
  content-src/lib/selectLayoutRender.js
Labels: PR / Needs review

#4676 Bug 1520697 - Odd behavior when dragging html into contenteditable search box
  content-src/components/Search/Search.jsx
  test/unit/content-src/components/Search.test.jsx
Labels: PR / Needs review

#4674 Bug 1513311 - Allow remote custom CSS to adjust section and/or card styles
  content-src/components/DiscoveryStreamBase/DiscoveryStreamBase.jsx
  test/unit/content-src/components/DiscoveryStreamBase.test.jsx
Labels: PR / R+

#4678 Bug 1520852 – Changing property name to match new API schema
  content-src/components/DiscoveryStreamBase/DiscoveryStreamBase.jsx
  content-src/components/DiscoveryStreamComponents/CardGrid/CardGrid.jsx
  content-src/components/DiscoveryStreamComponents/Hero/Hero.jsx
Labels: PR / R+

#4679 (no bug) - Update MAX_ROWS_LIST per Pocket API specs
  content-src/components/DiscoveryStreamBase/DiscoveryStreamBase.jsx
Labels: PR / R+

#4680 bug 1520893 - Display spocs
  content-src/components/DiscoveryStreamBase/DiscoveryStreamBase.jsx
  content-src/lib/selectLayoutRender.js
Labels: PR / Needs review

#4681 Bug 1520854 - make text color in AS work again in dark theme
  content-src/components/DiscoveryStreamBase/_DiscoveryStreamBase.scss
Labels: PR / R+

#4683 NOBUG – Use `control` layout as default
  lib/ActivityStream.jsm
Labels: PR / R+

#4684 Fixing spoc prop
  content-src/components/DiscoveryStreamBase/DiscoveryStreamBase.jsx
Labels: PR / Needs review

#4672 Bug 1516034 - Use non-prerendered version of HTML for DiscoveryStream New Tab
  bin/render-activity-stream-html.js
  common/PrerenderData.jsm
  test/unit/common/PrerenderData.test.js
  test/unit/lib/PrefsFeed.test.js
Labels: PR / R+ with nits

#4685 Bug 1519775 - Make one and two-column lists work
  content-src/components/DiscoveryStreamBase/DiscoveryStreamBase.jsx
  content-src/components/DiscoveryStreamComponents/CardGrid/_CardGrid.scss
  content-src/components/DiscoveryStreamComponents/List/_List.scss
Labels: PR / R+

#4686 Bug 1521132 - Combine spoc rendering functions into selectLayoutRende…
  content-src/components/DiscoveryStreamBase/DiscoveryStreamBase.jsx
  content-src/lib/selectLayoutRender.js
  test/unit/content-src/lib/selectLayoutRender.test.js
Labels: PR / R+

#4691 Bug 1516034 Refactor to add non-prerendered comment in root tag
  bin/render-activity-stream-html.js
Labels: PR / R+

#4694 (no bug) - Fix css style regression from grid column alignment and add tests
  content-src/components/DiscoveryStreamBase/DiscoveryStreamBase.jsx
  test/browser/browser.ini
  test/browser/browser_discovery_styles.js
Labels: PR / Needs review

#4687 Bug 1520914 - AS devtools blank page fix on first discovery stream en…
  content-src/components/ASRouterAdmin/ASRouterAdmin.jsx
Labels: PR / Needs review

#4688 Bug 1519243 - Split title component into two, the new one is navigation
  content-src/components/DiscoveryStreamBase/DiscoveryStreamBase.jsx
  content-src/components/DiscoveryStreamBase/_DiscoveryStreamBase.scss
  content-src/components/DiscoveryStreamComponents/List/_List.scss
  content-src/components/DiscoveryStreamComponents/Navigation/Navigation.jsx
  content-src/components/DiscoveryStreamComponents/Navigation/_Navigation.scss
  content-src/components/DiscoveryStreamComponents/SectionTitle/SectionTitle.jsx
  content-src/components/DiscoveryStreamComponents/SectionTitle/_SectionTitle.scss
  content-src/styles/_activity-stream.scss
Labels: PR / Needs review

#4690 chore(List) - remove unnecessary comparison
  content-src/components/DiscoveryStreamBase/DiscoveryStreamBase.jsx
Labels: PR / R+

#4696 Bug 1520898 - Display spoc context.
  content-src/components/DiscoveryStreamComponents/CardGrid/CardGrid.jsx
  content-src/components/DiscoveryStreamComponents/DSCard/DSCard.jsx
  content-src/components/DiscoveryStreamComponents/DSCard/_DSCard.scss
  content-src/components/DiscoveryStreamComponents/Hero/Hero.jsx
  content-src/components/DiscoveryStreamComponents/Hero/_Hero.scss
Labels: PR / Needs review

#4682 Bug 1520925 - Further refine CardGrid (WIP)
  content-src/components/DiscoveryStreamComponents/CardGrid/CardGrid.jsx
  content-src/components/DiscoveryStreamComponents/CardGrid/_CardGrid.scss
  content-src/components/DiscoveryStreamComponents/DSCard/_DSCard.scss
Labels: PR / R+ with nits

#4700 NOBUG – use `excerpt` not `title` for excerpt data
  content-src/components/DiscoveryStreamComponents/CardGrid/CardGrid.jsx
Labels: PR / Needs review

#4693 Bug 1521615 - Dry out header css for reusage usage with top sites.
  content-src/components/DiscoveryStreamBase/DiscoveryStreamBase.jsx
  content-src/components/DiscoveryStreamBase/_DiscoveryStreamBase.scss
  content-src/components/DiscoveryStreamComponents/Hero/_Hero.scss
  content-src/components/DiscoveryStreamComponents/List/List.jsx
  content-src/components/DiscoveryStreamComponents/List/_List.scss
  content-src/components/DiscoveryStreamComponents/TopSites/TopSites.jsx
Labels: PR / R+

#4699 Bug 1519774 - implement lists without images
  content-src/components/DiscoveryStreamBase/DiscoveryStreamBase.jsx
  content-src/components/DiscoveryStreamComponents/List/List.jsx
  content-src/components/DiscoveryStreamComponents/List/_List.scss
Labels: PR / R+

#4702 Bug 1521891 - portrait images in list items should correctly cover 72x72 box
  content-src/components/DiscoveryStreamComponents/List/_List.scss
Labels: PR / R+

#4701 Bug 1520888 - Ensure spocs don't load over a rec.
  common/Reducers.jsm
  content-src/components/DiscoveryStreamBase/DiscoveryStreamBase.jsx
  lib/DiscoveryStreamFeed.jsm
  test/unit/common/Reducers.test.js
Labels: PR / R+

#4703 Bug 1521888 - add padding between ds-list-item-text and the image to the right, as per spec
  content-src/components/DiscoveryStreamComponents/List/_List.scss
Labels: PR / R+

#4705 (nobug) changing default endpoint to `basic`
  lib/ActivityStream.jsm
Labels: PR / R+ with nits

#4704 Bug 1521643 – Item title highlights when hovering anywhere within Hero section
  content-src/components/DiscoveryStreamComponents/Hero/_Hero.scss
Labels: PR / R+

#4706 Bug 1521886 - update thicknesss/color of ds-list horizontal rules
  content-src/components/DiscoveryStreamComponents/List/_List.scss
  content-src/styles/_variables.scss
Labels: PR / R+

#4697 Bug 1521757 - Port PBM search hand-off implementation changes to Activity Stream
  common/Actions.jsm
  common/Reducers.jsm
  content-src/components/Search/Search.jsx
  content-src/components/Search/_Search.scss
  lib/PlacesFeed.jsm
  test/unit/common/Reducers.test.js
  test/unit/content-src/components/Search.test.jsx
  test/unit/lib/PlacesFeed.test.js
  test/unit/unit-entry.js
Labels: PR / R+ with nits

#4695 Bug 1519342 - Show Onboarding card after RTAMO addon install
  content-src/asrouter/asrouter-content.jsx
  content-src/asrouter/templates/ReturnToAMO/ReturnToAMO.jsx
  lib/ASRouter.jsm
  test/unit/asrouter/ASRouter.test.js
Labels: PR / R+

#4708 Bug 1519772 - Implement pressed and hover states for list items
  content-src/components/DiscoveryStreamComponents/List/_List.scss
Labels: PR / R+

#4709 Bug 1519770 - Remove placeholder topic information from list items
  content-src/components/DiscoveryStreamComponents/List/List.jsx
Labels: PR / R+

#4710 (nobug) - Center Card images
  content-src/components/DiscoveryStreamComponents/DSCard/_DSCard.scss
  content-src/components/DiscoveryStreamComponents/Hero/_Hero.scss
Labels: PR / R+

#4711 Bug 1522233 - Add styling for HorizonalRule
  content-src/components/DiscoveryStreamComponents/Hero/_Hero.scss
  content-src/components/DiscoveryStreamComponents/HorizontalRule/HorizontalRule.jsx
  content-src/components/DiscoveryStreamComponents/HorizontalRule/_HorizontalRule.scss
Labels: PR / R+ with nits

#4714 Bug 1519773 - implement image placeholder style for list items
  content-src/components/DiscoveryStreamComponents/DSCard/_DSCard.scss
  content-src/components/DiscoveryStreamComponents/Hero/_Hero.scss
  content-src/components/DiscoveryStreamComponents/List/List.jsx
  content-src/components/DiscoveryStreamComponents/List/_List.scss
  content-src/styles/_mixins.scss
  content-src/styles/_theme.scss
  test/unit/content-src/components/DiscoveryStreamComponents/List.test.jsx
Labels: PR / R+ with nits

#4689 Bug 1517330 - Add optional heading to simple snippet
  content-src/asrouter/components/ConditionalWrapper/ConditionalWrapper.jsx
  content-src/asrouter/templates/SimpleSnippet/SimpleSnippet.jsx
  content-src/asrouter/templates/SimpleSnippet/SimpleSnippet.schema.json
  content-src/asrouter/templates/SimpleSnippet/_SimpleSnippet.scss
  lib/SnippetsTestMessageProvider.jsm
  test/unit/asrouter/templates/SimpleSnippet.test.jsx
Labels: PR / R+ with nits

#4723 Bug 1519871 - implement borderless ds lists
  content-src/components/DiscoveryStreamBase/DiscoveryStreamBase.jsx
  content-src/components/DiscoveryStreamComponents/List/List.jsx
  content-src/components/DiscoveryStreamComponents/List/_List.scss
Labels: PR / R+

#4716 Bug 1520849 - Add error boundary for DiscoveryStream
  content-src/components/Base/Base.jsx
  content-src/components/ErrorBoundary/_ErrorBoundary.scss
Labels: PR / R+ with nits

#4717 Bug 1521743 – Using `domain` for article sources
  content-src/components/DiscoveryStreamComponents/Hero/Hero.jsx
Labels: PR / Needs review

#4712 Bug 1521605 – Setting proper order for hero img and text in 2/3 layout
  content-src/components/DiscoveryStreamComponents/Hero/_Hero.scss
Labels: PR / R+ with nits

#4721 Bug 1521568 - Can't drag downloaded PDF into new tab
  content-src/components/Search/Search.jsx
  content-src/components/Search/_Search.scss
Labels: PR / R+

#4715 Bug 1520853 - update default search shortcuts config for Fx66
  lib/ActivityStream.jsm
  lib/TopSitesFeed.jsm
  test/browser/browser_topsites_contextMenu_options.js
  test/browser/browser_topsites_section.js
  test/unit/lib/TopSitesFeed.test.js
Labels: PR / R+

#4720 Bug 1519764 - Disable Dark theme for Discovery Stream
  content-src/asrouter/components/Button/_Button.scss
  content-src/asrouter/components/SnippetBase/_SnippetBase.scss
  content-src/components/ASRouterAdmin/ASRouterAdmin.scss
  content-src/components/Base/Base.jsx
  content-src/components/Base/_Base.scss
  content-src/components/Card/_Card.scss
  content-src/styles/_theme.scss
  content-src/styles/activity-stream-mac.scss
Labels: PR / R+

#4724 Bug 1522177 - Ensure card does not create an empty tag when excerpt i…
  content-src/components/DiscoveryStreamComponents/DSCard/DSCard.jsx
Labels: PR / R+

#4725 Bug 1522590 – Hero Component Refinements
  content-src/components/DiscoveryStreamBase/DiscoveryStreamBase.jsx
  content-src/components/DiscoveryStreamComponents/Hero/Hero.jsx
  content-src/components/DiscoveryStreamComponents/Hero/_Hero.scss
  content-src/components/DiscoveryStreamComponents/List/List.jsx
  content-src/styles/_mixins.scss
Labels: PR / R+

#4719 Bug 1521119 - make list horizontal rules show up in right places
  content-src/components/DiscoveryStreamComponents/List/_List.scss
Labels: PR / Needs review

#4722 Bug 1521915 - replace DiscoveryStream three-period ellipses with a single unicode ellipsis character
  content-src/components/DiscoveryStreamComponents/Hero/Hero.jsx
  content-src/lib/truncate-text.js
  test/unit/content-src/lib/truncate-text.test.js
Labels: PR / R+

#4726 Bug 1519878 - implement full width ds-list items
  content-src/components/DiscoveryStreamBase/DiscoveryStreamBase.jsx
  content-src/components/DiscoveryStreamComponents/List/List.jsx
  content-src/components/DiscoveryStreamComponents/List/_List.scss
Labels: PR / R+

#4727 Bug 1522677 – Card Grid refinements
  content-src/components/DiscoveryStreamComponents/CardGrid/CardGrid.jsx
  content-src/components/DiscoveryStreamComponents/CardGrid/_CardGrid.scss
  content-src/components/DiscoveryStreamComponents/DSCard/_DSCard.scss
  content-src/components/DiscoveryStreamComponents/Hero/_Hero.scss
  content-src/styles/_mixins.scss
Labels: PR / R+ with nits

#4732 Bug 1522683 - Nav css updates.
  content-src/components/DiscoveryStreamComponents/Navigation/Navigation.jsx
  content-src/components/DiscoveryStreamComponents/Navigation/_Navigation.scss
Labels: PR / R+

#4736 Bug 1522976 - Card grid stuffs.
  content-src/components/DiscoveryStreamComponents/CardGrid/_CardGrid.scss
  content-src/components/DiscoveryStreamComponents/DSCard/DSCard.jsx
  content-src/components/DiscoveryStreamComponents/DSCard/_DSCard.scss
Labels: PR / R+

#4735 Bug 1522865 - Adjust list title weight and numbered circle
  content-src/components/DiscoveryStreamComponents/List/List.jsx
  content-src/components/DiscoveryStreamComponents/List/_List.scss
Labels: PR / Needs review

#4737 Bug 1522993 - align text to bottom of card.
  content-src/components/DiscoveryStreamComponents/DSCard/DSCard.jsx
  content-src/components/DiscoveryStreamComponents/DSCard/_DSCard.scss
Labels: PR / Needs review

#4730 Bug 1518261
  lib/DiscoveryStreamFeed.jsm
  test/unit/lib/DiscoveryStreamFeed.test.js
Labels: PR / Needs review

#4739 Bug 1523031 - Hero with lists show 1 too many items
  content-src/components/DiscoveryStreamComponents/Hero/Hero.jsx
Labels: PR / R+

#4744 Port Bug 1518426 - Add another domain to FilterAdult. r=Mardak
  lib/FilterAdult.jsm
Labels: PR / R+

#4746 Port Bug 1514594: Part 3 - Change ChromeUtils.import API. *** Bug 1514594: Part 3a - Change ChromeUtils.import to return an exports object; not pollute global. r=mccr8
  aboutNewTabService.js
  common/PerfService.jsm
  common/Reducers.jsm
  karma.mc.config.js
  lib/ASRouter.jsm
  lib/ASRouterFeed.jsm
  lib/ASRouterPreferences.jsm
  lib/ASRouterTargeting.jsm
  lib/ASRouterTriggerListeners.jsm
  lib/AboutPreferences.jsm
  lib/ActivityStream.jsm
  lib/ActivityStreamMessageChannel.jsm
  lib/ActivityStreamPrefs.jsm
  lib/CFRPageActions.jsm
  lib/DiscoveryStreamFeed.jsm
  lib/DownloadsManager.jsm
  lib/FaviconFeed.jsm
  lib/HighlightsFeed.jsm
  lib/ManualMigration.jsm
  lib/NaiveBayesTextTagger.jsm
  lib/NewTabInit.jsm
  lib/NmfTextTagger.jsm
  lib/OnboardingMessageProvider.jsm
  lib/PersistentCache.jsm
  lib/PersonalityProvider.jsm
  lib/PlacesFeed.jsm
  lib/PrefsFeed.jsm
  lib/RecipeExecutor.jsm
  lib/SearchShortcuts.jsm
  lib/SectionsManager.jsm
  lib/ShortURL.jsm
  lib/SiteClassifier.jsm
  lib/SnippetsFeed.jsm
  lib/Store.jsm
  lib/SystemTickFeed.jsm
  lib/TelemetryFeed.jsm
  lib/TippyTopProvider.jsm
  lib/TopSitesFeed.jsm
  lib/TopStoriesFeed.jsm
  lib/UTEventReporting.jsm
  lib/UserDomainAffinityProvider.jsm
  package-lock.json
  package.json
  ping-centre/PingCentre.jsm
  test/browser/browser_activity_stream_strings.js
  test/browser/browser_asrouter_cfr.js
  test/browser/browser_asrouter_targeting.js
  test/browser/browser_asrouter_trigger_listeners.js
  test/browser/browser_enabled_newtabpage.js
  test/browser/browser_getScreenshots.js
  test/browser/browser_newtab_overrides.js
  test/browser/browser_packaged_as_locales.js
  test/unit/unit-entry.js
  test/xpcshell/test_ASRouterTargeting_attribution.js
  test/xpcshell/test_AboutNewTabService.js
  webpack.system-addon.config.js
Labels: PR / R+ with nits

#4745 chore(tests): Add basic hero and list tests to ensure correct item offset rendering
  test/unit/content-src/components/DiscoveryStreamComponents/Hero.test.jsx
  test/unit/content-src/components/DiscoveryStreamComponents/List.test.jsx
Labels: PR / R+

#4742 Bug 1523381 - Update max items for Pocket API endpoint 0.7
  content-src/components/DiscoveryStreamBase/DiscoveryStreamBase.jsx
Labels: PR / R+, Uplift Needed
