Repository mozilla/activity-stream, pull requests merged in 2019-03, with the labels that each got.

#4823 Bug 1531604 - Fixing impression pos
  content-src/components/DiscoveryStreamComponents/CardGrid/CardGrid.jsx
  content-src/components/DiscoveryStreamComponents/DSCard/DSCard.jsx
  content-src/components/DiscoveryStreamComponents/Hero/Hero.jsx
  content-src/components/DiscoveryStreamComponents/List/List.jsx
  content-src/components/DiscoveryStreamImpressionStats/ImpressionStats.jsx
  content-src/lib/selectLayoutRender.js
  lib/TelemetryFeed.jsm
  test/unit/content-src/components/DiscoveryStreamComponents/ImpressionStats.test.jsx
  test/unit/content-src/lib/selectLayoutRender.test.js
  test/unit/lib/TelemetryFeed.test.js
Labels: PR / R+

#4819 Bug 1528953 - Add pref to opt out of recommended features
  lib/ASRouter.jsm
  lib/ASRouterPreferences.jsm
  lib/ActivityStream.jsm
  lib/CFRMessageProvider.jsm
  test/unit/asrouter/ASRouter.test.js
  test/unit/asrouter/ASRouterPreferences.test.js
  test/unit/asrouter/CFRMessageProvider.test.js
Labels: PR / R+ with nits

#4830 Backport Bug 827976 (with fixes)
  lib/DownloadsManager.jsm
  test/unit/unit-entry.js
Labels: PR / Needs review

#4818 Bug 1527642 - Pocket New Tab context menu UI
  content-src/components/ContextMenu/ContextMenu.jsx
  content-src/components/DiscoveryStreamComponents/DSCard/DSCard.jsx
  content-src/components/DiscoveryStreamComponents/DSCard/_DSCard.scss
  content-src/components/DiscoveryStreamComponents/DSLinkMenu/DSLinkMenu.jsx
  content-src/components/DiscoveryStreamComponents/DSLinkMenu/_DSLinkMenu.scss
  content-src/components/DiscoveryStreamComponents/Hero/Hero.jsx
  content-src/components/DiscoveryStreamComponents/Hero/_Hero.scss
  content-src/components/DiscoveryStreamComponents/List/List.jsx
  content-src/components/LinkMenu/LinkMenu.jsx
  content-src/styles/_activity-stream.scss
  test/unit/content-src/components/DiscoveryStreamComponents/DSLinkMenu.test.jsx
Labels: PR / R+

#4829 Bug 1532807 - Fixing Taskcluster failure
  content-src/components/DiscoveryStreamComponents/HorizontalRule/_HorizontalRule.scss
  content-src/styles/_mixins.scss
Labels: PR / R+

#4831 Bug 1533089 - HTTP Referer not set when clicking articles
  content-src/components/DiscoveryStreamComponents/DSCard/DSCard.jsx
  content-src/components/DiscoveryStreamComponents/Hero/Hero.jsx
  content-src/components/DiscoveryStreamComponents/List/List.jsx
  content-src/components/DiscoveryStreamComponents/SafeAnchor/SafeAnchor.jsx
Labels: PR / R+

#4832 Bug 1533089 - HTTP Referer not set when clicking articles
  content-src/components/DiscoveryStreamComponents/DSCard/DSCard.jsx
  content-src/components/DiscoveryStreamComponents/DSLinkMenu/DSLinkMenu.jsx
  content-src/components/DiscoveryStreamComponents/Hero/Hero.jsx
  content-src/components/DiscoveryStreamComponents/List/List.jsx
  content-src/components/DiscoveryStreamComponents/SafeAnchor/SafeAnchor.jsx
Labels: PR / R+

#4826 Bug 1531604 - Fixing impression pos (#4823)
  content-src/components/DiscoveryStreamComponents/CardGrid/CardGrid.jsx
  content-src/components/DiscoveryStreamComponents/DSCard/DSCard.jsx
  content-src/components/DiscoveryStreamComponents/Hero/Hero.jsx
  content-src/components/DiscoveryStreamComponents/List/List.jsx
  content-src/components/DiscoveryStreamImpressionStats/ImpressionStats.jsx
  content-src/lib/selectLayoutRender.js
  lib/TelemetryFeed.jsm
  test/unit/content-src/components/DiscoveryStreamComponents/ImpressionStats.test.jsx
  test/unit/content-src/lib/selectLayoutRender.test.js
  test/unit/lib/TelemetryFeed.test.js
Labels: PR / On hold for now

#4828 Bug 1532777 - Track cfr user preferences in AS pings
  docs/v2-system-addon/data_dictionary.md
  lib/TelemetryFeed.jsm
Labels: PR / R+

#4840 (nobug) CFR icon attribute should use content.category
  lib/CFRPageActions.jsm
Labels: PR / Needs review

#4820 Bug 1521203 - Ensure appropriate resource requests for endpoints (layout, feed, spoc)
  lib/ActivityStream.jsm
  lib/DiscoveryStreamFeed.jsm
  test/browser/browser.ini
  test/unit/lib/DiscoveryStreamFeed.test.js
Labels: PR / R+

#4837 Bug 1531585 - Dismiss as link menu option
  common/Reducers.jsm
  content-src/components/DiscoveryStreamComponents/DSCard/DSCard.jsx
  content-src/components/DiscoveryStreamComponents/DSLinkMenu/DSLinkMenu.jsx
  content-src/components/DiscoveryStreamComponents/Hero/Hero.jsx
  content-src/components/DiscoveryStreamComponents/Hero/_Hero.scss
  content-src/components/DiscoveryStreamComponents/List/List.jsx
  lib/DiscoveryStreamFeed.jsm
  test/unit/common/Reducers.test.js
  test/unit/content-src/components/DiscoveryStreamComponents/DSLinkMenu.test.jsx
  test/unit/lib/DiscoveryStreamFeed.test.js
Labels: PR / R+

#4851 Bug 1534253 – Adding active state to dark theme cards
  content-src/components/DiscoveryStreamComponents/DSCard/_DSCard.scss
Labels: PR / R+

#4848 Bug 1517303 - Add tests to verify CFR & targeting
  test/browser/browser_asrouter_targeting.js
Labels: PR / R+

#4843 Bug 1508669 - Update dev dependencies
  package-lock.json
  package.json
Labels: PR / R+

#4853 Bug 1534278 –  Remove Extra borders on Hero cards on Dark theme
  content-src/components/DiscoveryStreamComponents/Hero/_Hero.scss
  content-src/styles/_mixins.scss
Labels: PR / R+ with nits

#4842 Bug 1533053 - Add more automated tests to check switching between fea…
  test/browser/browser_asrouter_cfr.js
Labels: PR / R+

#4857 Bug 1535464 - Update CFR addon Learn More links
  lib/CFRMessageProvider.jsm
Labels: PR / R+

#4852 Bug 1534934 - Investigate multiple CFR triggers being called at the s…
  lib/CFRPageActions.jsm
  test/browser/browser_asrouter_cfr.js
  test/unit/asrouter/ASRouter.test.js
  test/unit/asrouter/CFRPageActions.test.js
  test/unit/asrouter/constants.js
Labels: PR / R+ with nits

#4856 Bug 1510335 - Set theme variant using query parameter
  content-src/asrouter/asrouter-content.jsx
  content-src/lib/constants.js
  test/unit/asrouter/asrouter-content.test.jsx
Labels: PR / R+

#4858 Bug 1535401 - Fix spocs display based off probability
  content-src/components/DiscoveryStreamBase/DiscoveryStreamBase.jsx
  content-src/lib/selectLayoutRender.js
  test/unit/content-src/components/DiscoveryStreamComponents/DiscoveryStreamBase.test.jsx
  test/unit/content-src/lib/selectLayoutRender.test.js
Labels: PR / R+ with nits

#4816 Bug 1529035 - State and pref reset
  common/Reducers.jsm
  lib/DiscoveryStreamFeed.jsm
  test/unit/common/Reducers.test.js
  test/unit/lib/DiscoveryStreamFeed.test.js
Labels: PR / R+

#4859 Bug 1530359 - Handle URL redirects for CFR triggers
  lib/ASRouterTriggerListeners.jsm
  test/unit/asrouter/ASRouterTriggerListeners.test.js
  test/unit/asrouter/CFRMessageProvider.test.js
Labels: PR / R+

#4867 Bug 1530714 - Report ASRouter errors in ASRouterAdmin
  content-src/components/ASRouterAdmin/ASRouterAdmin.jsx
  content-src/components/ASRouterAdmin/ASRouterAdmin.scss
  lib/ASRouter.jsm
  test/unit/asrouter/ASRouter.test.js
  test/unit/asrouter/MessageLoaderUtils.test.js
  test/unit/content-src/components/ASRouterAdmin.test.jsx
Labels: PR / R+ with nits
