Repository mozilla/activity-stream, pull requests merged in 2019-02, with the labels that each got.

#4753 Bug 1524386 - Update descriptions in CFR template schema
  content-src/asrouter/templates/CFR/templates/ExtensionDoorhanger.schema.json
Labels: PR / Needs review

#4749 Bug 1518521 - Record a scalar for how long it takes to present about:home after start-up
  aboutNewTabService.js
  lib/TelemetryFeed.jsm
  nsIAboutNewTabService.idl
  test/unit/lib/TelemetryFeed.test.js
Labels: PR / R+

#4751 Bug 1524321 – Removing truncation + character counts
  content-src/components/DiscoveryStreamComponents/Hero/Hero.jsx
  content-src/components/DiscoveryStreamComponents/List/List.jsx
  content-src/lib/truncate-text.js
  test/unit/content-src/lib/truncate-text.test.js
Labels: PR / R+

#4754 Bug 1521084 - Make opt-out button work about:preferences if users are not enrolled in an experiment
  common/Actions.jsm
  lib/AboutPreferences.jsm
  lib/ActivityStream.jsm
  lib/DiscoveryStreamFeed.jsm
  test/unit/lib/AboutPreferences.test.js
  test/unit/lib/DiscoveryStreamFeed.test.js
Labels: PR / Needs review

#4763 Port Bug 1525134 - Remove remote url from browser_discovery_styles.js r=andreio
  test/browser/browser_discovery_styles.js
Labels: PR / Needs review

#4761 Bug 1525413 - Perf work on loading discovery stream
  common/Reducers.jsm
  content-src/components/Base/Base.jsx
  content-src/components/Base/_Base.scss
  content-src/components/DiscoveryStreamBase/DiscoveryStreamBase.jsx
  content-src/lib/selectLayoutRender.js
  lib/DiscoveryStreamFeed.jsm
  test/unit/common/Reducers.test.js
  test/unit/content-src/components/DiscoveryStreamComponents/DiscoveryStreamBase.test.jsx
  test/unit/lib/DiscoveryStreamFeed.test.js
Labels: PR / R+ with nits

#4767 Followup Bug 1521084 - Add default pref for impressions so it gets into redux state
  lib/ActivityStream.jsm
Labels: PR / Needs review

#4771 Bug 1525932 - Dark Mode message typo fix
  content-src/components/DarkModeMessage/DarkModeMessage.jsx
Labels: PR / R+

#4764 Bug 1524632 – Design refinements for 66 components
  content-src/components/DiscoveryStreamBase/_DiscoveryStreamBase.scss
  content-src/components/DiscoveryStreamComponents/CardGrid/_CardGrid.scss
  content-src/components/DiscoveryStreamComponents/DSCard/_DSCard.scss
  content-src/components/DiscoveryStreamComponents/Hero/Hero.jsx
  content-src/components/DiscoveryStreamComponents/Hero/_Hero.scss
  content-src/components/DiscoveryStreamComponents/List/_List.scss
  content-src/components/DiscoveryStreamComponents/Navigation/_Navigation.scss
  content-src/components/DiscoveryStreamComponents/SectionTitle/_SectionTitle.scss
Labels: PR / R+

#4769 Bug 1523381 - Update max items for Pocket API endpoint 0.7 (#4742)
  content-src/components/DiscoveryStreamBase/DiscoveryStreamBase.jsx
Labels: PR / R+

#4765 Bug 1525581 - Load cached content on startup and update in the backgr…
  lib/DiscoveryStreamFeed.jsm
  test/unit/lib/DiscoveryStreamFeed.test.js
Labels: PR / R+

#4774 Bug 1519879 - Spoc Items in List
  content-src/components/DiscoveryStreamBase/DiscoveryStreamBase.jsx
  content-src/components/DiscoveryStreamComponents/DSCard/DSCard.jsx
  content-src/components/DiscoveryStreamComponents/Hero/Hero.jsx
  content-src/components/DiscoveryStreamComponents/List/List.jsx
  content-src/components/DiscoveryStreamComponents/List/_List.scss
  content-src/components/DiscoveryStreamComponents/SpocIntersectionObserver/SpocIntersectionObserver.jsx
  test/unit/content-src/components/DiscoveryStreamComponents/List.test.jsx
Labels: PR / Needs review

#4760 Bug 1523703 - Pref on Pocket Newtab experience in Nightly for EN and CA
  lib/ActivityStream.jsm
Labels: PR / On hold for now

#4775 (nobug) - Refactor loadLayout so that _timestamp is now lastUpdated
  lib/DiscoveryStreamFeed.jsm
  test/unit/lib/DiscoveryStreamFeed.test.js
Labels: PR / R+ with nits

#4779 Bug 1526387 - CFR Addon Recommendations call remote API before clicking "Install"
  lib/CFRPageActions.jsm
  test/browser/browser_asrouter_cfr.js
  test/unit/asrouter/CFRPageActions.test.js
Labels: PR / R+ with nits

#4772 Bug 1525494 - Parallel component feed loads
  content-src/components/ASRouterAdmin/ASRouterAdmin.jsx
  content-src/lib/selectLayoutRender.js
  lib/DiscoveryStreamFeed.jsm
  test/unit/content-src/lib/selectLayoutRender.test.js
  test/unit/lib/DiscoveryStreamFeed.test.js
Labels: PR / Needs review

#4785 Bug 1527195 - Height issues fixed for ds card.
  content-src/components/DiscoveryStreamComponents/DSCard/DSCard.jsx
Labels: PR / Needs review

#4766 Bug 1525391 - Collect telemetry for request time and cache age for Pocket
  docs/v2-system-addon/data_events.md
  lib/DiscoveryStreamFeed.jsm
  test/unit/lib/DiscoveryStreamFeed.test.js
Labels: PR / Needs review

#4778 Bug 1500061 - Tighen CSP for new tab
  bin/render-activity-stream-html.js
  content-src/lib/snippets.js
Labels: PR / R+ with nits

#4787 (no bug) - Fix taskcluster by actually using packaged dist files for referenced test
  mochitest.sh
Labels: PR / R+

#4786 Bug 1527347 - Remove breakpoints for Discovery Stream.
  content-src/components/Base/Base.jsx
  content-src/components/Base/_Base.scss
Labels: PR / R+

#4781 Bug 1525366 - Show user preference for SPOCs if Discoverystream is on
  lib/AboutPreferences.jsm
  lib/DiscoveryStreamFeed.jsm
  locales-src/en-US/strings.properties
  test/unit/lib/AboutPreferences.test.js
  test/unit/lib/DiscoveryStreamFeed.test.js
Labels: PR / R+

#4789 Bug 1527626 - Large blank area in the search results on Preferences w…
  lib/AboutPreferences.jsm
  locales-src/en-US/strings.properties
  test/unit/lib/AboutPreferences.test.js
Labels: PR / Needs review

#4788 Bug 1527397 – Refactor Hero's full width layout
  content-src/components/DiscoveryStreamComponents/Hero/Hero.jsx
  content-src/components/DiscoveryStreamComponents/Hero/_Hero.scss
Labels: PR / R+

#4784 Bug 1518258 - Use pref based consumer key in discovery stream layout …
  lib/ActivityStream.jsm
  lib/DiscoveryStreamFeed.jsm
  test/unit/lib/DiscoveryStreamFeed.test.js
Labels: PR / R+ with nits

#4791 Bug 1527701 - Use SafeAnchor in navigation and message component
  content-src/components/DiscoveryStreamComponents/DSMessage/DSMessage.jsx
  content-src/components/DiscoveryStreamComponents/Navigation/Navigation.jsx
  content-src/components/DiscoveryStreamComponents/SafeAnchor/SafeAnchor.jsx
Labels: PR / R+ with nits

#4792 Bug 1527980 - Add devtools for resetting and picking a layout variant
  content-src/components/ASRouterAdmin/ASRouterAdmin.jsx
  content-src/components/ASRouterAdmin/ASRouterAdmin.scss
Labels: PR / R+ with nits

#4794 Bug 1527347 - Fixing breakpoints for search too
  content-src/components/Base/_Base.scss
Labels: PR / R+

#4796 Port Bug 1527495 - migrate text-link binding to CE, r=bgrins
  lib/AboutPreferences.jsm
Labels: PR / Needs review

#4743 Bug 1522832 - Fine-grained visibility on impression stats
  common/Actions.jsm
  content-src/components/DiscoveryStreamBase/DiscoveryStreamBase.jsx
  content-src/components/DiscoveryStreamComponents/CardGrid/CardGrid.jsx
  content-src/components/DiscoveryStreamComponents/DSCard/DSCard.jsx
  content-src/components/DiscoveryStreamComponents/DSCard/_DSCard.scss
  content-src/components/DiscoveryStreamComponents/Hero/Hero.jsx
  content-src/components/DiscoveryStreamComponents/Hero/_Hero.scss
  content-src/components/DiscoveryStreamComponents/List/List.jsx
  content-src/components/DiscoveryStreamComponents/List/_List.scss
  content-src/components/DiscoveryStreamComponents/SpocIntersectionObserver/SpocIntersectionObserver.jsx
  content-src/components/DiscoveryStreamImpressionStats/ImpressionStats.jsx
  content-src/components/DiscoveryStreamImpressionStats/_ImpressionStats.scss
  content-src/styles/_activity-stream.scss
  lib/TelemetryFeed.jsm
  test/unit/content-src/components/DiscoveryStreamComponents/ImpressionStats.test.jsx
  test/unit/content-src/components/DiscoveryStreamComponents/List.test.jsx
  test/unit/lib/TelemetryFeed.test.js
Labels: PR / R+

#4797 Port Bug 1524688: Part 61 - Convert AboutNewTabService to static registration. r=mconley
  AboutNewTabService.jsm
  NewTabComponents.manifest
  components.conf
  moz.build
Labels: PR / Needs review

#4790 Bug 1527702 - Rotate based on impressions for recs.
  common/Actions.jsm
  lib/ActivityStream.jsm
  lib/DiscoveryStreamFeed.jsm
  lib/PrefsFeed.jsm
  test/unit/lib/DiscoveryStreamFeed.test.js
Labels: PR / R+ with nits

#4795 Bug 1527437 [Cards][Lists] - Align spocs items to bottom of container
  content-src/components/DiscoveryStreamComponents/List/List.jsx
  content-src/components/DiscoveryStreamComponents/List/_List.scss
Labels: PR / Needs review

#4799 Bug 1527702 - Followup: Fix test to check for new DISCOVERY_STREAM_IMPRESSION_STATS action
  test/unit/lib/DiscoveryStreamFeed.test.js
Labels: PR / R+

#4800 Bug 1527702 - Followup: Remove unused DISCOVERY_STREAM_REC_IMPRESSION action
  common/Actions.jsm
Labels: PR / Needs review

#4803 Bug 1528494 - Fix pref check in PrefsFeed.onPrefChanged()
  lib/PrefsFeed.jsm
Labels: PR / Needs review

#4783 Bug 1526452 - Stop exporting sourcemaps to MC, only support during startmc
  .gitignore
  docs/v2-system-addon/1.GETTING_STARTED.md
  jar.mn
  package.json
  webpack.aboutlibrary.config.js
  webpack.prerender.config.js
  webpack.system-addon.config.js
  yamscripts.yml
Labels: PR / R+ with nits

#4805 Bug 1508744 - Instrument pin tab event
  docs/v2-system-addon/data_events.md
  lib/TelemetryFeed.jsm
  test/unit/lib/TelemetryFeed.test.js
Labels: PR / R+

#4802 Bug 1503693 - CFR button should persist in the URL bar until excused
  lib/CFRPageActions.jsm
  test/unit/asrouter/CFRPageActions.test.js
Labels: PR / R+

#4812 Bug 1529730 - Impression capping for spocs on hero
  content-src/components/DiscoveryStreamComponents/Hero/Hero.jsx
Labels: PR / R+

#4810 Bug 1529334 - Blocking/unblocking CFR doesn't clear impressions
  lib/ASRouter.jsm
Labels: PR / R+

#4804 Bug 1527945 - Disable sync on .get() for Tippytop
  lib/FaviconFeed.jsm
Labels: PR / Needs review

#4808 Bug 1528059 - Fixing dismissed Pocket stories come back until stories…
  lib/TopStoriesFeed.jsm
  test/unit/lib/TopStoriesFeed.test.js
Labels: PR / R+ with nits

#4815 Bug 1522899 - Limit spocs per domain
  lib/DiscoveryStreamFeed.jsm
  test/unit/lib/DiscoveryStreamFeed.test.js
Labels: PR / R+

#4814 Bug 1517849 - Mirror impression telemetry to Structured Ingestion dat…
  lib/ActivityStream.jsm
  lib/TelemetryFeed.jsm
  ping-centre/PingCentre.jsm
  test/unit/lib/TelemetryFeed.test.js
  test/unit/ping-centre/PingCentre.test.js
Labels: PR / R+ with nits

#4809 Bug 1528959 - Pin Tab CFR template and schema
  common/Actions.jsm
  content-src/asrouter/docs/targeting-attributes.md
  content-src/asrouter/templates/CFR/templates/ExtensionDoorhanger.schema.json
  lib/ASRouter.jsm
  lib/ASRouterTargeting.jsm
  lib/ASRouterTriggerListeners.jsm
  lib/CFRMessageProvider.jsm
  test/browser/browser_asrouter_targeting.js
  test/unit/asrouter/ASRouter.test.js
  test/unit/asrouter/ASRouterTargeting.test.js
  test/unit/asrouter/ASRouterTriggerListeners.test.js
  test/unit/asrouter/CFRMessageProvider.test.js
  test/unit/asrouter/constants.js
  test/unit/unit-entry.js
Labels: PR / R+ with nits

#4817 Bug 1529730 - Impression capping for spocs on hero (#4812)
  content-src/components/DiscoveryStreamComponents/Hero/Hero.jsx
Labels: PR / On hold for now
