Repository mozilla/activity-stream, pull requests merged in 2019-05, with the labels that each got.

#4948 Bug 1547061 - Port FXA signup form to trailhead first run
  content-src/asrouter/asrouter-content.jsx
  content-src/asrouter/templates/Trailhead/Trailhead.jsx
  content-src/asrouter/templates/Trailhead/_Trailhead.scss
  content-src/components/Base/Base.jsx
  test/unit/asrouter/templates/Trailhead.test.jsx
Labels: PR / R+ with nits

#4961 Bug 1548267 - Overlay accessibility
  content-src/asrouter/components/ModalOverlay/ModalOverlay.jsx
  content-src/asrouter/components/ModalOverlay/_ModalOverlay.scss
  content-src/asrouter/templates/Trailhead/Trailhead.jsx
  test/unit/asrouter/ModalOverlay.test.jsx
Labels: PR / Needs review

#4962 Bug 1548268 - Turn on jsx-a11y for the trailhead related files
  .eslintrc.jsx-a11y.js
  content-src/asrouter/components/ModalOverlay/ModalOverlay.jsx
  content-src/asrouter/templates/OnboardingMessage/OnboardingMessage.jsx
  content-src/asrouter/templates/Trailhead/Trailhead.jsx
  content-src/asrouter/templates/Trailhead/_Trailhead.scss
  package-lock.json
  package.json
  yamscripts.yml
Labels: PR / R+

#4959 Followup Bug 1547748 - Run browser_newtab_userTypedValue.js and fix sendAsyncMessage exception
  lib/ASRouter.jsm
  mochitest.sh
Labels: PR / Needs review

#4965 (nobug) remove locale targeting for nightly testing
  lib/OnboardingMessageProvider.jsm
Labels: PR / Needs review

#4966 Bug 1547065 - Add some finalized actions for trailhead cards
  lib/OnboardingMessageProvider.jsm
Labels: PR / R+

#4928 Bug 1535717 - Add SPOCS Fill ping
  common/Actions.jsm
  common/Reducers.jsm
  content-src/components/DiscoveryStreamBase/DiscoveryStreamBase.jsx
  content-src/lib/selectLayoutRender.js
  docs/v2-system-addon/data_dictionary.md
  docs/v2-system-addon/data_events.md
  lib/DiscoveryStreamFeed.jsm
  lib/TelemetryFeed.jsm
  ping-centre/PingCentre.jsm
  test/schemas/pings.js
  test/unit/common/Reducers.test.js
  test/unit/content-src/lib/selectLayoutRender.test.js
  test/unit/lib/DiscoveryStreamFeed.test.js
  test/unit/lib/TelemetryFeed.test.js
  test/unit/ping-centre/PingCentre.test.js
Labels: PR / R+

#4952 Bug 1546422 - FXA-related snippets should not snow up if Firefox Acco…
  content-src/asrouter/docs/targeting-attributes.md
  lib/ASRouterTargeting.jsm
  test/browser/browser_asrouter_targeting.js
Labels: PR / R+ with nits

#4972 Bug 1535717 - Update telemetry endpoint for Spocs Fill
  common/Actions.jsm
  lib/TelemetryFeed.jsm
Labels: PR / R+

#4973 Bug 1548504 - Support localized "Sync" first run variant
  content-src/asrouter/templates/Trailhead/Trailhead.jsx
  lib/OnboardingMessageProvider.jsm
  test/unit/asrouter/asrouter-content.test.jsx
  test/unit/asrouter/templates/Trailhead.test.jsx
Labels: PR / Needs review

#4977 Bug 1548648 - Do not send session ping for hidden preloaded newtab
  lib/TelemetryFeed.jsm
  test/unit/lib/TelemetryFeed.test.js
Labels: PR / R+

#4975 Bug 1548743 - Improve styling of trailhead flow (scrollable page, animations, dismiss)
  content-src/asrouter/templates/Trailhead/Trailhead.jsx
  content-src/asrouter/templates/Trailhead/_Trailhead.scss
  content-src/components/ASRouterAdmin/ASRouterAdmin.scss
  content-src/styles/_activity-stream.scss
  content-src/styles/_theme.scss
  content-src/styles/_variables.scss
Labels: PR / R+ with nits

#4935 Bug 1546898 - Bookmark Panel QA test provider
  common/Reducers.jsm
  content-src/asrouter/schemas/panel/cfr-fxa-bookmark.schema.json
  content-src/components/ASRouterAdmin/ASRouterAdmin.jsx
  lib/ASRouter.jsm
  lib/ASRouterPreferences.jsm
  lib/BookmarkPanelHub.jsm
  lib/PanelTestProvider.jsm
  test/unit/asrouter/ASRouter.test.js
  test/unit/asrouter/ASRouterPreferences.test.js
  test/unit/asrouter/PanelTestProvider.test.js
  test/unit/asrouter/schemas/panel/cfr-fxa-bookmark.schema.test.js
  test/unit/common/Reducers.test.js
  test/unit/lib/BookmarkPanelHub.test.js
Labels: PR / R+

#4976 Bug 1547211 - Better fallback states for DS for offline mode
  content-src/components/DiscoveryStreamComponents/DSImage/DSImage.jsx
  content-src/components/DiscoveryStreamComponents/DSImage/DSImage.scss
Labels: PR / R+

#4971 Bug 1548353 - Timeout DS fetches after 45 seconds.
  lib/DiscoveryStreamFeed.jsm
  test/unit/lib/DiscoveryStreamFeed.test.js
Labels: PR / Needs review

#4980 Bug 1547062 - Experiment branch generation for trailhead
  content-src/asrouter/docs/targeting-attributes.md
  content-src/components/ASRouterAdmin/ASRouterAdmin.jsx
  content-src/components/ASRouterAdmin/ASRouterAdmin.scss
  lib/ASRouter.jsm
  lib/ASRouterTargeting.jsm
  lib/OnboardingMessageProvider.jsm
  test/unit/asrouter/ASRouter.test.js
  test/unit/asrouter/TargetingDocs.test.js
  test/unit/content-src/components/ASRouterAdmin.test.jsx
  test/unit/unit-entry.js
Labels: PR / R+ with nits

#4978 Bug 1548721 - update react-redux from 5.1.0 to 7.0.3
  package-lock.json
  package.json
  vendor/react-redux.js
Labels: PR / R+

#4981 (nobug) - Turn on CFR FxA remote provider
  lib/ActivityStream.jsm
Labels: PR / R+

#4979 Bug1548520 - Add user telemetry for click events
  docs/v2-system-addon/data_events.md
  lib/ASRouter.jsm
  lib/BookmarkPanelHub.jsm
  test/unit/lib/BookmarkPanelHub.test.js
Labels: PR / R+ with nits

#4909 Bug 1548329 - Load discovery stream feeds sequentially without blocking
  common/Actions.jsm
  common/Reducers.jsm
  content-src/components/DiscoveryStreamBase/DiscoveryStreamBase.jsx
  content-src/lib/selectLayoutRender.js
  lib/DiscoveryStreamFeed.jsm
  test/unit/common/Reducers.test.js
  test/unit/content-src/components/DiscoveryStreamBase.test.jsx
  test/unit/content-src/lib/selectLayoutRender.test.js
  test/unit/lib/DiscoveryStreamFeed.test.js
Labels: PR / Needs review

#4983 Bug 1545110 - Unexpected search shortcut in Topsites
  lib/ActivityStream.jsm
  lib/TopSitesFeed.jsm
  test/unit/lib/TopSitesFeed.test.js
Labels: PR / R+

#4984 Bug 1548915 - Change DS default layout
  lib/DiscoveryStreamFeed.jsm
Labels: PR / R+

#4939 Bug 1546734 - [Card] Adjust vertical spacing and text color
  content-src/components/DiscoveryStreamComponents/CardGrid/_CardGrid.scss
  content-src/components/DiscoveryStreamComponents/DSCard/_DSCard.scss
  content-src/components/DiscoveryStreamComponents/Hero/_Hero.scss
  content-src/components/DiscoveryStreamComponents/List/_List.scss
Labels: PR / Needs review

#4990 Bug 1549716 - The email input field border wrongly remains red after clearing an invalid email
  content-src/asrouter/templates/Trailhead/_Trailhead.scss
Labels: PR / R+

#4989 Bug 1549722 - The hover effect of the buttons from the first run card s is barely noticeable on Dark Theme
  content-src/styles/_theme.scss
Labels: PR / Needs review

#4985 Bug 1548503 - Update card button actions with finalized urls or actions
  content-src/asrouter/templates/StartupOverlay/StartupOverlay.jsx
  content-src/asrouter/templates/Trailhead/Trailhead.jsx
  lib/OnboardingMessageProvider.jsm
  test/unit/asrouter/templates/Trailhead.test.jsx
Labels: PR / R+ with nits

#4991 Bug 1549714 - The new onboarding modal is not scrollable if the browser window is horizontally resized to less than 25%
  content-src/asrouter/templates/Trailhead/_Trailhead.scss
Labels: PR / Needs review

#4987 Bug 1548268 - Improve accessibility of trailhead flow
  bin/render-activity-stream-html.js
  content-src/asrouter/asrouter-content.jsx
  content-src/asrouter/components/ModalOverlay/ModalOverlay.jsx
  content-src/asrouter/templates/Trailhead/Trailhead.jsx
  test/unit/asrouter/asrouter-content.test.jsx
  test/unit/asrouter/templates/Trailhead.test.jsx
Labels: PR / Needs review

#4970 Bug 1547016 - Use regular packaged finalized onboarding strings
  content-src/asrouter/templates/Trailhead/Trailhead.jsx
  jar.mn
  lib/OnboardingMessageProvider.jsm
Labels: PR / Needs review

#4993 Bug 1549846 - Set normandy-targetable string pref for interrupt survey
  lib/ASRouter.jsm
  test/unit/asrouter/ASRouter.test.js
Labels: PR / Needs review

#4994 Port 1549906 - Use brandings.ftl to allow OnboardingMessageProvider.jsm to use new strings
  lib/OnboardingMessageProvider.jsm
Labels: PR / Needs review

#4997 Bug 1550053 - Fix busted topsites and topstores configs enable/disable
  content-src/lib/selectLayoutRender.js
  test/unit/content-src/lib/selectLayoutRender.test.js
Labels: PR / Needs review

#4995 Bug 1549995 - The "SKIPPED_SIGNIN" telemetry ping is wrongly sent after the sign in flow from the "First Run Modal" is completed
  content-src/asrouter/components/ModalOverlay/ModalOverlay.jsx
  content-src/asrouter/templates/Trailhead/Trailhead.jsx
  test/unit/asrouter/templates/Trailhead.test.jsx
Labels: PR / Needs review

#4998 Bug 1550062 - First run modal should open all links in a new tab.
  content-src/asrouter/templates/Trailhead/Trailhead.jsx
Labels: PR / Needs review

#5000 Bug 1549802 - Update card button actions with final finalized urls or actions
  lib/OnboardingMessageProvider.jsm
Labels: PR / Needs review

#4999 Bug 1546733 - [Card] Place source above title and adjust vertical spacing
  content-src/components/DiscoveryStreamComponents/DSCard/DSCard.jsx
  content-src/components/DiscoveryStreamComponents/DSCard/_DSCard.scss
  content-src/components/DiscoveryStreamComponents/Hero/Hero.jsx
  content-src/components/DiscoveryStreamComponents/Hero/_Hero.scss
Labels: PR / Needs review

#5005 Bug 1549727 - The page shifts slightly to the left after dismissing the onboarding modal
  content-src/asrouter/templates/Trailhead/_Trailhead.scss
Labels: PR / Needs review

#5006 Bug 1549494 - Update image and styles for the sync branch of first run modal
  content-src/asrouter/templates/Trailhead/_Trailhead.scss
  data/content/assets/sync-devices-trailhead.svg
Labels: PR / Needs review

#5007 Bug 1549494 - (Followup fix) Update image and styles for the sync branch of first run modal
  data/content/assets/sync-devices-trailhead.svg
Labels: PR / Needs review

#5009 (nobug) - Have ratioSample resolve 0 instead of return 0
  test/unit/unit-entry.js
Labels: PR / Needs review

#5011 (nobug) - Remove unused trailhead.wip
  data/trailhead.wip
Labels: PR / Needs review

#5012 Bug 1550438 - Return-to-AMO strings need to be formatted
  lib/OnboardingMessageProvider.jsm
Labels: PR / R+

#4953 Beta uplift for Special FXA snippet
  bin/render-activity-stream-html.js
  common/Actions.jsm
  common/PrerenderData.jsm
  content-src/activity-stream.jsx
  content-src/asrouter/asrouter-content.jsx
  content-src/asrouter/components/SnippetBase/SnippetBase.jsx
  content-src/asrouter/templates/SimpleBelowSearchSnippet/SimpleBelowSearchSnippet.jsx
  content-src/asrouter/templates/SimpleBelowSearchSnippet/SimpleBelowSearchSnippet.schema.json
  content-src/asrouter/templates/SimpleBelowSearchSnippet/_SimpleBelowSearchSnippet.scss
  content-src/asrouter/templates/template-manifest.jsx
  content-src/components/Base/Base.jsx
  content-src/components/ManualMigration/ManualMigration.jsx
  content-src/components/ManualMigration/_ManualMigration.scss
  content-src/components/Search/_Search.scss
  content-src/lib/asroutercontent.js
  content-src/styles/_activity-stream.scss
  content-src/styles/_icons.scss
  data/content/assets/glyph-import-16.svg
  lib/ActivityStream.jsm
  lib/HighlightsFeed.jsm
  lib/ManualMigration.jsm
  lib/SnippetsTestMessageProvider.jsm
  lib/TopSitesFeed.jsm
  locales-src/en-US/strings.properties
  test/unit/activity-stream.test.jsx
  test/unit/asrouter/SnippetsTestMessageProvider.test.js
  test/unit/asrouter/asrouter-content.test.jsx
  test/unit/asrouter/constants.js
  test/unit/asrouter/templates/SimpleBelowSearchSnippet.test.jsx
  test/unit/common/Reducers.test.js
  test/unit/content-src/components/ConfirmDialog.test.jsx
  test/unit/content-src/components/ManualMigration.test.jsx
  test/unit/lib/ActivityStream.test.js
  test/unit/lib/HighlightsFeed.test.js
  test/unit/lib/ManualMigration.test.js
  test/unit/lib/TopSitesFeed.test.js
Labels: PR / Needs review

#5010 Bug 1550098 - Trailhead initial uplift for Firefox 67.0
  .eslintrc.jsx-a11y.js
  bin/render-activity-stream-html.js
  common/Actions.jsm
  content-src/asrouter/asrouter-content.jsx
  content-src/asrouter/components/ModalOverlay/ModalOverlay.jsx
  content-src/asrouter/components/ModalOverlay/_ModalOverlay.scss
  content-src/asrouter/docs/targeting-attributes.md
  content-src/asrouter/templates/OnboardingMessage/OnboardingMessage.jsx
  content-src/asrouter/templates/OnboardingMessage/_OnboardingMessage.scss
  content-src/asrouter/templates/StartupOverlay/StartupOverlay.jsx
  content-src/asrouter/templates/Trailhead/Trailhead.jsx
  content-src/asrouter/templates/Trailhead/_Trailhead.scss
  content-src/components/ASRouterAdmin/ASRouterAdmin.jsx
  content-src/components/ASRouterAdmin/ASRouterAdmin.scss
  content-src/components/Base/Base.jsx
  content-src/components/Search/_Search.scss
  content-src/styles/_activity-stream.scss
  content-src/styles/_theme.scss
  content-src/styles/_variables.scss
  data/content/assets/sync-devices-trailhead.svg
  data/content/assets/trailhead/accounts-form-bg.jpg
  data/content/assets/trailhead/benefit-knowledge.png
  data/content/assets/trailhead/benefit-privacy.png
  data/content/assets/trailhead/benefit-products.png
  data/content/assets/trailhead/card-illo-devices.png
  data/content/assets/trailhead/card-illo-fbcont.png
  data/content/assets/trailhead/card-illo-ffmonitor.png
  data/content/assets/trailhead/card-illo-ffsend.png
  data/content/assets/trailhead/card-illo-lockwise.png
  data/content/assets/trailhead/card-illo-mobile.png
  data/content/assets/trailhead/card-illo-pledge.png
  data/content/assets/trailhead/card-illo-pocket.png
  data/content/assets/trailhead/card-illo-private.png
  data/content/assets/trailhead/card-illo-sendtab.png
  data/content/assets/trailhead/card-illo-tracking.png
  data/content/assets/trailhead/firefox-logo.png
  docs/v2-system-addon/data_events.md
  lib/ASRouter.jsm
  lib/OnboardingMessageProvider.jsm
  lib/TelemetryFeed.jsm
  lib/UTEventReporting.jsm
  mochitest.sh
  package-lock.json
  package.json
  test/schemas/pings.js
  test/unit/asrouter/ASRouter.test.js
  test/unit/asrouter/ASRouterTargeting.test.js
  test/unit/asrouter/ModalOverlay.test.jsx
  test/unit/asrouter/TargetingDocs.test.js
  test/unit/asrouter/asrouter-content.test.jsx
  test/unit/asrouter/templates/OnboardingMessage.test.jsx
  test/unit/asrouter/templates/Trailhead.test.jsx
  test/unit/content-src/components/ASRouterAdmin.test.jsx
  test/unit/lib/TelemetryFeed.test.js
  test/unit/lib/UTEventReporting.test.js
  test/unit/unit-entry.js
  yamscripts.yml
Labels: PR / Needs review

#5014 Bug 1417163 - Show ellipsis at end of long title and description texts with line-clamp
  content-src/styles/_mixins.scss
Labels: PR / Needs review

#5017 Bug 1550723 - An inactive horizontal scrollbar is displayed at the bottom of the about:welcome pages which contain a modal
  content-src/asrouter/templates/Trailhead/_Trailhead.scss
Labels: PR / Needs review

#5015 Bug 1550566 - Retrieve `deviceID` parameter from FxA metrics endpoint and append as additional query parameter for FxA flows
  content-src/asrouter/templates/StartupOverlay/StartupOverlay.jsx
  content-src/asrouter/templates/Trailhead/Trailhead.jsx
  test/unit/asrouter/templates/Trailhead.test.jsx
Labels: PR / Needs review

#5016 Bug 1550642 - Improve accessibility of autofocused email
  content-src/asrouter/templates/Trailhead/Trailhead.jsx
Labels: PR / Needs review

#5019 Bug 1550614 - Mobile image accidentally includes Lockwise in the background
  data/content/assets/trailhead/card-illo-mobile.png
Labels: PR / R+

#5022 Bug 1550842 - Console warnings make it seem like newtab is using cookies
  content-src/components/DiscoveryStreamComponents/DSImage/DSImage.jsx
  content-src/components/DiscoveryStreamComponents/DSImage/_DSImage.scss
Labels: PR / Needs review

#5013 Bug 1550065 - Add telemetry for Return to AMO experience
  content-src/asrouter/asrouter-content.jsx
  content-src/asrouter/templates/ReturnToAMO/ReturnToAMO.jsx
  docs/v2-system-addon/data_events.md
  test/unit/content-src/components/ReturnToAMO.test.jsx
Labels: PR / R+

#5023 Bug 1551207 - No telemetry ping is sent if the "First Run Cards" are dismissed
  content-src/asrouter/asrouter-content.jsx
  content-src/asrouter/components/ModalOverlay/ModalOverlay.jsx
  content-src/asrouter/templates/Trailhead/Trailhead.jsx
  test/unit/asrouter/asrouter-content.test.jsx
Labels: PR / R+ with nits

#4992 Bug 1544578 - TopStoriesFeed early return for discovery stream
  lib/ActivityStream.jsm
  lib/TopStoriesFeed.jsm
  test/unit/lib/TopStoriesFeed.test.js
Labels: PR / R+ with nits

#5026 Bug 1550149 - About preferences switch Recommended by Pocket descript…
  lib/AboutPreferences.jsm
  test/unit/lib/AboutPreferences.test.js
Labels: PR / Needs review

#5028 Bug 1551677 - Improve accessibility of trailhead dialog
  content-src/asrouter/templates/Trailhead/Trailhead.jsx
  test/unit/asrouter/templates/Trailhead.test.jsx
Labels: PR / On hold for now

#5018 Bug 1550714 - Notify all tabs of messages that have become invalid of…
  common/Actions.jsm
  content-src/asrouter/asrouter-content.jsx
  lib/ASRouter.jsm
  lib/ASRouterPreferences.jsm
  test/unit/asrouter/ASRouter.test.js
  test/unit/asrouter/ASRouterPreferences.test.js
Labels: PR / R+

#5029 Bug 1551566 - Enable jsx-a11y eslint for ASRouterAdmin/asrouter directory and fix errors
  content-src/asrouter/components/RichText/RichText.jsx
  content-src/asrouter/templates/ReturnToAMO/ReturnToAMO.jsx
  content-src/asrouter/templates/SimpleBelowSearchSnippet/SimpleBelowSearchSnippet.jsx
  content-src/asrouter/templates/SimpleSnippet/SimpleSnippet.jsx
  content-src/asrouter/templates/SubmitFormSnippet/SubmitFormSnippet.jsx
  content-src/components/ASRouterAdmin/ASRouterAdmin.jsx
  package.json
  test/unit/content-src/components/ASRouterAdmin.test.jsx
  yamscripts.yml
Labels: PR / R+

#5032 Bug 1551832 - Onboarding button label not wrapping
  content-src/asrouter/templates/Trailhead/_Trailhead.scss
Labels: PR / R+

#4986 Bug 1522166 - Switch between light and dark icon in snippet messages
  content-src/asrouter/components/SnippetBase/_SnippetBase.scss
  content-src/asrouter/templates/EOYSnippet/EOYSnippet.schema.json
  content-src/asrouter/templates/FXASignupSnippet/FXASignupSnippet.schema.json
  content-src/asrouter/templates/NewsletterSnippet/NewsletterSnippet.schema.json
  content-src/asrouter/templates/SendToDeviceSnippet/SendToDeviceSnippet.schema.json
  content-src/asrouter/templates/SimpleBelowSearchSnippet/SimpleBelowSearchSnippet.jsx
  content-src/asrouter/templates/SimpleBelowSearchSnippet/SimpleBelowSearchSnippet.schema.json
  content-src/asrouter/templates/SimpleSnippet/SimpleSnippet.jsx
  content-src/asrouter/templates/SimpleSnippet/SimpleSnippet.schema.json
  content-src/asrouter/templates/SubmitFormSnippet/SubmitFormSnippet.jsx
  content-src/asrouter/templates/SubmitFormSnippet/SubmitFormSnippet.schema.json
  lib/SnippetsTestMessageProvider.jsm
  test/unit/asrouter/templates/SimpleBelowSearchSnippet.test.jsx
  test/unit/asrouter/templates/SimpleSnippet.test.jsx
  test/unit/asrouter/templates/SubmitFormSnippet.test.jsx
Labels: PR / R+ with nits

#5033 Bug 1546429 - Add mochitest coverage of Special FXA (Below Search) Snippet
  test/browser/browser.ini
  test/browser/browser_asrouter_snippets.js
Labels: PR / R+ with nits

#5031 Bug 1552009 - Remove husky in order to support mozilla-central-first workflow
  contributing.md
  hooks/pre-push
  package-lock.json
  package.json
  yamscripts.yml
Labels: PR / R+

#5037 Bug 1552237 - Fixing broken filter
  content-src/lib/selectLayoutRender.js
  test/unit/content-src/lib/selectLayoutRender.test.js
Labels: PR / R+

#5024 Bug 1550107 - Insert placeholders on feed cards while they load and slight spoc adjustment.
  content-src/components/DiscoveryStreamComponents/CardGrid/CardGrid.jsx
  content-src/components/DiscoveryStreamComponents/Hero/Hero.jsx
  content-src/components/DiscoveryStreamComponents/List/List.jsx
  content-src/lib/selectLayoutRender.js
  test/unit/content-src/lib/selectLayoutRender.test.js
Labels: PR / R+

#5036 Bug 1550649 - Should not roll trailhead branch if has addons attribution data
  lib/ASRouter.jsm
  test/unit/asrouter/ASRouter.test.js
Labels: PR / R+

#5027 Bug 1551248 Fixing dark vs light theme issue
  content-src/components/DiscoveryStreamComponents/List/_List.scss
Labels: PR / R+

#5034 Bug 1552013 - Update README in browser/components/newtab to reflect mc-based workflow
  .mcignore
  README.md
  docs/index.rst
  moz.build
Labels: PR / R+ with nits

#5038 Bug 1549688 - Return early if BookmarkPanelHub is not initialized
  lib/BookmarkPanelHub.jsm
  test/unit/lib/BookmarkPanelHub.test.js
Labels: PR / R+ with nits

#5025 Bug 1551359 - Fill cards with longer excerpts for shorter titles
  content-src/components/DiscoveryStreamComponents/DSCard/DSCard.jsx
  content-src/components/DiscoveryStreamComponents/Hero/Hero.jsx
  content-src/components/DiscoveryStreamComponents/List/List.jsx
  content-src/lib/clamp-total-lines.js
  content-src/styles/_activity-stream.scss
  content-src/styles/_mixins.scss
  test/unit/content-src/lib/clamp-total-lines.test.js
Labels: PR / Needs review

#5020 Bug 1548917 - [Accessibility] Focus state refinements
  content-src/components/DiscoveryStreamComponents/CardGrid/_CardGrid.scss
  content-src/components/DiscoveryStreamComponents/DSCard/_DSCard.scss
  content-src/styles/_mixins.scss
  content-src/styles/_variables.scss
Labels: PR / R+

#5035 Bug 1551613 - Enable jsx-a11y eslint for TopSites component and fix errors
  content-src/components/A11yLinkButton/A11yLinkButton.jsx
  content-src/components/A11yLinkButton/_A11yLinkButton.scss
  content-src/components/ASRouterAdmin/ASRouterAdmin.jsx
  content-src/components/TopSites/TopSite.jsx
  content-src/components/TopSites/TopSiteForm.jsx
  content-src/components/TopSites/TopSiteFormInput.jsx
  content-src/components/TopSites/TopSites.jsx
  content-src/components/TopSites/_TopSites.scss
  content-src/styles/_activity-stream.scss
  content-src/styles/_icons.scss
  package.json
  test/unit/content-src/components/ASRouterAdmin.test.jsx
  test/unit/content-src/components/TopSites.test.jsx
  yamscripts.yml
Labels: PR / R+

#5041 Bug 1528447 - Long source domains should get truncated with ellipsis
  content-src/components/DiscoveryStreamComponents/DSCard/DSCard.jsx
  content-src/components/DiscoveryStreamComponents/Hero/Hero.jsx
  content-src/components/DiscoveryStreamComponents/Hero/_Hero.scss
  content-src/components/DiscoveryStreamComponents/List/List.jsx
  content-src/components/DiscoveryStreamComponents/List/_List.scss
  content-src/styles/_activity-stream.scss
Labels: PR / R+

#5045 Bug 1550217 - Pref on Trailhead with desired experimentation for 67.0.5
  lib/ASRouter.jsm
Labels: PR / R+

#5046 Bug 1550858 - Update final final final final final actions or urls
  lib/OnboardingMessageProvider.jsm
Labels: PR / R+

#5053 Bug 1553205 - FxA metrics values sometimes don't get set
  content-src/asrouter/templates/Trailhead/Trailhead.jsx
Labels: PR / Needs review

#5050 Bug 1550861 - Trailhead final uplift
  content-src/asrouter/asrouter-content.jsx
  content-src/asrouter/components/ModalOverlay/ModalOverlay.jsx
  content-src/asrouter/templates/StartupOverlay/StartupOverlay.jsx
  content-src/asrouter/templates/Trailhead/Trailhead.jsx
  content-src/asrouter/templates/Trailhead/_Trailhead.scss
  data/content/assets/trailhead/card-illo-mobile.png
  lib/ASRouter.jsm
  lib/OnboardingMessageProvider.jsm
  locales-src/ach/strings.properties
  locales-src/cs/strings.properties
  locales-src/de/strings.properties
  locales-src/el/strings.properties
  locales-src/es-ES/strings.properties
  locales-src/es-MX/strings.properties
  locales-src/eu/strings.properties
  locales-src/gd/strings.properties
  locales-src/he/strings.properties
  locales-src/ia/strings.properties
  locales-src/it/strings.properties
  locales-src/ka/strings.properties
  locales-src/lij/strings.properties
  locales-src/lt/strings.properties
  locales-src/ml/strings.properties
  locales-src/my/strings.properties
  locales-src/pa-IN/strings.properties
  locales-src/pt-BR/strings.properties
  locales-src/ro/strings.properties
  locales-src/sk/strings.properties
  locales-src/ta/strings.properties
  locales-src/ur/strings.properties
  locales-src/vi/strings.properties
  locales-src/zh-CN/strings.properties
  locales-src/zh-TW/strings.properties
  test/unit/asrouter/ASRouter.test.js
  test/unit/asrouter/asrouter-content.test.jsx
  test/unit/asrouter/templates/Trailhead.test.jsx
Labels: PR / R+

#5052 Bug 1548516 - Add mochitest coverage for bookmark panel message
  test/browser/browser.ini
  test/browser/browser_asrouter_bookmarkpanel.js
Labels: PR / R+

#5056 (nobug) - await BrowserTestUtils.waitForCondition
  test/browser/browser_asrouter_cfr.js
Labels: PR / R+

#5055 Bug 1553450 - Disable asrouter devtoolsEnabled in mochitest environment
  test/browser/browser.ini
  test/browser/browser_asrouter_snippets.js
Labels: PR / R+

#5057 Bug 1531734 - Remove pref migration code in FFx69
  lib/ASRouterPreferences.jsm
  lib/ActivityStream.jsm
  lib/PrefsFeed.jsm
  test/unit/asrouter/ASRouterPreferences.test.js
  test/unit/lib/ActivityStream.test.js
  test/unit/lib/PrefsFeed.test.js
Labels: PR / Needs review

#5054 Bug 1552179 - Turn on eslint-a11y for the rest of the content-src folder
  content-src/components/CollapsibleSection/CollapsibleSection.jsx
  content-src/components/ConfirmDialog/ConfirmDialog.jsx
  content-src/components/ContextMenu/ContextMenu.jsx
  content-src/components/ContextMenu/_ContextMenu.scss
  content-src/components/DiscoveryStreamComponents/DSImage/DSImage.jsx
  content-src/components/ErrorBoundary/ErrorBoundary.jsx
  package.json
  test/browser/browser_highlights_section.js
  test/browser/browser_topsites_contextMenu_options.js
  test/browser/browser_topsites_section.js
  test/unit/content-src/components/ContextMenu.test.jsx
  test/unit/content-src/components/ErrorBoundary.test.jsx
  yamscripts.yml
Labels: PR / R+

#5043 Bug 1550160 - Clean up unused card CSS
  content-src/components/DiscoveryStreamComponents/DSCard/_DSCard.scss
Labels: PR / R+

#5061 (nobug) - Increase DSImage to 100% coverage
  test/unit/content-src/components/DiscoveryStreamComponents/DSImage.test.jsx
Labels: PR / Needs review

#5044 Bug 1552596 - Revert dynamic line clamping in favor of performant static line clamping
  content-src/components/DiscoveryStreamComponents/DSCard/DSCard.jsx
  content-src/components/DiscoveryStreamComponents/DSCard/_DSCard.scss
  content-src/components/DiscoveryStreamComponents/Hero/Hero.jsx
  content-src/components/DiscoveryStreamComponents/Hero/_Hero.scss
  content-src/components/DiscoveryStreamComponents/List/List.jsx
  content-src/components/DiscoveryStreamComponents/List/_List.scss
  content-src/lib/clamp-total-lines.js
  content-src/styles/_mixins.scss
  test/unit/content-src/lib/clamp-total-lines.test.js
Labels: PR / Needs review

#5063 Bug 1553234 - Set the aria-expanded attribute of collapsible sections
  content-src/components/CollapsibleSection/CollapsibleSection.jsx
Labels: PR / R+ with nits

#5066 Bug 1554125 - add mochitest coverage for about:welcome
  test/browser/browser.ini
  test/browser/browser_aboutwelcome.js
Labels: PR / R+

#5059 Bug 1552888 - Typography and padding adjustments
  content-src/components/DiscoveryStreamComponents/CardGrid/_CardGrid.scss
  content-src/components/DiscoveryStreamComponents/DSCard/_DSCard.scss
  content-src/components/DiscoveryStreamComponents/Hero/_Hero.scss
Labels: PR / Needs review

#5069 chore(Doc) - Update the telemetry checklist
  docs/v2-system-addon/telemetry.md
Labels: PR / R+

#5068 Bug 1539378 - personality provider update
  lib/PersonalityProvider.jsm
Labels: PR / R+

#5071 chore(doc) - Update the Remote CFR documentation with info about the …
  docs/v2-system-addon/remote_cfr.md
Labels: PR / R+

#5074 Bug 1555048 - Ensure impression observer element is in correct spot
  content-src/components/DiscoveryStreamImpressionStats/_ImpressionStats.scss
Labels: PR / R+

#5075 Bug 1548043 - Changing to personal computer emoji for wider support
  lib/DiscoveryStreamFeed.jsm
Labels: PR / Needs review

#5076 Backport Bug 1553917 - Make eslint compatible with mozilla central
  .eslintignore
  .eslintrc.js
  .eslintrc.jsx-a11y.js
  mochitest.sh
  package.json
  yamscripts.yml
Labels: PR / R+ with nits

#5060 Bug 1552195 - Support the escape button for closing all modals
  content-src/asrouter/components/ModalOverlay/ModalOverlay.jsx
  content-src/asrouter/components/ModalOverlay/_ModalOverlay.scss
  content-src/asrouter/templates/OnboardingMessage/OnboardingMessage.jsx
  content-src/asrouter/templates/OnboardingMessage/_OnboardingMessage.scss
  content-src/components/ASRouterAdmin/ASRouterAdmin.jsx
  content-src/components/ASRouterAdmin/ASRouterAdmin.scss
  content-src/components/ContextMenu/ContextMenu.jsx
  content-src/components/TopSites/TopSites.jsx
  test/browser/browser_topsites_section.js
Labels: PR / R+

#5078 Bug 1555390 - Remove prerendering in AboutNewTabService
  AboutNewTabService.jsm
  nsIAboutNewTabService.idl
  test/browser/browser_packaged_as_locales.js
  test/xpcshell/test_AboutNewTabService.js
Labels: PR / R+

#5072 Bug 1535328 - Update dev dependencies
  loaders/inject-loader.js
  package-lock.json
  package.json
Labels: PR / R+

#5080 Bug 1555391 - Remove PrerenderData.jsm and usages
  common/PrerenderData.jsm
  content-src/activity-stream-prerender.jsx
  content-src/activity-stream.jsx
  content-src/components/Base/Base.jsx
  content-src/components/Base/_Base.scss
  lib/PrefsFeed.jsm
  test/unit/activity-stream-prerender.test.jsx
  test/unit/common/PrerenderData.test.js
  test/unit/lib/PrefsFeed.test.js
Labels: PR / R+

#5081 Bug 1555393 - Remove activity-stream-prerender.jsx and build code
  .eslintignore
  .gitignore
  .mcignore
  bin/render-activity-stream-html.js
  content-src/activity-stream-prerender.jsx
  jar.mn
  package.json
  webpack.prerender.config.js
  yamscripts.yml
Labels: PR / R+

#5082 Bug 1553375 - Remove react prerendering of placeholders (props, actions, telemetry)
  common/Actions.jsm
  common/PerfService.jsm
  content-src/activity-stream.jsx
  content-src/components/Base/Base.jsx
  content-src/lib/init-store.js
  docs/v2-system-addon/data_dictionary.md
  docs/v2-system-addon/data_events.md
  lib/TelemetryFeed.jsm
  test/schemas/pings.js
  test/unit/content-src/lib/init-store.test.js
  test/unit/lib/TelemetryFeed.test.js
Labels: PR / R+

#5073 Bug 1548697 - Upgrade prod dependencies
  content-src/asrouter/asrouter-content.jsx
  content-src/asrouter/rich-text-strings.js
  package-lock.json
  package.json
Labels: PR / R+
