Repository mozilla/activity-stream, pull requests merged in 2019-09, with the labels that each got.

#5301 Bug 1577654 - Design tweaks for TextPromo
  content-src/components/DiscoveryStreamBase/DiscoveryStreamBase.jsx
  content-src/components/DiscoveryStreamComponents/DSDismiss/DSDismiss.jsx
  content-src/components/DiscoveryStreamComponents/DSTextPromo/_DSTextPromo.scss
Labels: PR / R+

#5296 Bug 1575820 - Show extended triplets on new tab after sync login
  lib/ASRouter.jsm
Labels: PR / Needs review

#5285 Bug 1577279 - mach lint complains about newtab due to eslint version mismatch
  .eslintrc.js
  package-lock.json
  package.json
  yamscripts.yml
Labels: PR / R+ with nits

#5299 [fix snippets-service #862] Add SubmitForm error button label.
  content-src/asrouter/templates/FXASignupSnippet/FXASignupSnippet.jsx
  content-src/asrouter/templates/FXASignupSnippet/FXASignupSnippet.schema.json
  content-src/asrouter/templates/NewsletterSnippet/NewsletterSnippet.jsx
  content-src/asrouter/templates/NewsletterSnippet/NewsletterSnippet.schema.json
  content-src/asrouter/templates/SendToDeviceSnippet/SendToDeviceSnippet.jsx
  content-src/asrouter/templates/SendToDeviceSnippet/SendToDeviceSnippet.schema.json
  content-src/asrouter/templates/SubmitFormSnippet/SubmitFormSnippet.jsx
  content-src/asrouter/templates/SubmitFormSnippet/SubmitFormSnippet.schema.json
  lib/SnippetsTestMessageProvider.jsm
  test/unit/asrouter/templates/FXASignupSnippet.test.jsx
  test/unit/asrouter/templates/NewsletterSnippet.test.jsx
  test/unit/asrouter/templates/SendToDeviceSnippet.test.jsx
  test/unit/asrouter/templates/SubmitFormSnippet.test.jsx
Labels: PR / R+

#5293 Bug 1561880 - Refactor browser window listeners to use EveryWindow.jsm
  lib/ASRouter.jsm
  lib/ASRouterTriggerListeners.jsm
  test/unit/asrouter/ASRouterTriggerListeners.test.js
  test/unit/unit-entry.js
Labels: PR / R+

#5305 Bug 1559185 - Use existing default prefs for dynamic prefs too
  lib/ActivityStream.jsm
  test/unit/lib/ActivityStream.test.js
  test/unit/utils.js
Labels: PR / R+

#5228 Bug 1572059 - Need ASRouterTriggerListeners to trigger on bookmarked pages
  content-src/asrouter/docs/targeting-attributes.md
  lib/ASRouter.jsm
  lib/ASRouterTargeting.jsm
  lib/ASRouterTriggerListeners.jsm
  lib/PanelTestProvider.jsm
  test/unit/asrouter/ASRouter.test.js
  test/unit/asrouter/ASRouterFeed.test.js
  test/unit/asrouter/ASRouterTriggerListeners.test.js
  test/unit/asrouter/PanelTestProvider.test.js
Labels: PR / R+

#5298 Bug 1561942 - Messaging System devtools support for What's New panel
  lib/ASRouter.jsm
  lib/ToolbarPanelHub.jsm
  test/unit/asrouter/ASRouter.test.js
  test/unit/lib/ToolbarPanelHub.test.js
Labels: PR / Needs review

#5294 [fix bug 1546165] Add optional heading/icon to snippets:
  content-src/asrouter/components/ConditionalWrapper/ConditionalWrapper.jsx
  content-src/asrouter/templates/FXASignupSnippet/FXASignupSnippet.schema.json
  content-src/asrouter/templates/NewsletterSnippet/NewsletterSnippet.schema.json
  content-src/asrouter/templates/SendToDeviceSnippet/SendToDeviceSnippet.schema.json
  content-src/asrouter/templates/SimpleSnippet/SimpleSnippet.jsx
  content-src/asrouter/templates/SubmitFormSnippet/SubmitFormSnippet.schema.json
  contributing.md
  lib/SnippetsTestMessageProvider.jsm
Labels: PR / Needs review

#5306 Bug 1577655 - Dismiss wrapper design tweaks
  content-src/components/DiscoveryStreamComponents/DSDismiss/DSDismiss.jsx
  content-src/components/DiscoveryStreamComponents/DSDismiss/_DSDismiss.scss
  content-src/components/DiscoveryStreamComponents/DSTextPromo/_DSTextPromo.scss
Labels: PR / Needs review

#5312 Bug 1569700 - CFR: recommend firefox send for PDFs
  lib/ASRouterTriggerListeners.jsm
  lib/PanelTestProvider.jsm
  test/unit/asrouter/PanelTestProvider.test.js
Labels: PR / R+

#5260 Bug 1570332 - Expose user prefs values to targeting expressions
  content-src/asrouter/docs/targeting-attributes.md
  lib/ASRouterTargeting.jsm
  test/browser/browser_asrouter_targeting.js
  test/unit/unit-entry.js
Labels: PR / R+ with nits

#5319 Bug 1582005 - Add bucket_id as a required field
  content-src/asrouter/templates/OnboardingMessage/WhatsNewMessage.schema.json
  lib/PanelTestProvider.jsm
Labels: PR / R+

#5317 (nobug) - Include provider name in React key to allow duplicate messa…
  content-src/components/ASRouterAdmin/ASRouterAdmin.jsx
Labels: PR / R+

#5320 Bug 1582061 - What's New links open twice when accessed with 'Space' key
  lib/ToolbarPanelHub.jsm
  test/unit/lib/ToolbarPanelHub.test.js
Labels: PR / R+

#5328 Bug 1581570 - Spocs placement bug impacting non placements fixed (#5310)
  common/Reducers.jsm
  test/unit/common/Reducers.test.js
Labels: Uplift Needed

#5329 Bug 1584625 - browser_aboutwelcome.js mochitest fails when run twice
  test/browser/browser_onboarding_rtamo.js
Labels: PR / R+

#5316 Bug 1581618 - Remove old about:welcome control variant
  .eslintrc.js
  content-src/asrouter/asrouter-content.jsx
  content-src/asrouter/templates/FirstRun/Interrupt.jsx
  content-src/asrouter/templates/StartupOverlay/StartupOverlay.jsx
  content-src/asrouter/templates/StartupOverlay/_StartupOverlay.scss
  content-src/asrouter/templates/Trailhead/_Trailhead.scss
  content-src/styles/_activity-stream.scss
  data/content/assets/fox-tail.png
  data/content/assets/sync-devices.svg
  lib/ASRouter.jsm
  lib/OnboardingMessageProvider.jsm
  locales-src/onboarding.ftl
  test/browser/browser_aboutwelcome.js
  test/browser/browser_onboarding_rtamo.js
  test/unit/asrouter/ASRouter.test.js
  test/unit/asrouter/ASRouterTargeting.test.js
  test/unit/asrouter/templates/Interrupt.test.jsx
  test/unit/content-src/components/StartupOverlay.test.jsx
Labels: PR / R+

#5318 Bug 1576680 - Telemetry additions for SPOC Topsites
  content-src/components/TopSites/TopSite.jsx
  docs/v2-system-addon/data_dictionary.md
  docs/v2-system-addon/data_events.md
  test/schemas/pings.js
  test/unit/content-src/components/TopSites.test.jsx
Labels: PR / R+
