Repository mozilla/activity-stream, pull requests merged in 2019-08, with the labels that each got.

#5201 Bug 1568909 - Show triplets for extended period after first run
  content-src/asrouter/asrouter-content.jsx
  content-src/asrouter/templates/FirstRun/FirstRun.jsx
  docs/v2-system-addon/data_events.md
  lib/ASRouter.jsm
  lib/OnboardingMessageProvider.jsm
  test/unit/asrouter/ASRouter.test.js
Labels: PR / R+, fx69

#5214 Bug 1570192 - Potential perf fixes in DS image onSeen
  content-src/components/DiscoveryStreamComponents/DSImage/DSImage.jsx
  test/unit/content-src/components/DiscoveryStreamComponents/DSImage.test.jsx
Labels: PR / Needs review

#5207 Bug 1569020 - Add a new badge action for setting homepage_override pref
  content-src/asrouter/templates/OnboardingMessage/UpdateAction.schema.json
  lib/ASRouter.jsm
  lib/PanelTestProvider.jsm
  lib/ToolbarBadgeHub.jsm
  test/unit/asrouter/ASRouter.test.js
  test/unit/asrouter/PanelTestProvider.test.js
  test/unit/lib/ToolbarBadgeHub.test.js
Labels: PR / R+ with nits, fx69

#5208 Bug 1569597 - Updated schema & template, added test snippet with corr…
  content-src/asrouter/asrouter-content.jsx
  content-src/asrouter/templates/SimpleBelowSearchSnippet/SimpleBelowSearchSnippet.jsx
  content-src/asrouter/templates/SimpleBelowSearchSnippet/SimpleBelowSearchSnippet.schema.json
  content-src/asrouter/templates/SimpleBelowSearchSnippet/_SimpleBelowSearchSnippet.scss
  content-src/asrouter/templates/SimpleSnippet/SimpleSnippet.jsx
  content-src/components/Base/_Base.scss
  content-src/components/Search/_Search.scss
  lib/SnippetsTestMessageProvider.jsm
Labels: PR / R+, fx69

#5219 Bug 1570219 - The What's new message icon is missing alternative text
  content-src/asrouter/templates/OnboardingMessage/WhatsNewMessage.schema.json
  lib/PanelTestProvider.jsm
  lib/ToolbarPanelHub.jsm
  test/unit/lib/ToolbarPanelHub.test.js
Labels: PR / Needs review

#5222 Bug 1570745 - Fix failing mochitests due to CFR message reference fro…
  test/browser/browser_asrouter_toolbarbadge.js
Labels: PR / R+

#5223 Bug 1571846 - Moments pref reset issue
  lib/ASRouter.jsm
  lib/ToolbarBadgeHub.jsm
  test/unit/lib/ToolbarBadgeHub.test.js
Labels: PR / R+

#5226 Bug 1571818 - handleMessageRequest method does not consider trigger p…
  lib/ASRouter.jsm
  test/unit/asrouter/ASRouter.test.js
Labels: PR / Needs review

#5224 Bug 1571435 - Overrode the .active class for snippets with buttons, t…
  content-src/asrouter/templates/SimpleBelowSearchSnippet/_SimpleBelowSearchSnippet.scss
Labels: PR / R+

#5211 Bug 1567272 - Enabling DS for CA
  lib/ActivityStream.jsm
Labels: PR / Needs review

#5196 Bug 1540842 - Adding "Saved to Pocket" parity to Discovery Stream
  AboutNewTabService.jsm
  bin/render-activity-stream-html.js
  bin/vendor.js
  common/Reducers.jsm
  content-src/components/Card/types.js
  content-src/components/DiscoveryStreamComponents/CardGrid/CardGrid.jsx
  content-src/components/DiscoveryStreamComponents/DSCard/DSCard.jsx
  content-src/components/DiscoveryStreamComponents/DSCard/_DSCard.scss
  content-src/components/DiscoveryStreamComponents/DSContextFooter/DSContextFooter.jsx
  content-src/components/DiscoveryStreamComponents/DSContextFooter/_DSContextFooter.scss
  content-src/styles/_activity-stream.scss
  data/content/assets/icon-removed-bookmark.svg
  jar.mn
  locales-src/newtab.ftl
  package-lock.json
  package.json
  test/unit/content-src/components/DiscoveryStreamComponents/DSContextFooter.test.jsx
  vendor/REACT_TRANSITION_GROUP_LICENSE
  vendor/react-transition-group.js
  webpack.system-addon.config.js
Labels: PR / R+ with nits

#5227 Bug 1571441 - Fixed snippet width and block button position on smaller screens
  content-src/asrouter/templates/SimpleBelowSearchSnippet/_SimpleBelowSearchSnippet.scss
  content-src/components/Base/_Base.scss
Labels: PR / R+

#5233 Bug 1571817 - Hold back rollout test for Extended Triplets
  lib/ASRouter.jsm
  test/unit/asrouter/ASRouter.test.js
Labels: PR / R+ with nits

#5234 Bug 1572378 - Unable to install extension from RTAMO overlay
  content-src/asrouter/templates/FirstRun/FirstRun.jsx
  test/unit/asrouter/templates/FirstRun.test.jsx
Labels: PR / R+

#5231 Bug 1571023 - Added new strings for Sync, Send Tab and Firefox Send.
  lib/CFRPageActions.jsm
  locales-src/asrouter.ftl
Labels: PR / R+, fx69

#5236 Bug 1570754 - Add delay to clearing triplets and always block extended
  content-src/asrouter/asrouter-content.jsx
  content-src/asrouter/templates/FirstRun/FirstRun.jsx
  content-src/asrouter/templates/Trailhead/_Trailhead.scss
  lib/OnboardingMessageProvider.jsm
  test/unit/asrouter/templates/FirstRun.test.jsx
Labels: PR / R+ with nits, fx69

#5238 (nobug) - Run test for webextension topSites that uses redux state
  mochitest.sh
Labels: PR / Needs review

#5206 Pocket New Tab should display "Save to Pocket" for Hero and List components
  content-src/components/DiscoveryStreamComponents/DSContextFooter/DSContextFooter.jsx
  content-src/components/DiscoveryStreamComponents/DSContextFooter/_DSContextFooter.scss
  content-src/components/DiscoveryStreamComponents/Hero/Hero.jsx
  content-src/components/DiscoveryStreamComponents/Hero/_Hero.scss
  content-src/components/DiscoveryStreamComponents/List/List.jsx
  content-src/components/DiscoveryStreamComponents/List/_List.scss
  test/unit/content-src/components/DiscoveryStreamComponents/DSCard.test.jsx
  test/unit/content-src/components/DiscoveryStreamComponents/DSContextFooter.test.jsx
  test/unit/content-src/components/DiscoveryStreamComponents/Hero.test.jsx
  test/unit/content-src/components/DiscoveryStreamComponents/List.test.jsx
Labels: PR / Needs review

#5235 Bug 1572463 - Fixes for the Special Monitor Snippet
  content-src/asrouter/templates/SimpleBelowSearchSnippet/SimpleBelowSearchSnippet.jsx
  content-src/asrouter/templates/SimpleBelowSearchSnippet/_SimpleBelowSearchSnippet.scss
  lib/SnippetsTestMessageProvider.jsm
Labels: PR / R+ with nits, fx69

#5240 Bug 1571442 - Search box shouldn't move down with extended Triplets on
  content-src/asrouter/templates/Trailhead/_Trailhead.scss
Labels: PR / Needs review

#5216 Bug 1566545 - Card UI spoc variants
  content-src/components/DiscoveryStreamBase/DiscoveryStreamBase.jsx
  content-src/components/DiscoveryStreamComponents/CardGrid/CardGrid.jsx
  content-src/components/DiscoveryStreamComponents/DSCard/DSCard.jsx
  content-src/components/DiscoveryStreamComponents/DSCard/_DSCard.scss
  content-src/styles/_icons.scss
  content-src/styles/_variables.scss
  data/content/assets/glyph-arrow.svg
  lib/DiscoveryStreamFeed.jsm
  test/unit/content-src/components/DiscoveryStreamComponents/DSCard.test.jsx
Labels: PR / Needs review

#5247 Bug 1573204 - Adding an extra line to pocket stories
  content-src/components/DiscoveryStreamComponents/CardGrid/_CardGrid.scss
  content-src/components/DiscoveryStreamComponents/DSCard/_DSCard.scss
Labels: PR / R+

#5246 Bug 1560260 - System tick can cause no cards to show
  lib/DiscoveryStreamFeed.jsm
Labels: PR / Needs review

#5248 Bug 1573209 - Installing addon from ReturntoAMO shouldnt hide triplets
  content-src/asrouter/asrouter-content.jsx
  content-src/asrouter/templates/FirstRun/FirstRun.jsx
  lib/ASRouter.jsm
  test/unit/asrouter/ASRouter.test.js
  test/unit/asrouter/templates/FirstRun.test.jsx
Labels: PR / Needs review

#5242 Bug 1572841 - Avoid loading JSMs eagerly in Discovery Stream
  lib/DiscoveryStreamFeed.jsm
Labels: PR / Needs review

#5199 Bug 1568262 - Removed unused onboarding strings
  locales-src/onboarding.ftl
  test/unit/asrouter/templates/FirstRun.test.jsx
  test/unit/asrouter/templates/OnboardingMessage.test.jsx
  test/unit/asrouter/templates/Trailhead.test.jsx
  test/unit/asrouter/templates/Triplets.test.jsx
Labels: PR / R+

#5239 Bug 1572441 - Localize Protection panel message
  lib/OnboardingMessageProvider.jsm
  lib/ToolbarPanelHub.jsm
  locales-src/asrouter.ftl
Labels: PR / R+

#5241 Bug 1572556 - Mitigation strategy for 69 DS and Adzerk
  lib/DiscoveryStreamFeed.jsm
  test/unit/lib/DiscoveryStreamFeed.test.js
Labels: PR / R+

#5243 Bug 1571450 - Added a focus highlight to Snippet CTA and dismiss buttons
  content-src/asrouter/components/Button/_Button.scss
  content-src/asrouter/templates/SimpleBelowSearchSnippet/_SimpleBelowSearchSnippet.scss
Labels: PR / R+

#5249 Bug 1573206 - Testing a render change
  content-src/components/DiscoveryStreamComponents/DSCard/DSCard.jsx
  content-src/components/DiscoveryStreamComponents/DSCard/_DSCard.scss
  content-src/components/DiscoveryStreamComponents/Hero/_Hero.scss
  test/unit/content-src/components/DiscoveryStreamComponents/DSCard.test.jsx
Labels: PR / Needs review

#5225 Bug 1571765 - Use requestIdleCallback to do badging work at an approp…
  lib/ToolbarBadgeHub.jsm
  test/unit/lib/ToolbarBadgeHub.test.js
Labels: PR / R+

#5258 (nobug) Docs for Messaging System user actions
  content-src/asrouter/docs/user-actions.md
Labels: PR / Needs review

#5254 Bug 1573930 - FF prefs to control DS
  lib/DiscoveryStreamFeed.jsm
  lib/PrefsFeed.jsm
  lib/TopStoriesFeed.jsm
  test/browser/browser.ini
  test/unit/lib/DiscoveryStreamFeed.test.js
  test/unit/lib/TopStoriesFeed.test.js
Labels: PR / Needs review

#5232 Bug 1565043 - New TextPromo Component
  content-src/components/DiscoveryStreamBase/DiscoveryStreamBase.jsx
  content-src/components/DiscoveryStreamComponents/DSTextPromo/DSTextPromo.jsx
  content-src/components/DiscoveryStreamComponents/DSTextPromo/_DSTextPromo.scss
  content-src/styles/_activity-stream.scss
  content-src/styles/_variables.scss
  data/content/assets/glyph-caret-right.svg
  test/unit/content-src/components/DiscoveryStreamComponents/DSTextPromo.test.jsx
Labels: PR / Needs review

#5263 (nobug) specifying node 8 in readme
  docs/v2-system-addon/1.GETTING_STARTED.md
Labels: PR / R+

#5200 Bug 1567957 - Added aria-hidden to StartupOverlay, ModalOverlay, ReturnToAMO, FirstRun
  content-src/asrouter/templates/FirstRun/Interrupt.jsx
  content-src/asrouter/templates/ReturnToAMO/ReturnToAMO.jsx
  content-src/asrouter/templates/StartupOverlay/StartupOverlay.jsx
  test/unit/content-src/components/ReturnToAMO.test.jsx
  test/unit/content-src/components/StartupOverlay.test.jsx
Labels: PR / R+

#5272 Bug 1561370 - Land strings and images for Firefox 70 What's New messages
  locales-src/asrouter.ftl
Labels: PR / In progress don't review yet

#5264 Bug 1574995 - Update Firefox workmark for the New Tab page
  content-src/components/Search/_Search.scss
  data/content/assets/firefox-wordmark.svg
Labels: PR / Needs review

#5273 Bug 1575888 - Enable the What's New toolbar badge
  lib/OnboardingMessageProvider.jsm
  lib/PanelTestProvider.jsm
  test/unit/asrouter/PanelTestProvider.test.js
  test/unit/lib/ToolbarBadgeHub.test.js
Labels: PR / R+ with nits

#5271 Bug 1575523 - Fixed snippet resizing at smallest breakpoint.
  content-src/asrouter/templates/SimpleBelowSearchSnippet/_SimpleBelowSearchSnippet.scss
Labels: PR / R+

#5267 Bug 1571763 - Message template for tracking protection report in what's new panel
  content-src/asrouter/docs/targeting-attributes.md
  content-src/asrouter/templates/OnboardingMessage/WhatsNewMessage.schema.json
  data/content/assets/protection-report-icon.png
  lib/ASRouter.jsm
  lib/ASRouterTargeting.jsm
  lib/OnboardingMessageProvider.jsm
  lib/PanelTestProvider.jsm
  lib/ToolbarPanelHub.jsm
  test/unit/asrouter/ASRouter.test.js
  test/unit/asrouter/PanelTestProvider.test.js
  test/unit/lib/ToolbarPanelHub.test.js
Labels: PR / R+ with nits

#5283 Bug 1575797 - After downloading a file, 'Top Sites' and 'Highlights' empty: 'Oops, something went wrong loading this content. Refresh page to try again.'
  lib/DownloadsManager.jsm
Labels: PR / Needs review

#5279 Bug 1576207 - Fixed break point overlap at 1121px
  content-src/asrouter/templates/SimpleBelowSearchSnippet/_SimpleBelowSearchSnippet.scss
Labels: PR / R+

#5289 (nobug) - Mochitest: messages are rendered in the What's New panel
  test/browser/browser.ini
  test/browser/browser_asrouter_whatsnewpanel.js
Labels: PR / Needs review

#5291 Bug 1577824 - DS cards limit visible lines back to 3
  content-src/components/DiscoveryStreamComponents/CardGrid/_CardGrid.scss
  content-src/components/DiscoveryStreamComponents/DSCard/_DSCard.scss
Labels: PR / Needs review, fx70

#5290 Bug 1577663 - Card Grid Remove ds-header if empty and margin tweaks
  content-src/components/DiscoveryStreamBase/_DiscoveryStreamBase.scss
  content-src/components/DiscoveryStreamComponents/CardGrid/CardGrid.jsx
  content-src/components/DiscoveryStreamComponents/CardGrid/_CardGrid.scss
Labels: PR / Needs review, fx70

#5276 Bug 1569934 - Switched h3 to h2 for document flow
  content-src/asrouter/templates/OnboardingMessage/OnboardingMessage.jsx
  content-src/asrouter/templates/Trailhead/Trailhead.jsx
  content-src/asrouter/templates/Trailhead/_Trailhead.scss
Labels: PR / R+

#5281 Bug 1576223 - Testing a better image and card load
  content-src/components/DiscoveryStreamComponents/DSCard/DSCard.jsx
  content-src/components/DiscoveryStreamComponents/DSImage/DSImage.jsx
  content-src/components/DiscoveryStreamComponents/DSImage/_DSImage.scss
Labels: PR / Needs review, fx70

#5287 Bug 1577348 - Use dsimage in dstextpromo; add alt text and rounding to dsimage
  content-src/components/DiscoveryStreamBase/DiscoveryStreamBase.jsx
  content-src/components/DiscoveryStreamComponents/DSImage/DSImage.jsx
  content-src/components/DiscoveryStreamComponents/DSTextPromo/DSTextPromo.jsx
  content-src/components/DiscoveryStreamComponents/DSTextPromo/_DSTextPromo.scss
Labels: PR / Needs review, fx70

#5292 Bug 1575888 - Enable the What's New toolbar badge (#5273)
  lib/OnboardingMessageProvider.jsm
  lib/PanelTestProvider.jsm
  test/unit/asrouter/PanelTestProvider.test.js
  test/unit/lib/ToolbarBadgeHub.test.js
Labels: PR / Needs review, fx70
