Repository mozilla/activity-stream, pull requests merged in 2019-04, with the labels that each got.

#4865 How to setup Remote Settings CFR with dev server
  lib/ASRouter.jsm
Labels: PR / R+

#4863 Bug 1527500 - Save to pocket and bookmark menu options
  common/Reducers.jsm
  content-src/components/DiscoveryStreamComponents/CardGrid/CardGrid.jsx
  content-src/components/DiscoveryStreamComponents/DSCard/DSCard.jsx
  content-src/components/DiscoveryStreamComponents/DSLinkMenu/DSLinkMenu.jsx
  content-src/components/DiscoveryStreamComponents/Hero/Hero.jsx
  content-src/components/DiscoveryStreamComponents/List/List.jsx
  content-src/lib/link-menu-options.js
  content-src/styles/_icons.scss
  data/content/assets/glyph-pocket-archive-16.svg
  data/content/assets/glyph-pocket-delete-16.svg
  test/unit/common/Reducers.test.js
  test/unit/content-src/components/DiscoveryStreamComponents/DSLinkMenu.test.jsx
Labels: PR / Needs review

#4845 Bug 1536115 - Update babel dev-dependencies
  .travis.yml
  karma.mc.config.js
  lib/HighlightsFeed.jsm
  package-lock.json
  package.json
  test/unit/asrouter/CFRPageActions.test.js
  test/unit/common/Reducers.test.js
  test/unit/content-src/lib/snippets.test.js
  test/unit/lib/HighlightsFeed.test.js
  test/unit/lib/PersistentCache.test.js
  test/unit/lib/PersonalityProvider.test.js
  test/unit/lib/SectionsManager.test.js
  test/unit/lib/TopSitesFeed.test.js
  webpack.system-addon.config.js
Labels: PR / R+ with nits

#4866 Bug 1445352 - Add code coverage for .jsx files
  karma.mc.config.js
Labels: PR / R+

#4870 (nobug) - Ensure fetch calls don't include credentials
  .eslintrc.js
  bin/strings-import.js
  content-src/asrouter/templates/SubmitFormSnippet/SubmitFormSnippet.jsx
  lib/PersonalityProvider.jsm
  package-lock.json
  package.json
  ping-centre/PingCentre.jsm
  test/browser/browser_activity_stream_strings.js
  test/unit/ping-centre/PingCentre.test.js
Labels: PR / R+

#4869 Bug 1533359 - Targeting support for any subdomain
  content-src/asrouter/schemas/message-format.md
  lib/ASRouter.jsm
  lib/ASRouterTargeting.jsm
  lib/ASRouterTriggerListeners.jsm
  test/browser/browser_asrouter_cfr.js
  test/unit/asrouter/ASRouter.test.js
  test/unit/asrouter/ASRouterTriggerListeners.test.js
Labels: PR / R+

#4879 Bug 1540765 - PersistentCache should do JSON parsing off of the main thread
  lib/PersistentCache.jsm
  test/unit/lib/DiscoveryStreamFeed.test.js
  test/unit/lib/PersistentCache.test.js
Labels: PR / R+

#4878 Bug 1538811 - Document how to setup the dev environment for remote CFR messages
  docs/v2-system-addon/remote_cfr.md
  docs/v2-system-addon/tippytop.md
Labels: PR / R+

#4881 (nobug) - Remove global coverage threshold and move to per file only
  karma.mc.config.js
Labels: PR / R+

#4868 Bug 1530740 - Add loaded content ping for Discovery Stream
  common/Actions.jsm
  content-src/components/DiscoveryStreamImpressionStats/ImpressionStats.jsx
  docs/v2-system-addon/data_events.md
  lib/TelemetryFeed.jsm
  test/unit/content-src/components/DiscoveryStreamComponents/ImpressionStats.test.jsx
  test/unit/lib/TelemetryFeed.test.js
Labels: PR / R+

#4882 Bug 1541543 - Update svg to use context-fill
  data/content/assets/glyph-pocket-archive-16.svg
  data/content/assets/glyph-pocket-delete-16.svg
Labels: PR / Needs review

#4883 Bug 1541359 - Chore: Increase our frontend code coverage
  content-src/components/TopSites/SearchShortcutsForm.jsx
  karma.mc.config.js
  test/unit/content-src/components/DiscoveryStreamBase.test.jsx
  test/unit/content-src/components/DiscoveryStreamComponents/CardGrid.test.jsx
  test/unit/content-src/components/DiscoveryStreamComponents/DSCard.test.jsx
  test/unit/content-src/components/DiscoveryStreamComponents/DSMessage.test.jsx
  test/unit/content-src/components/DiscoveryStreamComponents/HorizontalRule.test.jsx
  test/unit/content-src/components/DiscoveryStreamComponents/Navigation.test.jsx
  test/unit/content-src/components/DiscoveryStreamComponents/SafeAnchor.test.jsx
  test/unit/content-src/components/DiscoveryStreamComponents/SectionTitle.test.jsx
  test/unit/content-src/components/TopSites/SearchShortcutsForm.test.jsx
Labels: PR / R+

#4871 Bug 1539904 - Handle Delete and Archive from pocket link menus when h…
  lib/HighlightsFeed.jsm
  lib/PlacesFeed.jsm
  test/unit/lib/HighlightsFeed.test.js
  test/unit/lib/PlacesFeed.test.js
Labels: PR / R+

#4888 Bug 1539904 - (Followup) Refresh highlights after deleted/archive completes
  common/Actions.jsm
  lib/HighlightsFeed.jsm
  lib/PlacesFeed.jsm
  test/unit/lib/HighlightsFeed.test.js
  test/unit/lib/PlacesFeed.test.js
Labels: PR / R+

#4887 bug 1522301 - Move to non hard coded geo check.
  lib/ActivityStream.jsm
Labels: PR / R+

#4889 Bug 1542792 - Add telemetry to record undesired events for CFR remote messages
  docs/v2-system-addon/data_events.md
  lib/ASRouter.jsm
  test/unit/asrouter/ASRouter.test.js
  test/unit/asrouter/MessageLoaderUtils.test.js
Labels: PR / Awaiting data review, PR / R+ with nits

#4892 (nobug) - Add extra props to DSBase test mounting and remove obsolete file
  test/unit/content-src/components/DiscoveryStreamBase.test.jsx
  test/unit/content-src/components/DiscoveryStreamComponents/DiscoveryStreamBase.test.jsx
Labels: PR / R+

#4886 Bug 1533601 - About preferences settings for discovery stream
  content-src/components/DiscoveryStreamBase/DiscoveryStreamBase.jsx
  content-src/lib/selectLayoutRender.js
  lib/AboutPreferences.jsm
  test/browser/browser.ini
  test/unit/content-src/lib/selectLayoutRender.test.js
  test/unit/lib/AboutPreferences.test.js
Labels: PR / R+ with nits

#4877 Bug 1529983 - Add placeholder when there are no stories to show
  content-src/components/DiscoveryStreamComponents/CardGrid/CardGrid.jsx
  content-src/components/DiscoveryStreamComponents/CardGrid/_CardGrid.scss
  content-src/components/DiscoveryStreamComponents/DSCard/DSCard.jsx
  content-src/components/DiscoveryStreamComponents/DSCard/_DSCard.scss
  content-src/components/DiscoveryStreamComponents/DSEmptyState/DSEmptyState.jsx
  content-src/components/DiscoveryStreamComponents/DSEmptyState/_DSEmptyState.scss
  content-src/components/DiscoveryStreamComponents/Hero/Hero.jsx
  content-src/components/DiscoveryStreamComponents/Hero/_Hero.scss
  content-src/components/DiscoveryStreamComponents/List/List.jsx
  content-src/components/DiscoveryStreamComponents/List/_List.scss
  content-src/styles/_activity-stream.scss
  test/unit/content-src/components/DiscoveryStreamComponents/DSEmptyState.test.jsx
  test/unit/content-src/components/DiscoveryStreamComponents/Hero.test.jsx
  test/unit/content-src/components/DiscoveryStreamComponents/List.test.jsx
Labels: PR / R+

#4890 Bug 1535773 - Allow collapsing of top sites and the rest of Discovery Stream content
  content-src/components/CollapsibleSection/CollapsibleSection.jsx
  content-src/components/DiscoveryStreamBase/DiscoveryStreamBase.jsx
  content-src/components/DiscoveryStreamBase/_DiscoveryStreamBase.scss
  content-src/components/DiscoveryStreamComponents/TopSites/TopSites.jsx
  content-src/components/DiscoveryStreamComponents/TopSites/_TopSites.scss
  content-src/components/SectionMenu/SectionMenu.jsx
  content-src/components/TopSites/TopSites.jsx
  lib/ActivityStream.jsm
  test/unit/content-src/components/DiscoveryStreamBase.test.jsx
Labels: PR / R+

#4894 (nobug) - Remove DarkModeMessage now that dark mode is implemented
  content-src/asrouter/components/Button/_Button.scss
  content-src/asrouter/components/SnippetBase/_SnippetBase.scss
  content-src/components/ASRouterAdmin/ASRouterAdmin.scss
  content-src/components/Base/Base.jsx
  content-src/components/Base/_Base.scss
  content-src/components/Card/_Card.scss
  content-src/components/DarkModeMessage/DarkModeMessage.jsx
  content-src/components/DarkModeMessage/_DarkModeMessage.scss
  content-src/styles/_activity-stream.scss
  content-src/styles/_theme.scss
  content-src/styles/activity-stream-mac.scss
  lib/ActivityStream.jsm
  test/unit/content-src/components/DarkModeMessage.test.jsx
Labels: PR / R+

#4896 Port 1494948: Removed FX_PREFERENCES_OPENED_VIA probe and origin parameter for openPreferences r=jaws,chutten
  lib/ASRouter.jsm
  lib/AboutPreferences.jsm
  test/unit/asrouter/ASRouter.test.js
Labels: PR / R+

#4898 (nobug) - Remove unused strings and exclude them from export
  bin/render-activity-stream-html.js
  locales-src/en-US/strings.properties
Labels: PR / R+

#4885 Bug 1531933 – Use proper image sizes
  content-src/components/DiscoveryStreamComponents/CardGrid/CardGrid.jsx
  content-src/components/DiscoveryStreamComponents/DSCard/DSCard.jsx
  content-src/components/DiscoveryStreamComponents/DSCard/_DSCard.scss
  content-src/components/DiscoveryStreamComponents/DSImage/DSImage.jsx
  content-src/components/DiscoveryStreamComponents/DSImage/DSImage.scss
  content-src/components/DiscoveryStreamComponents/DSImage/cache.js
  content-src/components/DiscoveryStreamComponents/Hero/Hero.jsx
  content-src/components/DiscoveryStreamComponents/Hero/_Hero.scss
  content-src/components/DiscoveryStreamComponents/List/List.jsx
  content-src/components/DiscoveryStreamComponents/List/_List.scss
  content-src/styles/_activity-stream.scss
  test/unit/common/ImgCache.test.js
  test/unit/content-src/components/DiscoveryStreamComponents/DSImage.test.jsx
  test/unit/content-src/components/DiscoveryStreamComponents/List.test.jsx
Labels: PR / Needs work

#4891 Bug 1538804 - Update targeting for CFR Pinned tabs to include more locales and TLDs
  lib/CFRMessageProvider.jsm
  test/unit/asrouter/CFRMessageProvider.test.js
Labels: PR / R+

#4900 Bug 1539823 - Add schema for below-search-box FxA Snippet
  content-src/asrouter/templates/SimpleBelowSearchSnippet/SimpleBelowSearchSnippet.jsx
  content-src/asrouter/templates/SimpleBelowSearchSnippet/SimpleBelowSearchSnippet.schema.json
  content-src/asrouter/templates/template-manifest.jsx
  lib/SnippetsTestMessageProvider.jsm
  test/unit/asrouter/SnippetsTestMessageProvider.test.js
  test/unit/asrouter/templates/SimpleBelowSearchSnippet.test.jsx
Labels: PR / R+

#4897 Message schema for CFR FxA Message
  content-src/asrouter/schemas/panel/cfr-fxa-bookmark.schema.json
  test/unit/asrouter/schemas/panel/cfr-fxa-bookmark.schema.test.js
Labels: PR / Needs review

#4902 (nobug): Add experimentation info for asrouter
  content-src/asrouter/docs/experiment-guide.md
Labels: PR / R+

#4903 Bug 1544467 - Add the missing field for undesired events of CFR
  lib/ASRouter.jsm
  test/unit/asrouter/ASRouter.test.js
Labels: PR / Needs review

#4884 Bug 1540939 - Remove SnippetsFeed and related components
  content-src/activity-stream.jsx
  content-src/asrouter/components/SnippetBase/_SnippetBase.scss
  content-src/asrouter/docs/debugging-docs.md
  content-src/lib/snippets.js
  docs/v2-system-addon/snippets.md
  karma.mc.config.js
  lib/ActivityStream.jsm
  lib/SnippetsFeed.jsm
  test/unit/content-src/lib/snippets.test.js
  test/unit/lib/ActivityStream.test.js
  test/unit/lib/SnippetsFeed.test.js
Labels: PR / Needs work

#4906 Bug 1544627 - render ASRouterUISurface from Base.jsx
  content-src/activity-stream.jsx
  content-src/asrouter/asrouter-content.jsx
  content-src/components/Base/Base.jsx
  content-src/lib/asroutercontent.js
  test/unit/activity-stream.test.jsx
  test/unit/common/Reducers.test.js
Labels: PR / R+

#4908 Bug 1544867 - Make AS devtools collapsible
  content-src/components/ASRouterAdmin/ASRouterAdmin.jsx
  content-src/components/ASRouterAdmin/ASRouterAdmin.scss
  content-src/components/ASRouterAdmin/SimpleHashRouter.jsx
  content-src/components/Base/Base.jsx
  content-src/styles/_activity-stream.scss
  test/unit/content-src/components/ASRouterAdmin.test.jsx
  test/unit/content-src/components/Base.test.jsx
Labels: PR / R+

#4907 Bug 1543723 - The import message icon is cut when the screen is horizontally resized to less than half screen
  content-src/components/ManualMigration/_ManualMigration.scss
Labels: PR / R+

#4893 Bug 1543108 - Land a new provider for CFR FxA messages
  lib/ActivityStream.jsm
  test/browser/browser_asrouter_cfr.js
Labels: PR / R+

#4904 bug 1543800 - local layout
  lib/ActivityStream.jsm
  lib/DiscoveryStreamFeed.jsm
  test/unit/lib/DiscoveryStreamFeed.test.js
Labels: PR / R+

#4905 Bug 1544574 - Simplify SPOC impression handler of DiscoveryStreamFeed
  common/Reducers.jsm
  lib/DiscoveryStreamFeed.jsm
  test/unit/lib/DiscoveryStreamFeed.test.js
Labels: PR / Needs review

#4915 bug 1545448 - Fixing bug around feed data last updated.
  lib/DiscoveryStreamFeed.jsm
  test/unit/lib/DiscoveryStreamFeed.test.js
Labels: PR / R+

#4913 bug 1545194 - v1 personalization for 68
  lib/ActivityStream.jsm
Labels: PR / R+

#4919 Bug 1545455 - Bottom corners of images in bordered cards should be rounded
  content-src/components/DiscoveryStreamComponents/CardGrid/_CardGrid.scss
Labels: PR / Needs review

#4922 Port 1544887 - Fix some in-content page icon colors in dark mode. r=dao
  lib/AboutPreferences.jsm
Labels: PR / Needs review

#4918 Bug 1545487 - Remove browser migration (import bookmarks, history, etc) message from Activity Stream
  common/Actions.jsm
  common/PrerenderData.jsm
  content-src/components/Base/Base.jsx
  content-src/components/ManualMigration/ManualMigration.jsx
  content-src/components/ManualMigration/_ManualMigration.scss
  content-src/styles/_activity-stream.scss
  content-src/styles/_icons.scss
  data/content/assets/glyph-import-16.svg
  lib/ActivityStream.jsm
  lib/HighlightsFeed.jsm
  lib/ManualMigration.jsm
  lib/TopSitesFeed.jsm
  locales-src/en-US/strings.properties
  test/unit/content-src/components/ConfirmDialog.test.jsx
  test/unit/content-src/components/ManualMigration.test.jsx
  test/unit/lib/ActivityStream.test.js
  test/unit/lib/HighlightsFeed.test.js
  test/unit/lib/ManualMigration.test.js
  test/unit/lib/TopSitesFeed.test.js
Labels: PR / R+ with nits

#4924 Bug 1545122 - Landing local layout 66-release-2-above-6-below-4 for D…
  lib/ActivityStream.jsm
  lib/DiscoveryStreamFeed.jsm
Labels: PR / R+

#4926 (nobug) - Make devtools button hidden but clickable
  content-src/components/ASRouterAdmin/ASRouterAdmin.jsx
  content-src/components/ASRouterAdmin/ASRouterAdmin.scss
Labels: PR / R+

#4925 Bug 1544574 - Add a followup fix to handle the special case
  lib/DiscoveryStreamFeed.jsm
Labels: PR / Needs review

#4916 Bug 1500061 - Switch to regular script tags, tighten CSP
  bin/render-activity-stream-html.js
Labels: PR / R+ with nits

#4927 (nobug) Make button for collapsing devtools less prominent
  content-src/components/ASRouterAdmin/ASRouterAdmin.jsx
  content-src/components/ASRouterAdmin/ASRouterAdmin.scss
Labels: PR / R+ with nits

#4929 Bug 1546474 - Use aria-label in addition to title for block button in snippet templates
  content-src/asrouter/components/SnippetBase/SnippetBase.jsx
Labels: PR / R+

#4930 Bug 1546590 - Hardcoded layout results in only one new tab page rende…
  lib/DiscoveryStreamFeed.jsm
  test/unit/lib/DiscoveryStreamFeed.test.js
Labels: PR / Needs review

#4932 Bug 1546768 - Design fixes for Special FXA snippet
  content-src/asrouter/templates/SimpleBelowSearchSnippet/_SimpleBelowSearchSnippet.scss
  content-src/components/Search/_Search.scss
Labels: PR / R+

#4933 (nobug) - Properly close snippets div tag
  bin/render-activity-stream-html.js
Labels: PR / R+

#4934 Bug 1535448 - Handle focus state while navigating with keyboard
  content-src/components/DiscoveryStreamComponents/CardGrid/_CardGrid.scss
  content-src/components/DiscoveryStreamComponents/DSCard/_DSCard.scss
  content-src/components/DiscoveryStreamComponents/Hero/_Hero.scss
  content-src/components/DiscoveryStreamComponents/List/_List.scss
  content-src/components/DiscoveryStreamComponents/TopSites/_TopSites.scss
  content-src/styles/_mixins.scss
  content-src/styles/_variables.scss
Labels: PR / Needs review

#4938 Trailhead basic flow with single message, no bundles
  content-src/asrouter/asrouter-content.jsx
  content-src/asrouter/docs/targeting-attributes.md
  content-src/asrouter/templates/OnboardingMessage/OnboardingMessage.jsx
  content-src/asrouter/templates/Trailhead/Trailhead.jsx
  lib/ASRouterTargeting.jsm
  lib/OnboardingMessageProvider.jsm
  test/unit/asrouter/ASRouterTargeting.test.js
  test/unit/asrouter/asrouter-content.test.jsx
  test/unit/asrouter/templates/OnboardingMessage.test.jsx
Labels: PR / Needs review

#4940 Bug 1546683 - Use fluent to localize trailhead first run
  content-src/asrouter/templates/OnboardingMessage/OnboardingMessage.jsx
  content-src/asrouter/templates/Trailhead/Trailhead.jsx
  data/trailhead.ftl
  jar.mn
  lib/OnboardingMessageProvider.jsm
Labels: PR / Needs review

#4942 Bug 1547746 - Render trailhead cards in a new portal / on the top of the page
  bin/render-activity-stream-html.js
  content-src/asrouter/asrouter-content.jsx
  test/unit/asrouter/asrouter-content.test.jsx
Labels: PR / Needs review

#4943 Bug 1547744 - Add modal overlay to trailhead
  content-src/asrouter/components/ModalOverlay/ModalOverlay.jsx
  content-src/asrouter/templates/Trailhead/Trailhead.jsx
  content-src/asrouter/templates/Trailhead/Trailhead.scss
  content-src/styles/_activity-stream.scss
Labels: PR / Needs review

#4945 Bug 1547744 - (follow-up) remove welcome class and render cards
  content-src/asrouter/templates/Trailhead/Trailhead.jsx
Labels: PR / Needs review

#4946 (nobug) - Partial quick visual changes for trailhead first run
  content-src/asrouter/templates/Trailhead/Trailhead.jsx
  content-src/asrouter/templates/Trailhead/Trailhead.scss
  content-src/styles/_variables.scss
  data/trailhead.ftl
  lib/OnboardingMessageProvider.jsm
Labels: PR / Needs review

#4944 Bug 1547748 - add includeBundle stuff to trailhead
  content-src/asrouter/templates/Trailhead/Trailhead.jsx
  lib/ASRouter.jsm
  lib/OnboardingMessageProvider.jsm
  test/unit/asrouter/ASRouter.test.js
Labels: PR / Needs review

#4947 (nobug) Trailhead basic card styles
  content-src/asrouter/components/ModalOverlay/_ModalOverlay.scss
  content-src/asrouter/templates/OnboardingMessage/OnboardingMessage.jsx
  content-src/asrouter/templates/OnboardingMessage/_OnboardingMessage.scss
  content-src/asrouter/templates/Trailhead/Trailhead.jsx
  content-src/asrouter/templates/Trailhead/Trailhead.scss
Labels: PR / Needs review

#4949 (nobug) - Switch existing onboarding to use fluent-dom
  content-src/asrouter/templates/OnboardingMessage/OnboardingMessage.jsx
  lib/OnboardingMessageProvider.jsm
Labels: PR / Needs work

#4950 (nobug) - Update finalized strings for layout and cards
  content-src/asrouter/templates/Trailhead/Trailhead.jsx
  content-src/asrouter/templates/Trailhead/Trailhead.scss
  content-src/styles/_variables.scss
  data/trailhead.ftl
  lib/OnboardingMessageProvider.jsm
Labels: PR / Needs review

#4956 (nobug) - Add and use image assets for modal and cards
  content-src/asrouter/templates/OnboardingMessage/_OnboardingMessage.scss
  content-src/asrouter/templates/Trailhead/Trailhead.jsx
  content-src/asrouter/templates/Trailhead/Trailhead.scss
  content-src/styles/_variables.scss
  data/content/assets/trailhead/accounts-form-bg.jpg
  data/content/assets/trailhead/benefit-knowledge.png
  data/content/assets/trailhead/benefit-privacy.png
  data/content/assets/trailhead/benefit-products.png
  data/content/assets/trailhead/card-illo-devices.png
  data/content/assets/trailhead/card-illo-fbcont.png
  data/content/assets/trailhead/card-illo-ffmonitor.png
  data/content/assets/trailhead/card-illo-ffsend.png
  data/content/assets/trailhead/card-illo-lockwise.png
  data/content/assets/trailhead/card-illo-mobile.png
  data/content/assets/trailhead/card-illo-pledge.png
  data/content/assets/trailhead/card-illo-pocket.png
  data/content/assets/trailhead/card-illo-private.png
  data/content/assets/trailhead/card-illo-sendtab.png
  data/content/assets/trailhead/card-illo-tracking.png
  data/content/assets/trailhead/firefox-logo.png
  lib/OnboardingMessageProvider.jsm
Labels: PR / Needs review

#4954 (nobug) Rename Trailhead.scss to _Trailhead.scss
  content-src/asrouter/templates/Trailhead/_Trailhead.scss
Labels: PR / R+

#4951 (nobug) - Disable fixed search and fixed settings icon when showing cards
  content-src/asrouter/templates/Trailhead/Trailhead.jsx
  content-src/asrouter/templates/Trailhead/_Trailhead.scss
  content-src/components/Base/Base.jsx
  content-src/components/Search/_Search.scss
Labels: PR / R+
