Repository mozilla/activity-stream, pull requests merged in 2019-06, with the labels that each got.

#5086 Bug 1554293 - Make sure pocket cards are optimized for screen readers
  content-src/components/Card/Card.jsx
  content-src/components/CollapsibleSection/CollapsibleSection.jsx
  content-src/components/DiscoveryStreamComponents/DSLinkMenu/DSLinkMenu.jsx
  content-src/components/TopSites/TopSite.jsx
Labels: PR / R+

#5085 Bug 1542863 - Adding feed load fail fallback.
  common/Actions.jsm
  content-src/components/DiscoveryStreamBase/DiscoveryStreamBase.jsx
  content-src/components/DiscoveryStreamComponents/CardGrid/CardGrid.jsx
  content-src/components/DiscoveryStreamComponents/DSEmptyState/DSEmptyState.jsx
  content-src/components/DiscoveryStreamComponents/DSEmptyState/_DSEmptyState.scss
  content-src/components/DiscoveryStreamComponents/Hero/Hero.jsx
  content-src/components/DiscoveryStreamComponents/List/List.jsx
  content-src/lib/selectLayoutRender.js
  content-src/styles/_theme.scss
  content-src/styles/_variables.scss
  data/content/assets/spinner.svg
  lib/DiscoveryStreamFeed.jsm
  test/unit/content-src/components/DiscoveryStreamComponents/DSEmptyState.test.jsx
  test/unit/lib/DiscoveryStreamFeed.test.js
Labels: PR / Needs review

#5067 Bug 1552809 - Enable Bookmark panel messages to work without translations
  lib/ASRouter.jsm
  lib/BookmarkPanelHub.jsm
  lib/PanelTestProvider.jsm
  test/unit/asrouter/PanelTestProvider.test.js
  test/unit/lib/BookmarkPanelHub.test.js
Labels: PR / R+

#5087 Bug 1552932 - [Top Sites] Focus and Hover UX updates
  content-src/components/DiscoveryStreamComponents/TopSites/_TopSites.scss
  content-src/components/TopSites/_TopSites.scss
Labels: PR / R+

#5095 Bug 1556887 - Convert strings in Top Sites dialog to use fluent (header and body)
  .eslintrc.js
  bin/bug_xxx_newtab.py
  content-src/components/CollapsibleSection/_CollapsibleSection.scss
  content-src/components/TopSites/TopSiteForm.jsx
  content-src/components/TopSites/TopSiteFormInput.jsx
  locales-src/en-US/strings.properties
  locales-src/newtab.ftl
  test/unit/content-src/components/TopSites.test.jsx
Labels: PR / R+

#5064 Bug 1550119 - Pass Adzerk shim to spoc click and view pings.
  content-src/components/DiscoveryStreamComponents/CardGrid/CardGrid.jsx
  content-src/components/DiscoveryStreamComponents/DSCard/DSCard.jsx
  content-src/components/DiscoveryStreamComponents/Hero/Hero.jsx
  content-src/components/DiscoveryStreamComponents/List/List.jsx
  content-src/components/DiscoveryStreamImpressionStats/ImpressionStats.jsx
  docs/v2-system-addon/data_dictionary.md
  docs/v2-system-addon/data_events.md
  lib/TelemetryFeed.jsm
  test/unit/lib/TelemetryFeed.test.js
Labels: PR / Awaiting data review, PR / R+

#5058 Bug 1550115 - Include impression id to spoc request.
  lib/DiscoveryStreamFeed.jsm
  test/unit/lib/DiscoveryStreamFeed.test.js
  test/unit/unit-entry.js
Labels: PR / Needs review

#5070 Bug 1553926 - Re-enable fetch-options eslint plugin
  .eslintrc.js
Labels: PR / Needs review

#5097 Backport 1552714 - Migrate all remaining callsites to use WebIDL DOML…
  .eslintrc.js
  lib/BookmarkPanelHub.jsm
  lib/CFRPageActions.jsm
Labels: PR / Needs review

#5088 Bug 1554734 - Also support context-menu arrow key navigation
  content-src/components/ContextMenu/ContextMenu.jsx
  test/unit/content-src/components/ContextMenu.test.jsx
Labels: PR / R+

#5101 Bug 1552937 - Preserve hover state on cards when hovering over context menu
  content-src/components/DiscoveryStreamComponents/DSCard/_DSCard.scss
Labels: PR / R+

#5105 (nobug) - Update eslint-plugin-mozilla to 1.3.0 and ignore prettier for now
  .eslintrc.js
  .prettierignore
  package-lock.json
  package.json
Labels: PR / Needs review

#5107 Bug 1558968 - Return to AMO is broken after Bug 1548697
  content-src/asrouter/asrouter-content.jsx
Labels: PR / Needs review

#5090 Bug 1523403 - Test coverage for DS front-end
  content-src/components/DiscoveryStreamComponents/DSLinkMenu/DSLinkMenu.jsx
  karma.mc.config.js
  test/unit/content-src/components/DiscoveryStreamComponents/DSCard.test.jsx
  test/unit/content-src/components/DiscoveryStreamComponents/DSLinkMenu.test.jsx
  test/unit/content-src/components/DiscoveryStreamComponents/Hero.test.jsx
  test/unit/content-src/components/DiscoveryStreamComponents/List.test.jsx
  test/unit/content-src/components/DiscoveryStreamComponents/TopSites.test.jsx
Labels: PR / Needs review

#5110 no bug - Fixing impression issue
  lib/DiscoveryStreamFeed.jsm
  test/unit/lib/DiscoveryStreamFeed.test.js
Labels: PR / R+

#5102 Bug 1551711 - Added alt-text prop to all snippet schemas that include an icon.
  content-src/asrouter/templates/EOYSnippet/EOYSnippet.schema.json
  content-src/asrouter/templates/SimpleBelowSearchSnippet/SimpleBelowSearchSnippet.jsx
  content-src/asrouter/templates/SimpleBelowSearchSnippet/SimpleBelowSearchSnippet.schema.json
  content-src/asrouter/templates/SimpleSnippet/SimpleSnippet.jsx
  content-src/asrouter/templates/SimpleSnippet/SimpleSnippet.schema.json
  content-src/asrouter/templates/SubmitFormSnippet/SubmitFormSnippet.jsx
  content-src/asrouter/templates/SubmitFormSnippet/SubmitFormSnippet.schema.json
Labels: PR / R+

#5106 Bug 1558903 - Passing proper shims for specific events.
  content-src/components/DiscoveryStreamComponents/DSCard/DSCard.jsx
  content-src/components/DiscoveryStreamComponents/Hero/Hero.jsx
  content-src/components/DiscoveryStreamComponents/List/List.jsx
Labels: PR / Needs review

#5113 no bug - Adding a test for shims on ds card
  test/unit/content-src/components/DiscoveryStreamComponents/DSCard.test.jsx
Labels: PR / Needs review

#5109 Bug 1558905 - Handle two new types of shims passed in two existing ev…
  content-src/components/DiscoveryStreamComponents/DSCard/DSCard.jsx
  content-src/components/DiscoveryStreamComponents/DSLinkMenu/DSLinkMenu.jsx
  content-src/components/DiscoveryStreamComponents/Hero/Hero.jsx
  content-src/components/DiscoveryStreamComponents/List/List.jsx
  content-src/lib/link-menu-options.js
Labels: PR / Awaiting data review, PR / R+

#5112 Bug 1559143 - Checkbox UI for prefs
  lib/AboutPreferences.jsm
  test/unit/lib/AboutPreferences.test.js
Labels: PR / Needs review

#5103 Bug 1553933 - Ensure we delete any remote spoc data when user opts ou…
  lib/ActivityStream.jsm
  lib/DiscoveryStreamFeed.jsm
  test/unit/lib/DiscoveryStreamFeed.test.js
Labels: PR / Needs review

#5115 Bug 1559380 - The ESC key should dismiss the context menu if accessed via keyboard navigation
  content-src/components/ContextMenu/ContextMenu.jsx
Labels: PR / Needs review

#5118 Bug 1536285 - Add Highlights as the final discovery stream section
  content-src/components/DiscoveryStreamBase/DiscoveryStreamBase.jsx
  content-src/components/DiscoveryStreamComponents/Highlights/Highlights.jsx
  content-src/components/DiscoveryStreamComponents/Highlights/_Highlights.scss
  content-src/components/Sections/Sections.jsx
  content-src/styles/_activity-stream.scss
  lib/AboutPreferences.jsm
  lib/ActivityStream.jsm
  test/browser/browser_highlights_section.js
  test/unit/content-src/components/DiscoveryStreamComponents/Highlights.test.jsx
  test/unit/lib/AboutPreferences.test.js
Labels: PR / Needs review

#5117 Port 1558917 - Referrer no longer sent for new tab links r=thecount
  lib/PlacesFeed.jsm
  test/unit/lib/PlacesFeed.test.js
  test/unit/unit-entry.js
Labels: PR / On hold for now

#5094 Bug 1553205 - FxA metrics values sometimes don't get set (#5053)
  content-src/asrouter/templates/Trailhead/Trailhead.jsx
Labels: PR / On hold for now

#5093 Bug 1552596 - Revert dynamic line clamping in favor of performant static line clamping (#5044)
  content-src/components/DiscoveryStreamComponents/DSCard/DSCard.jsx
  content-src/components/DiscoveryStreamComponents/DSCard/_DSCard.scss
  content-src/components/DiscoveryStreamComponents/Hero/Hero.jsx
  content-src/components/DiscoveryStreamComponents/Hero/_Hero.scss
  content-src/components/DiscoveryStreamComponents/List/List.jsx
  content-src/components/DiscoveryStreamComponents/List/_List.scss
  content-src/lib/clamp-total-lines.js
  content-src/styles/_mixins.scss
  test/unit/content-src/lib/clamp-total-lines.test.js
Labels: PR / On hold for now

#5092 Bug 1550858 - Update final final final final final actions or urls (#5046)
  lib/OnboardingMessageProvider.jsm
Labels: PR / On hold for now

#5120 Bug 1560043 - Start using npm 6.9
  .nvmrc
  package-lock.json
  package.json
Labels: PR / Needs review

#5123 Bug-1556039 - Fluent changes to 1556039 (removal of sr-only) spans
  bin/bug_xxx_newtab.py
  content-src/components/Card/Card.jsx
  content-src/components/CollapsibleSection/CollapsibleSection.jsx
  content-src/components/DiscoveryStreamComponents/DSLinkMenu/DSLinkMenu.jsx
  content-src/components/TopSites/TopSite.jsx
  locales-src/en-US/strings.properties
  locales-src/newtab.ftl
Labels: PR / Needs review

#5127 Bug 1561091 - Refactor getFormattedMessage to set fluent attributes or use plain text
  content-src/components/CollapsibleSection/CollapsibleSection.jsx
  content-src/components/DiscoveryStreamBase/DiscoveryStreamBase.jsx
  content-src/components/FluentOrText/FluentOrText.jsx
  content-src/components/Sections/Sections.jsx
  lib/SectionsManager.jsm
  test/unit/content-src/components/FluentOrText.test.jsx
Labels: PR / Needs review

#5119 Bug 1559383 - The arrow keys do not go through the available context menu option unless you press TAB first
  content-src/components/ContextMenu/ContextMenu.jsx
Labels: PR / R+

#5128 Bug 1558811 - Fixed :hover style for the collapsible section menu
  content-src/components/CollapsibleSection/_CollapsibleSection.scss
Labels: PR / Needs review

#5136 (nobug) - Run codespell lint for fluent files
  mochitest.sh
Labels: PR / Needs review

#5135 Bug 1559689 - Allow history highlights that happen to be bookmarked to appear in normal history order
  lib/HighlightsFeed.jsm
  test/unit/lib/HighlightsFeed.test.js
Labels: PR / Needs review

#5130 Bug 1561694 - Switching hardcoded layout to `3-col-7-row-octr`
  lib/DiscoveryStreamFeed.jsm
Labels: PR / R+

#5124 Bug 1560448 - Fixing campaign id in hero spocs
  content-src/components/DiscoveryStreamComponents/Hero/Hero.jsx
Labels: PR / R+

#5121 Bug 1560235 - Fixing alignment issue and regression.
  content-src/components/DiscoveryStreamComponents/DSCard/_DSCard.scss
Labels: PR / Needs review

#5122 Bug 1560352 - Send version number to spoc request
  lib/DiscoveryStreamFeed.jsm
Labels: PR / R+

#5131 Bug 1561335 - cleanup eslintrc prettier changes
  .eslintrc.js
Labels: PR / R+ with nits

#5138 Bug 1559382 - Dismissing the 2nd to last card will wrongly dismiss th…
  content-src/lib/selectLayoutRender.js
Labels: PR / Needs review

#5137 Bug 1551273 - Turning on DS for non-nightly users
  lib/ActivityStream.jsm
Labels: PR / Needs review
